tidyverse/ggplot2

- R/layer.r
Problem: 'stop' does not separate elements in the dots argument, therefore the error message (R/layer.r line 160f) is clumped:
Reproducible example:
```R
f <- function (a) ggplot(data.frame(x=rnorm(10),y=1:10), aes_q(x=quote(x),y=quote(y),color=a)) + geom_point()
f(1) # runs fine
f(1:3) # returns the error message:
Error: Aesthetics must either be length one, or the same length as the dataProblems:1:3
The fix would result in
...
f(1:3)
Error: Aesthetics must either be length one, or the same length as the data
Problems: 1:3
```
> layer.r: added missing error message newline/spacer

- R/quick-plot.r
- man/qplot.Rd
The URL for the sample chapter on the qplot function in both the R docs and the man docs were pointing to an old, no longer available URL. I've updated the documentation to point to the latest URL.
> Fix for bad URL in qplot docs

- R/geom-path-density2d.r
"estimatation" --> "estimation"
Only fixed the roxygen header. Would need to rebuild the doc itself.
> Fixed typo in `geom_density2d` roxygen2 Description

- NEWS
- R/scale-brewer.r
- man/scale_brewer.Rd
The order of colors in particular, and the fact that it cannot be easily
reversed (pending a change in package scales) makes scale_*_distiller
almost useless at the moment.
These are simple fixes and should be easy to pull.
> Improvements to scale_*_distiller

- NEWS
- R/facet-grid-.r
- R/facet-wrap.r
- R/plot-render.r
- R/scale-.r
- inst/tests/helper-plot-data.r
These were found by setting
```
options(warnPartialMatchAttr = TRUE,
warnPartialMatchDollar = TRUE,
warn = 2)
```
Using hadley/testthat#269 with `options("testthat.suppress" = NULL)` and running
`devtools::test()` and `vtest::vtest()` until there were no more partial
match messages.
There may still be some instances in the code base, but I think this
finds the vast majority.
> Fix all found instances of partial matching

- NEWS
- R/coord-munch.r
- inst/tests/test-munch.r
> Resubmission of #823

- R/facet-wrap.r
- inst/tests/test-sanitise-dim.r
As discussed in issue [#801](https://github.com/hadley/ggplot2/issues/801), `facet_wrap` doesn't properly check the `nrow` and `ncol` arguments, particularly negative values.
I've added a `sanitise_dim` function (plus some tests) to deal with this.
> Added sanitise_dim function for Issue #801

- R/theme-defaults.r
A very minor change: I've removed tick marks from ` theme_minimal() ` as I think that is more in keeping with "minimalism". The black ticks seemed a little visually unnecessary. 
Incidentally, removing black ticks it also aligns minimal to the default plotly theme.
All good if you don't like the idea.
```r 
qplot(data = mtcars, x = mpg, y = wt) + theme_minimal() 
```
Before:
After:
Tom
> Remove tick marks from theme_minimal

- NEWS
- R/facet-grid-.r
- R/facet-labels.r
- R/facet-wrap.r
- R/theme-defaults.r
- R/theme-elements.r
- R/theme.r
- man/facet_grid.Rd
- man/facet_wrap.Rd
- man/scale_hue.Rd
- man/theme.Rd
This implements a `switch_strips` argument to `facet_wrap` and `facet_grid`, which can be set to `x`, `y` or `both` (the latter only for grids). This allows to display the facet strips near the axes. They then act as axes subtitles. The padding between the switched strips and their corresponding axes can be adjusted through a new theme setting.
Displaying the facet titles near the axes especially makes sense when the facet title directly characterize a change in the axis (for example, a transformation, a different measure, etc). This should be typically used in conjunction with a theme without boxes around the strips. I go over this in the updated documentation.
A grid facetting with strips switched to both axes:
A wrap facetting with free scales and strips switched to the x axis:
> Facet titles

- NEWS
- R/geom-boxplot.r
- R/geom-point-.r
- R/geom-pointrange.r
- man/geom_boxplot.Rd
- man/geom_point.Rd
This PR adds an aesthetic option `stroke` to `geom_point` that makes it possible to specify the stroke width of point shapes 21-25 (see #1085, I had to resubmit because you can't force push when an issue is closed).
> Add stroke option to geom_point.

- NEWS
- R/save.r
- man/ggsave.Rd
Thank you for the fantastic ggplots package!
This is a suggested implementation for specifying a file extension in ```ggsave``` to allow device matching (pdf, png, jpg, etc.) for filenames without extension. The suggestion is motivated by the problem of using ggsave in a shinyApp for letting the user download a plot (for example addressed on StackOverflow here: http://stackoverflow.com/questions/14810409/save-plots-made-in-a-shiny-app). Because the shiny server provides a temporary file without extension, ggsave can't match to any of the internally defined device functions. I'm not aware of a currently available solution to this problem and although there are several work-arounds, I like the simplicity of ggsave and wanted to suggest this solution (not sure if it's the best way to do it, …
> file extension parameter for ggsave() to allow device specification for files without extension

- NEWS
- R/guide-legend.r
A small change to allow for:
p <- ggplot(mtcars,aes(x = mpg,y = disp,size = cyl)) + geom_point()
p + scale_size_continuous(guide = guide_legend(override.aes(color = "red")))
> rename aes in override.aes to allow for american spellings

- NEWS
- R/stat-bin2d.r
- man/geom_bin2d.Rd
- tests/testthat/test-stats.r
With this change, you can specify one set of breaks to `stat_bin2d` without setting the other.  This is particularly useful when binning by date in one dimension, and using a transformed scale in the other dimension.  This way, you don't have to figure out how to reconstruct the default breaks for the transformed scale.  For example:
```r
breaks <- list( x = sort(unique(movies$year)) - 0.5, y = NA )
g <- ggplot(movies) + aes(x = year, y = length)
g + stat_bin2d(breaks=breaks) + scale_y_log10()
```
> Handle stat_bin2d(breaks=(x=NA,y=Something))

- DESCRIPTION
- NEWS
- R/scale-brewer.r
- man/scale_brewer.Rd
Plus minor example and documentation fixes
> Add access to direction argument of scales::brewer_pal

- tests/testthat/test-aes-grouping.r
- tests/testthat/test-scales-breaks-labels.r
Only two tests needed to be adapted after removing `library(plyr)`
> Don't attach plyr in tests

- R/utilities-layer.r
- tests/testthat/test-aes-grouping.r
to allow distinguishing this case (prerequisite for #992)
This implicitly assumes `plyr::id` doesn't ever return 0. Tests in `plyr` test that sequences created by `id` start at 1, so we're probably safe here.
All tests pass, but I'm not sure if this has any other implications I'm not aware of.
> Use group identifier -1 if no group aesthetic is specified

- R/geom-violin.r
- man/geom_violin.Rd
Since violin plots are not known in every field of data analysis yet, it could be helpful to include a paper introducing the concept.
Hintze et al. seems to be the first and only paper on this matter: http://amstat.tandfonline.com/doi/abs/10.1080/00031305.1998.10480559
> add reference to paper introducing violin plots

- R/utilities-layer.r
- tests/testthat/test-utilities.r
Convenience function to encapsulate the check if the data are grouped. With test.
It still only checks only the first element of the group column, a comment explains why this works.
For #992.
(Sorry for being such a pain, but I really hate to check a vector if checking a value is enough.)
> has_groups()

- R/facet-locate.r
- R/utilities-layer.r
- `PANEL` is not taken into account for computing grouping when no `group` aesthetic is set
- required for #992
- otherwise, no warning can be given for the following example: `ggplot(expand.grid(x=1:10, y=1:10), aes(x, y)) + geom_boxplot() + facet_wrap(~y)`
- extract constant `NO_PANEL`, set it to -1
- just like `NO_GROUP`
All tests pass locally.
> Tweaks for PANEL

- R/geom-path-.r
Info shown below is from file ```geom-path-.r```, line 117
**Original error text:** geom_path: Each group consist of only one observation. Do you need to adjust the group aesthetic?
**Updated error text:** geom_path: Each group consist**s** of only one observation. Do you need to adjust the group aesthetic?
> fixed typo in error text of geom-path-.r: add "s" to "consist"

- vignettes/extending-ggplot2.Rmd
`@inheritParams ggplot2::stat_identity` had a single `:` in two places. Both were fixed.
> Fixed missing ":" in two places in "extending" vignette

- R/stat-bin.r
This closes #1349. This change makes it clear that `StatBin` is for continuous x data.
> StatBin/StatBar check for continuous/discrete data

- R/plot.r
to record library("ggplot2") on the graphics engine display list (for replaying recordPlot() in a different session without having to manually reload ggplot2)
> add recordGraphics() to print.ggplot() 

- R/position-.r
- R/position-fill.r
- R/position-jitter.r
- R/position-nudge.R
- R/position-stack.r
*R/position-.r
- Wrong call signature
*R/position-fill.r
- Obsolete function `setup_defaults`, probably a refactoring slip up.
- Colliding should be in the per panel, rather than per layer.
*R/position-jitter.r
- Inconsistent call signature name
*R/position-nudge.R
- Inconsistent call signature name
*R/position-stack.r
- Make use of new `setup_data` API
> Fix multiple tiny issues in the position classes

- NEWS.md
Here you go.
Also I was thinking that switching labels with `facet_grid()` would be clearer if `switch` would take "rows" and "cols" instead of "y" and "x". On the other hand this would not make sense for `facet_wrap()`, where we really move the strips near the specified axis, so "x" and "y" is the best choice there.
Would it be desirable to have different sets of value for `switch` in wrap and grid?
> Update news with labels changes

- NEWS
- NEWS.md
- R/fortify-map.r
The borders() function is extremely handy if you are working with geographical data but the specification of the geographical region-of-interest is limited to defining regions via text strings i.e. via the regions="" argument. However, both the maps::map() function and ggplot2::map_data() accept geographic region specification using xlim and ylim arguments. This modification extemds that functionality to borders()
> Added xlim and ylim arguments to borders()

- NEWS.md
- R/stat-density-2d.r
Resolves
-  Minor slip up, user supplied h is ignored.
-  #1448, This was a regression due to the `...` refactoring.
I think more refactoring is needed to lift all the `stat$compute_group` parameters into the user API `stat()` function.
> Fix statdensity2d

- DESCRIPTION
- NEWS.md
- R/ggproto.r
This fixes #1444. I'd suggest making a release after merging, since this a blocker for many people.
> Check for non-zero length before calling list2env()

- NEWS.md
- R/theme-defaults.r
The `element_text` function is called with a comma after its last argument. While this does not produce a bug, it is an irregularity better to be fixed.
> Remove superfluous comma in function arguments

- NEWS.md
- R/stat-density.r
- R/stat-ydensity.r
- man/geom_density.Rd
- man/geom_violin.Rd
It is sometimes useful to set a fixed bandwidth, to make it easier to compare between facets for example. Here is some code to demonstrate a use case
```r
d <- data.frame(
a=rep(c("a", "b"), each=100),
x=c(rnorm(50, 0, 0.2), rnorm(50, 0.5, 0.2), rnorm(100, 0, 2))
)
ggplot(d) + geom_density(aes(x=x)) + facet_wrap(~a)
ggplot(d) + geom_density(aes(x=x), bw=0.3) + facet_wrap(~a)
ggplot(d) + geom_density(aes(x=x)) + facet_wrap(~a, scales="free_x") 
ggplot(d) + geom_density(aes(x=x), bw=0.3) + facet_wrap(~a, scales="free_x")
```
I've been wanting this a few times already. I resorted to computing the densities manually and then plotting. Today I decided to be less lazy ;-)
> Add access to bw argument of density

- vignettes/extending-ggplot2.Rmd
Doesn't look like there was ever a 1.1.0 release, so I think this should be 2.0.0.
> ggplot2 version should be 2.0.0 not 1.1.0 in vignette?

- NEWS.md
- R/theme-defaults.r
While theme_void is meant for drawings or plots in which the coordinates
are self describing (like maps for examples), subplots and aesthetics
still need to be described. The legend itself can be removed with
`guide = none` in the scale functions.
> Still label legends and facets in theme_void

- R/facet-wrap.r
The swap code incorrectly resulted in nrow and ncol being equal or both being NULL. Using dummy variables will prevent this.
More details about the problem can be seen in hadley/ggplot2#1279
> Fix swapping of nrow & ncol for vertical facetting

- NEWS.md
- R/theme-defaults.r
addresses issue #1555 where some elements added under certain themes inherit "element_blank" and cannot be updated, e.g.
`ggplot(mtcars, aes(wt, mpg)) + geom_point() + theme_classic() + theme(panel.grid.major.y = element_line(colour = "pink", size = 4))`
update explicitly declares parent element as necessary and children elements as element_blank
> Updates theme-defaults.r (#1555)

- NEWS.md
- R/scale-continuous.r
Hi Hadley,
This makes the list of `x` aesthetics symmetric with `y` aesthetics. This is needed to fix some issues in ggstance.
> Extend list of x aesthetics

- .gitignore
- NEWS.md
- R/coord-map.r
- R/geom-polygon.r
- R/guide-colorbar.r
- R/labels.r
- R/plot-build.r
- R/position-dodge.r
- R/quick-plot.r
- R/scale-discrete-.r
- R/scale-hue.r
- R/stat-summary.r
- R/theme-defaults.r
- R/theme-elements.r
- R/theme.r
- R/utilities.r
- man/coord_map.Rd
- man/geom_polygon.Rd
- man/ggtheme.Rd
- man/guide_colourbar.Rd
- man/labs.Rd
- man/position_dodge.Rd
- man/qplot.Rd
- man/scale_discrete.Rd
- man/scale_hue.Rd
- man/stat_summary.Rd
- man/theme.Rd
- tests/testthat/test-labels.r
- new `subtitle` parameter for `labs` and `ggtitle`
- documented the `subtitle` parameter in `ggtitle` since it's an explicit parameter
- new `caption` parameter for `labs` function
- new `plot.subtitle` theme element
- new `plot.caption` theme element (default alignment is right-justified)
- updated default alignment for `plot.title` and `plot.subtitle` (now left-justified by default)
- updated roxygen documentation with `subtitle` and `caption` examples
- added test for `title`, `subtitle` & `caption` settings
- cleaned up `=` spacing in a few other files since they came up when I was trying to fix my own :-)
- updated `NEWS.md` (including suggested fixes to `NEWS.md`)
Sample code to validate non-breakage (i.e. test with various plot elements):
```
library(gridExtra)
st …
```
> Subtitles for ggplot2

- R/geom-boxplot.r
escape % symbol to avoid characters after be interpreted as comment
> trivial typo

- R/utilities-resolution.r
- man/resolution.Rd
This pull request fixes a minor typo I found in the documentation
> Typo in the documentation of resolution() function

- R/scale-gradient.r
corrected a typo in the manual for scale-gradient
> corrected typo -- missing parenthesis

- R/geom-histogram.r
- man/geom_histogram.Rd
Examples in `geom_histogram()` still use deprecated `origin`. This PR updates the document.
> Use "boundary" instead of deprecated "origin" in examples

- R/theme-defaults.r
- man/ggtheme.Rd
Small but clarifying change. I encountered a user who was confused why `p + theme_gray()` didn't update the plot when the examples were run in succession. 
I reordered examples so it does change the current plot. Also, commented that it is the default, in case the reader jumps right to the examples.
> docs: reorder theme_gray in examples so it's clear what it does

- R/theme.r
legend.key.size was marked as its own parent. fixed.
> corrected theme inhertiance for legend.key.size

- R/theme-defaults.r
According to an informal survey (@hrbrmstr @juliasilge), this margin is needed every time a plot.caption is used:
https://twitter.com/janschulz/status/727932334218039296
The chosen top margin is the same as for the subtitle, just on the top instead
of the bottom.
> Add top margin to default plot.caption

- R/scale-shape.r
- man/scale_shape.Rd
I often wind up hunting for the indices corresponding to different shapes, and it'd be nice if they were in the docs.
> Show a list of shapes in scale_shape docs

- R/annotation.r
- man/annotate.Rd
Adding two examples to the documentation of `annotate` about how to pass plotmath expressions.
1. simple plotmath expression
1. mixing plotmath syntax and plain text using `paste`
See #1548.
> Examples for plotmath expressions in `annotate`

- NEWS.md
- R/annotation-custom.r
- R/annotation-logticks.r
- R/annotation-map.r
- R/annotation-raster.r
- R/utilities.r
- tests/testthat/test-annotate.r
This fixes #1655 by adding dummy data to all annotate functions in the way already done for annotate_logticks.
> Fix annotate without global data

- NEWS.md
- R/position-collide.r
- R/position-stack.r
- man/position_stack.Rd
- tests/testthat/test-position-stack.R
This fixes #1552. `collide` now sorts the data by x and then by negated group. The negation is performed to ensure that the stacking order follows the default legend order of the fill.
> Sort within x prior to stacking

- NEWS.md
- R/plot-construction.r
- tests/testthat/test-add.R
This fixes a bug that is the root cause of rstudio/shiny#1178. When adding an `aes()` object to a `ggplot()` object, the `uneval` class is inadvertently dropped. For example:
```R
p <- ggplot(mtcars, aes(wt, mpg))
class(p$mapping)
p <- ggplot(mtcars) + aes(wt, mpg)
class(p$mapping)
```
This PR preserves the class of the object.
> Preserve class when adding uneval objects

- NEWS.md
- R/scale-.r
This change saves the palette and the number of breaks in it and retrieves these values on subsequent calls, avoiding multiple warnings pertaining to the palette. Fixes #1674
> Cache palette and n in ScaleDiscrete

- NEWS.md
- R/theme-defaults.r
- man/ggtheme.Rd
Make both the code and the visual aspect of all theme more homogeneous. The general idea was to take theme_grey as the reference for all changes (and since it changed slightly in the previous update of ggplot2, the other themes needed some love too!).
I tried to divide the PR in small standalone commits (too lazy for several pull requests ;-) ). I'll update them as needed so that the show PR can be merged. I also added the rationale for various choices as comments in the code.
Some fixes were clearly needed (default size, etc.). Visually, I think theme_bw in particular needed a review. For the others, the changes are quite subtle.
> Various fixes to themes

- NEWS.md
- R/margins.R
- R/theme-defaults.r
- tests/testthat/test-theme.r
And increase margins slightly. Fixes #1712 
@baptiste, @thomasp85, @jiho – can you please take a look? I always forget the consequences of tweaking theme defaults.
```R
df <- data.frame(x = 1:9, y = 1:9)
ggplot(df, aes(x, y)) + 
geom_point() + 
labs(
y = "yyy",
title = "This is title yyyyyy",
subtitle = "This is a subtitle yyyyyy"
)
```
Before: 
After: 
The difference is subtle, but an improvement.
> Add descenders to heights

- NEWS.md
- R/scale-.r
- tests/testthat/test-scales.r
This change will issue a warning if a transform results in the occurrence of new infinite values. Fixes #1696
> Check for occurence of infinite values

- R/scale-linetype.r
- man/scale_linetype.Rd
Show a simple legend for common line types. It just saves people a trip to the vignette or online docs.
Similar to PR https://github.com/hadley/ggplot2/pull/1578
> Show a list of linetypes in scale_linetype docs

- NEWS.md
- R/coord-map.r
- man/coord_map.Rd
I replaced the ... argument in coord_map() with parameters = NULL and added a new example in its help file for a projection that needs a 'parameters' argument. This fixes the bug mentioned in PR #1699.
In the previous version of coord_map(), the ... argument only served to pass the 'parameters' argument to mapproj::mapproject(), so it can be safely removed. I also added documentation about the new 'parameters' argument in coord_map().
P.S. I've now realized the proper workflow would have been to modify the original pull request at https://github.com/hadley/ggplot2/pull/1699 , but it's too late now.
> Add explicit 'parameters' arg to coord_map() in response to PR #1699

- R/scale-.r
- R/scale-continuous.r
- R/scale-date.r
- R/scale-discrete-.r
- R/scale-identity.r
- man/continuous_scale.Rd
- man/discrete_scale.Rd
Fixes #1732.
`continuous_scale` and `discrete_scale` now takes a `super` argument that defaults to `ScaleContinuous` and `ScaleDiscrete` respectively. This avoids having to reassign the super class after construction in the different positional scale constructors
> Pass super class to scale constructor

- R/scale-gradient.r
- man/scale_gradient.Rd
The documentation now mentions "continuous_scale" instead of "discrete_scale".
Fixes #1736.
> Scale gradient doc fix

- NEWS.md
- R/theme.r
- R/utilities.r
- man/theme.Rd
- tests/testthat/test-theme.r
- tests/testthat/test-utilities.r
> Remove ellipsis from theme

- NEWS.md
- R/stat-density.r
- man/geom_density.Rd
The argument controls the number of equally spaced points at which the density is to be estimated. As in `stats::density` the argument `n` defaults to 512. It is exposed through the function interface of `stat_density` and can thus also be used from `geom_density`.
An existent local variable `n`, which holds the number of values in the input vector, has been renamed to `nx` to avoid a name clash.
I needed this argument because plots created with `geom_density` contained a large number of points (1024?) per density curve. This resulted in large file sizes when saving the plot as a vector graphic. I think that it is generally useful to be able to control this parameter of the density function.
I rebuild the documentation, and tested the new functionality. However, I added a new argument to …
> Expose argument n from stats::density in the interface of stat_density.

- NEWS.md
- R/position-jitter.r
- R/position-jitterdodge.R
- R/stat-boxplot.r
The problem was the %||% operator accepts single tokens and so
care (bracketing as required) must be taken avoid miscalculations.
Some other places in the code-base had it right.
Fixes #1775
> Fix jitter width and jitter height

- NEWS.md
- R/stat-ydensity.r
- tests/testthat/test-geom-violin.R
> Expand ydensity range for nicer violin plots

- NEWS.md
- R/guide-colorbar.r
- R/guide-legend.r
- R/guides-.r
- tests/testthat/test-guides.R
> respect show.legend in colorbar

- R/facet-grid-.r
- R/facet-wrap.r
- R/labeller.r
> Fix stack and clipping in facets

- R/stat-ydensity.r
Fixes #1793
This PR changes the trim behaviour back to how it worked in v1.x.x
> Change meaning of trim in geom_violin

- R/coord-map.r
Fixes a bug in `CoordMap` that makes the x-axis ticks (but not title) appear on top of the graphic.
```{r}
df <- expand.grid(
lon = seq(-95.8, -94.9, .1),
lat = seq(29.4, 30.1, .1)
)
ggplot(df, aes(lon, lat)) +
geom_point()
```
```{r}
ggplot(df, aes(lon, lat)) +
geom_point() +
scale_x_continuous(position = "top")
```
```{r}
ggplot(df, aes(lon, lat)) +
geom_point() +
coord_map()
```
This commit (a minor two line swap) puts the ticks back on the bottom.
> coord_map: print x-axis ticks on bottom

- R/stat-bin.r
Fix minor typo in description of `boundary` argument and minor stylistic edit to include spaces around `=`.
> correction to stat_bin documentation

- README.Rmd
- README.md
When showing how to install ggplot2 package there is line 
> # Alternatively, install just readr
but should be 
> # Alternatively, install just ggplot2
> Change wrong package name in README file

- R/axis-secondary.R
- R/layout.R
Fixes #1877
This PR makes it possible to derive name of the primary scale even if the name is not specified in the scale constructor but either derived from the aesthetic or set through labs/xlab/ylab
> derive labels even if not specified in scale

- NEWS.md
- vignettes/releases/ggplot2-2.0.0.Rmd
This pull request changes two document files to match what is said in [`theme.r`](https://github.com/tidyverse/ggplot2/blob/master/R/theme.r#L330). I believe the warning message in the code is correct and the documents have a typo / thinko.
> Suspected typo / thinko: should use `axis.text` instead of `axis.ticks`.

- .travis.yml
This fixes issues when the Debian recommended packages lag behind the
CRAN versions
(https://github.com/travis-ci/travis-ci/issues/6850#issuecomment-264739865)
> Update packages before installation

- NEWS.md
- R/geom-errorbarh.r
Closes #1933 
`errorbar` is able to plot without putting a point at the midpoint of the error bar, but `errorbarh` was not able to.
An outstanding issue - It seems the `roxygen2`-generated documentation now does not pick up that `x` is an aesthetic that `geom_errorbarh` understands.
The result of this is that the user will need to use `geom_errorbarh` as well as `geom_point`.  I'm not sure how to fix this.
> Remove `x` as a required aesthetic for `geom_errorbarh`

- NEWS.md
- R/stat-smooth.r
Currently, `stat_smooth`'s "auto" method reports the function that it chooses, but not the formula. Since the formula depends on the function it chooses, reporting it seems like a good idea.
This is already in the docs, but putting it in the message will make it less likely for users to forget that they need to rewrite the formula (and tell their boss that the splines are just very close to being linear 😳).
> clarify geom_smooth auto message

- vignettes/extending-ggplot2.Rmd
In response to #1959.
I have added a note about renamed layer parameters as part of the question text in question 2 of section 1. This seemed logical as I encountered the issue when trying to solve this question. If there is a better place for the note, I can make the adjustment.
> ggproto vignette note about renamed layer parameters

- NEWS.md
- R/scale-.r
- man/continuous_scale.Rd
- man/discrete_scale.Rd
- man/scale_size.Rd
Updates `discrete_scale` documentation to match functionality and `continuous_scale` to make it clear the `labels` parameter can accept a formatter function as shown in the last example of `scale_x_discrete` (fixes #2052).
No code changes; just literally coped and pasted the documentation of the `labels` parameter from `continuous_scale`, called `devtools::document()`, and updated `NEWS.md` per `CONTRIBUTING.md` (delete that if it's too minor for news!).
> fix discrete_scale documentation

- NEWS.md
- R/ggproto.r
- R/plot-construction.r
In my experience, one of the most common and inscrutable error messages for new users is when they forget a `+` and get the error message: `non-numeric argument to binary operator`. For example, something like this:
```
> ggplot(mtcars, aes(x = disp, y = mpg))
> geom_point() + geom_smooth()
Error in geom_point() + geom_smooth() : 
non-numeric argument to binary operator
```
I would like to add a more informative error message in the style of #2056 and the error messages in **dplyr**, e.g. [this](https://github.com/hadley/dplyr/blob/0b9aabf6c06c9cd3b784b155044d497d4b93df3e/R/ts.R#L2).
```
> ggplot(mtcars, aes(x = disp, y = mpg))
> geom_point() + geom_smooth()
Error in `+.gg`(scale_fill_brewer(), geom_point()) : 
Cannot add ggproto objects together. Did you forget to add this object to a …
```
> Add error messages when using + with layers and scales

- NEWS.md
- R/stat-density.r
- tests/testthat/test-stat-density.R
Fixes #2127.
`compute_density()` now uses `stats::density()` to compute the density for two-element groups, resulting in plots that look like this (where group 5 has only two data points):
In the case where there is only a single point in the group (where it doesn't really make sense to calculate density), the group gets dropped with a warning.
```R
library("tidyverse")
set.seed(1958)
dat <- tibble(x = c(rnorm(n = 10, mean = 7, sd = 2),
rpois(n = 10, lambda = 2),
1, 9, 4),
group = c(rep(c("a", "b"), each = 10), "c", "c", "d"))
ggplot(dat, aes(x = x, fill = group)) +
geom_density(alpha = 0.5)
```
```
Warning message:
In compute_density(data$x, data$weight, from = range[1], to = range[2],  :
Groups with fewer than two data points have been dropped.
```
There is still a legend element for …
> Fix density calculations for groups with one or two elements

- R/fortify.r
- tests/testthat/test-fortify.r
The error message `"gglot2 doesn't know how to deal with data of class uneval"` is one of the more common ones that I see, and one that perplexes new users of ggplot2. I added a note about the most common reason for and fix of this error message.
If a `data` argument was omitted from `ggplot()`, the old behavior was
```
> ggplot(aes(x = x))
Error: ggplot2 doesn't know how to deal with data of class uneval
```
The new behavior is
```
> ggplot(aes(x = x))
Error: ggplot2 doesn't know how to deal with data of class uneval. Did you forget the data argument  in ggplot()?
```
> Add informative error message if user forgets data arg in ggplot()

- R/scale-.r
- man/discrete_scale.Rd
Fixes #2068. `discrete_scale` inherits params from `continuous_scale`, but the `breaks` and `limits` arguments behave differently for discrete vs. continuous scales. This adds new `breaks` and `limits` parameter documentation for `discrete_scale` that overrides the inherited parameter documentation.
> Update documentation of discrete_scale params that differ from continuous_scale

- R/scale-brewer.r
- man/scale_brewer.Rd
Fixes #2069. The inherited parameter documentation for brewer/distiller scales said that `...` arguments were passed to `discrete_scale`, which is true for the brewer scales but not for distiller scales (for distiller scales they go to `continuous_scale`).
> Note that scale_*_distiller passes ... args to continuous_scale, not discrete_scale

- NEWS.md
- R/theme-defaults.r
This is the continuation of #1883. Includes @baptiste's changes plus a line in `NEWS.md` about the change.
> Use rel() more consistently in theme elements, take two

- R/fortify-map.r
- R/ggproto.r
- R/scale-discrete-.r
- R/scale-gradient.r
- R/scale-grey.r
- R/scale-hue.r
- R/scale-linetype.r
- R/scale-manual.r
- R/scale-shape.r
- R/scale-size.r
- R/utilities-break.r
- man/as.list.ggproto.Rd
- man/borders.Rd
- man/cut_interval.Rd
- man/geom_histogram.Rd
- man/scale_discrete.Rd
- man/scale_gradient.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_linetype.Rd
- man/scale_manual.Rd
- man/scale_shape.Rd
- man/scale_size.Rd
See #2164
This uses `@inheritDotParams` for some `...` parameters. There are still some other places where we might be able to switch to `@inheritDotParams`. 
There's an issue when the dot parameters come from another package and include links. For example the `map_data` function passes `...` to `maps::map()`, but some of those params have links to other stuff within the maps package, and with `@inheritDotParams` the links get written to Rd as e.g. `\link{county}` when they need to be `\link[maps:county]{county}`
> Start using @inheritDotParams in documentation

- R/sf.R
- man/ggsf.Rd
see https://github.com/edzer/sfr/issues/396 for the motivating issue. This needs also https://github.com/edzer/sfr/commit/c9e56df2feebda344f9dcf07429a9711be026b66
> allow controlling ndiscr in call to sf::st_graticule

- R/geom-smooth.r
- R/stat-smooth.r
- man/geom_smooth.Rd
stat/geom_smooth lists 'rlm' as a possible method
for calulating a smooth, but method='rlm' fails
becuase rlm() is in MASS and is not imported. This
fixes this by importing MASS::rlm.
> Clarify stat/geom_smooth docs to show method takes a fn, not a character

- NEWS.md
- R/theme-defaults.r
- man/ggtheme.Rd
- tests/figs/themes/theme-bw-large.svg
- tests/figs/themes/theme-classic-large.svg
- tests/figs/themes/theme-dark-large.svg
- tests/figs/themes/theme-gray-large.svg
- tests/figs/themes/theme-light-large.svg
- tests/figs/themes/theme-linedraw-large.svg
- tests/figs/themes/theme-minimal-large.svg
- tests/figs/themes/theme-void-large.svg
- tests/testthat/test-theme.r
Closes #2176. These optional parameters control the default sizes of line and rectangle elements and are set to `base_size / 22` by default. As requested [here](https://github.com/tidyverse/ggplot2/pull/2174#issuecomment-309593094) I've added new tests at `base_size = 33`.
> Add base_line_size and base_rect_size parameters to theme defaults

- R/geom-text.r
Add note to documentation explaining differing behaviour of geom_text, and annotate(geom = "text").
> Add note recommending annotate

- vignettes/extending-ggplot2.Rmd
> [Minor] typo in extending-ggplot2 vignette

- R/stat-density.r
I found a small typo in R/stat-density.r, exampe -> example
> [Minor] fixing typo, exampe -> example

- tests/testthat/test-function-args.r
Fixes #2208 
Updates compute function name and surrounding comments/text that used to talk about the draw function (from the test above this one).
> Fixes test suite warnings from missing 

- R/margins.R
Currently `titleGrob()`'s `debug = TRUE` argument has no effect when `expand_x` and `expand_y` are both `FALSE` because the function returns output before the debugging conditional is reached. This fixes the issue by moving the debugging conditional up and ensuring that all of the `children` are returned.
Previous behavior:
```r
df <- data.frame(x = 1:10, y = 1:10, color = LETTERS[1:2])
p <- ggplot(df, aes(x, y, color = color)) +
geom_point() +
theme(
legend.title = element_text(debug = TRUE),
legend.text = element_text(debug = TRUE)
)
p # note no debugging output
```
After this PR:
```r
p
```
We could also address #1881 here by using `text_height` and `text_width` instead of `unit(1, "grobheight", text_grob)` and `unit(1, "grobwidth", text_grob)` for the widths and heights. This puts …
> Make `debug = TRUE` work when `expand_x` and `expand_y` are FALSE

- NEWS.md
- R/coord-transform.r
- tests/testthat/test-coord-transform.R
`coord_trans()` now generates a warning when a transformation results in x or y values being non-finite (#2147).
I've used `#` comments for the internal helper function so it doesn't generate MD documentation files, but not sure what the ggplot2 style is for those functions.
The logic and the message is based on the [transform in the Scale object](https://github.com/tidyverse/ggplot2/blob/4255cd8341ad1072036186e5d34ad2c1b12221b3/R/scale-.r#L207) in order to be consistent.
> Add warning for coord_trans() when resulting x/y value becomes non-finite (#2147)

- NEWS.md
- R/position-dodge2.r
- man/position_dodge.Rd
Fixes #2171 
``` r
ggplot(mtcars, aes(factor(cyl), fill = factor(vs))) +
geom_bar(position = "dodge2") 
```
``` r
ggplot(mtcars, aes(factor(cyl), fill = factor(vs))) +
geom_bar(position = position_dodge2(reverse = TRUE)) 
```
> Add `reverse` argument to `position_dodge2()`

- NEWS.md
- R/save.r
- man/ggsave.Rd
- tests/testthat/test-ggsave.R
Add feature request #2156. 
3 new string options for `ggsave()`: "screen" (72 DPI), "print" (300 DPI), and "retina" (320 DPI).
One question was what DPI the "retina" option should be. As mentioned in the issue, it's not so straightforward to pick a single DPI number. The standard for retina is to double the DPI, but from what baseline DPI?
There is no such thing as a baseline DPI for Apple because they define their `@1x` baseline, non-retina template using pixel dimensions (which all designs should be based on and then scaled for output). Retina output is `@2x` and sometimes `@3x` for the newer phones. For their phones, [this roughly corresponds to ~160 DPI](http://sebastien-gabriel.com/designers-guide-to-dpi/#ios), and ~130 DPI for their tablets. For Android, the baseline MDPI …
> Add string options for `ggsave()` (#2156)

- NEWS.md
- R/labeller.r
- R/margins.R
Here are some improvements to `titleGrob()` and related functions that we talked about:
I still need to figure out how to prevent rotated text from extending outside of the strip in facet labels.
``` r
x = 1:2,
y = 1:2,
z = c("a", "aaaaaaabc")
)
geom_point() +
facet_wrap(~ z) +
theme(strip.text.x = element_text(hjust = 0, vjust = 1, angle = 45, debug = TRUE))
```
> Further refactor titleGrob

- NEWS.md
- R/theme-defaults.r
- tests/figs/themes/theme-void-large.svg
Recent changes to text placement make it possible for strips to have margins around all sides. This adds margins around all sides of strips. Default plots where the strip labels are centered will look the same, but this fully fixes #1887 because the margins are defined in `strip.text` instead of `strip.text.x` and `strip.text.y`.
In some cases where text is rotated, this also prevents the edges of the text from being cut off the strip.
``` r
x = 1,
y = 1,
z = c("aaaaaaabc")
)
facet_wrap( ~ z) +
theme(strip.text = element_text(angle = 45, hjust = 0, vjust = 0, debug = TRUE))
```
Margins will need to manually be set to 0 if users want to fully justify text with the edges of the strips.
This change added a little extra space above and below the strip …
> Add margins on all sides of strips by default

- R/guide-legend.r
When I was looking into how to add margins around legend elements I noticed that the legends code  doesn't follow tidyverse style. This just fixes the style in `guide-legend.r`.
> Adhere to tidyverse style in guide-legend.r

- NEWS.md
- R/geom-defaults.r
Fixes #2299.
Fix `update_geom_defaults()` and `update_stat_defaults()` to allow American spelling of aesthetic parameters
> Fix `update_geom_defaults()` and `update_stat_defaults()`

- R/scale-.r
- man/continuous_scale.Rd
- man/discrete_scale.Rd
- man/scale_continuous.Rd
- man/scale_date.Rd
- man/scale_discrete.Rd
- man/scale_gradient.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_linetype.Rd
- man/scale_manual.Rd
- man/scale_shape.Rd
- man/scale_size.Rd
This corrects the documentation issue raised in #2296.
> Correct documentation for default name parameter in scales.

- R/position-stack.r
`reverse` is misspelled as `reveres` in the documentation.
> Fix typo in position_stack documentation

- R/layer.r
The check for null was occurring on the wrong variable: 'name' cannot be
null, but 'obj' can. Moreover the message should report the variable as
set by the end user (such as 'identity'), rather than the internal name
constructed by the function (such as 'StatIdentity').
> Improve error message from find_subclass() (#2065).

- NEWS.md
- R/bin.R
At some point during a refactoring, `ndensity` was changed from `density/max(density)` to `count/max(density)` -- I believe by mistake.  This changes it back.  See issue [#2324](https://github.com/tidyverse/ggplot2/issues/2324) for details.
> Restored correct scaling for `ndensity` when binning (#2324)

- NEWS.md
- R/scale-.r
- tests/testthat/test-scale-gradient.R
Fixes #2230. 
Limits are now imposed before rescaling so points outside the limits don't reappear.
> Fix limits on `scale_colour_gradient2()` 

- NEWS.md
- R/guide-colorbar.r
Previously it showed an approximation where the colours
at the scale limits were not guaranteed to be included.
``` r
ggplot(faithful, aes(x = eruptions, y = waiting)) +
geom_point()  +
stat_density_2d(aes(fill=..level..), geom='polygon') +
xlim(0.5, 6) +
ylim(40, 110) +
scale_fill_viridis_c() +
guides(fill=guide_colorbar(nbin=7))
```
*Before*
fixes #2343
> Fix colorbar to show all colors of the scale

- NEWS.md
- R/stat-bin.r
- R/stat-bin2d.r
- tests/testthat/test-stat-bin.R
- tests/testthat/test-stat-bin2d.R
The issue only was only about `stat_bin_2d`, but `stat_bin`
suffered the same slight.
Fixes #2366
> Fix breaks for bin & bin2d stats for trans scales

- R/labeller.r
- tests/figs/facet-strips/switched-facet-strips.svg
- tests/testthat/test-facet-strips.r
Fixes #2356. The [titleGrob() refactor](https://github.com/tidyverse/ggplot2/pull/2232/) caused a bug where strip labels on the left side weren't rotated properly. This fixes it by extracting the creation of the text grobs into a separate function (`create_strip_labels()`) that can be called after the angle has been adjusted.
> Fix angle of switched y strips

- R/guide-colorbar.r
This pull request fixes #2260 for continuous color scales. #2260 has been previously fixed for discrete color scales, but it still exists for continuous ones:
```
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Petal.Width)) + 
geom_point() +
theme(legend.spacing.y = grid::unit(0.5, "cm"))
```
> fix #2260 for continuous color scales

- NEWS.md
- R/zzz.r
- tests/testthat/test-zzz.R
This avoids confusion when calling `set.seed()` before attaching
ggplot2.
> Reset the random stream after running .onAttach

- NEWS
- NEWS.md
- R/facet-.r
- R/facet-grid-.r
- R/facet-null.r
- R/facet-wrap.r
- R/labeller.r
- R/layout.R
- R/plot-build.r
- man/as_labeller.Rd
- man/combine_vars.Rd
- man/facet_grid.Rd
- man/facet_null.Rd
- man/facet_wrap.Rd
- man/gg-add.Rd
- man/is.facet.Rd
- man/labellers.Rd
- vignettes/extending-ggplot2.Rmd
- vignettes/releases/ggplot2-2.0.0.Rmd
- vignettes/releases/ggplot2-2.2.0.Rmd
Change documentation and comments to standardise the spelling of 'faceting'. Both spellings ('faceting' and 'facetting') were previously in use. OED and https://en.oxforddictionaries.com/definition/faceting give the usual spelling as ‘faceting’.
Updated `man` directory using roxygen2
> Standardise spelling: ‘faceting’ instead of ‘facetting’

- tests/testthat/test-fortify.r
f61bfd620037b7e1c816129469b106443651a4dc updated the error message but not the test that expects the old message.
> Fix expected error message for fortify.default with class uneval

- NEWS.md
- R/position-jitterdodge.R
- man/position_jitterdodge.Rd
In pull #1996 position_jitter got a new argument called seed.
position_jitterdodge might also benefit from having a seed.
Below, I show an example of `position_jitterdodge` before and after my changes.
Please notice two things:
1. After my changes, the text labels are correctly centered on the points.
2. The x-axis gains 2 tick marks at 5 and 7.
- This was unexpected, and I don't know why it happened or if it matters much. It's easy to fix by doing `dat$cyl <- factor(dat$cyl)`.
Here's the code:
```r
dat <- mtcars
dat$name <- rownames(mtcars)
dat$name[dat$cyl != 6] <- ""
set.seed(1)
pos <- position_jitterdodge(seed = 1)
ggplot(dat, aes(cyl, mpg, color = name != "", label = name)) +
geom_point(
size = 0.5,
position = pos
) +
geom_text(
size = 2,
position = pos
) …
```
> add seed argument to position_jitterdodge

- R/geom-boxplot.r
- R/position-dodge2.r
- tests/testthat/test-position-dodge2.R
Closes #2290 by setting the default `preserve` argument in `position_dodge2()` to `"total"`. 
Before: 
``` r
ggplot(mtcars, aes(x = factor(vs), y = mpg)) +
facet_wrap( ~ factor(cyl)) +
geom_boxplot()
```
After:
``` r
ggplot(mtcars, aes(x = factor(vs), y = mpg)) +
facet_wrap( ~ factor(cyl)) +
geom_boxplot()
```
> Make position_dodge2 preserve total width by default

- R/position-dodge2.r
- man/position_dodge.Rd
#2386 made `preserve = "total"` the default for `PositionDodge2`, but didn't swap the order of the defaults in `position_dodge2()`. This fixes it.
> Swap order of preserve arguments in position_dodge2()

- vignettes/extending-ggplot2.Rmd
`facet_trans` has parameter `horizontal`. When set to `FALSE`, 
```r
ggplot(mtcars, aes(x = hp, y = mpg)) + geom_point() + facet_trans('sqrt', horizontal = FALSE)
```
gives
```
Error in gtable::gtable_add_grob(panel_table, rep(axes$y$right, length(panel_pos_v)),  : 
Not all inputs have either length 1 or same length same as 'grobs' 
```
Old:  
```r
for (i in rev(seq_along(panel_pos_h))) {
panel_table <- gtable::gtable_add_cols(panel_table, axis_width_r[i], panel_pos_h[i])
if (params$horizontal) {
panel_table <- gtable::gtable_add_grob(panel_table, 
rep(axes$y$right[i], length(panel_pos_v)), t = panel_pos_v, l = panel_pos_h[i] + 1, 
clip = "off")
} else {
panel_table <- gtable::gtable_add_grob(panel_table, 
rep(axes$y$right, length(panel_pos_v)), t = panel_pos_v, l = panel_pos_h[i] + 1, …
```
> Fix facet_trans() in Vignette: Extending ggplot2

- NEWS.md
- R/geom-label.R
I have tried to implement the fix suggested by Winston in the comments on this issue.
> remove unwanted annotation border from saved PDFs; closes #2407

- NEWS.md
- R/guide-colorbar.r
- man/guide_colourbar.Rd
- tests/figs/guides/white-to-red-gradient-colorbar-thick-black-tick-marks-green-frame.svg
- tests/figs/guides/white-to-red-gradient-colorbar-white-tick-marks-no-frame.svg
- tests/testthat/test-guides.R
Inspired by StackOverflow questions [here](https://stackoverflow.com/q/29793398/4975218) and [here:](https://stackoverflow.com/q/50070741/4975218) This patch enables better styling of the colorbar guide.
Examples:
```{r}
set.seed(123)
df <- data.frame(x <- rnorm(10),
y <- rnorm(10),
fill <- rnorm(10))
p <- ggplot(df, aes(x, y, fill = fill)) + geom_point()
p + scale_fill_gradient(low = 'white', high = 'red')
```
```{r}
p + scale_fill_gradient(low = 'white', high = 'red',
guide = guide_colorbar(frame.colour = "black"))
```
```{r}
p + scale_fill_gradient(low = 'white', high = 'red',
guide = guide_colorbar(ticks.colour = "black"))
```
```{r}
p + scale_fill_gradient(low = 'white', high = 'red',
guide = guide_colorbar(frame.colour = "black",
frame.linewidth = 1,
ticks.colour = "black", …
```
> Enable more styling options for guide_colorbar().

- NEWS.md
- R/theme-elements.r
This closes #2544.
```{r}
library(ggplot2)                                                                                                                                                       
ggplot(iris, aes(x = Sepal.Length, y = Petal.Length, color = Species)) +                                                                                               
geom_point() +                                                                                                                                                         
scale_color_discrete(guide = guide_legend(label.theme = element_text(face = "italic")))                                                                                
```
```{r}
ggplot(iris, aes(x = Sepal.Length, y = Petal.Length, color = Species)) + …
```
> Fix missing default setting for angles in element_grob.element_text(). Closes #2544.

- R/geom-abline.r
- R/geom-boxplot.r
- R/geom-contour.r
- R/geom-crossbar.r
- R/geom-curve.r
- R/geom-density.r
- R/geom-density2d.r
- R/geom-dotplot.r
- R/geom-errorbar.r
- R/geom-errorbarh.r
- R/geom-hex.r
- R/geom-hline.r
- R/geom-label.R
- R/geom-linerange.r
- R/geom-path.r
- R/geom-point.r
- R/geom-pointrange.r
- R/geom-polygon.r
- R/geom-raster.r
- R/geom-rect.r
- R/geom-ribbon.r
- R/geom-rug.r
- R/geom-segment.r
- R/geom-text.r
- R/geom-tile.r
- R/geom-violin.r
- R/geom-vline.r
- R/sf.R
Fix #2558
This PR changes all the default values for the alpha aesthetic to 1 in the cases where it is currently set to `NA`. Any colour are currently passed through `scales::alpha()` if it should be modified with transparency and this function treats `NA` as 1, so there should be no practical effect of this change.
> Change all default_aes alpha from NA to 1

- .travis.yml
- DESCRIPTION
- tests/testthat/helper-vdiffr.R
- On Travis add R 3.1 now that tidyr/tidyselect are fixed on 3.1
- On Appveyor use `ggplot_build()` instead of vdiffr until the latter is fixed on Windows platforms
> Fix CI builds

- NEWS.md
- R/plot-build.r
- R/theme-defaults.r
- R/theme-elements.r
- R/theme.r
- man/theme.Rd
- tests/figs/labels/defaults.svg
- tests/figs/labels/manual.svg
- tests/figs/labels/other-position.svg
- tests/testthat/test-labels.r
As per discussions on twitter, this PR adds a `tag` label alongside `title`, `subtitle`, and `caption`. It is placed in the upper left corner in its own row and column between the margin and the title/x-label.
The tag name is chosen over `label` as the `labs()` function indicate that “label” is a catchall term for all types of titles.
The default theming is like this:
```r
ggplot(mtcars) +
geom_point(aes(disp, mpg)) + 
labs(tag = 'A', title = 'test')
```
The size is slightly larger than the title and the margin is chosen so that it is well separated from the main parts of the plot. In general this is based on my own taste and is up for discussion.
> Add tag label for adding identifier to plot

- NEWS.md
- R/plot.r
- R/position-dodge2.r
- R/utilities.r
- man/ggplot2-package.Rd
- tests/testthat/test-position-dodge2.R
Fixes #2563
@karawoo can you please take a look at this one too - I'm going to refactor `position_dodge2()` shortly as I think I see a way to make the code cleaner.
> Single element panels still need to be resized

- NEWS.md
- R/geom-smooth.r
- tests/figs/geom-smooth/ribbon-turned-off-in-geom-smooth.svg
- tests/figs/geom-smooth/ribbon-turned-on-in-geom-smooth.svg
- tests/testthat/test-function-args.r
- tests/testthat/test-geom-smooth.R
I think the way to fix this issue is to give `geom_smooth()` a first-class `se` parameter that is considered when drawing the panel. This allows the geom and the legend drawing code to always be in synch. See resulting behavior in the examples below.
One note: Currently one regression test fails because the `geom_smooth()` and `draw_group()` functions have different default arguments and the test checks for that. I think the test is wrong in this particular case, but I wanted to bring this up for discussion. Relevant lines in the code, with explanation for why it should be this way:
https://github.com/clauswilke/ggplot2/blob/ed016144c97cf67424498453a2f4e06925fdba92/R/geom-smooth.r#L119-L126
Examples of `geom_smooth()` with `stat_summary()`:
``` r
ggplot(mtcars, aes(cyl, …
```
> Fix issue 1546, fill aesthetic does not show in the legend guide for stat_summary

- R/position-dodge.r
- R/position-dodge2.r
- tests/testthat/test-position-dodge2.R
Fixes #2493 
@karawoo can you please double check my logic? I think this makes sense as we should only be considering the maximum number of overlapping groups within a panel.
> Compute overlapping groups by panel

- R/guide-colorbar.r
- R/guide-legend.r
- R/margins.R
- R/plot-build.r
- tests/figs/coord-polar/secondary-axis-ticks-and-labels.svg
- tests/figs/facetting/left-justified-facet-labels-with-margins.svg
- tests/figs/geom-dotplot/facets-3-groups-histodot-stackgroups.svg
- tests/figs/guides/facet-grid-legend-on-bottom.svg
- tests/figs/guides/facet-grid-legend-on-left.svg
- tests/figs/guides/facet-grid-legend-on-right.svg
- tests/figs/guides/facet-grid-legend-on-top.svg
- tests/figs/guides/rotated-guide-titles-and-labels.svg
- tests/figs/themes/axes-styling.svg
- tests/figs/themes/height-is-3-times-width-2-row-facets.svg
- tests/figs/themes/height-is-3-times-width-2x2-facets.svg
- tests/figs/themes/strip-styling.svg
- tests/testthat/test-guides.R
Correct text justification works now for rotated text. Do you want me to add a visual test for this?
``` r
df <- reshape2::melt(outer(1:4, 1:4), varnames = c("X1", "X2"))
p1 <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
p1 + scale_fill_continuous(
breaks = c(5, 10, 15),
labels = paste("long", c(5, 10, 15)),
guide = guide_legend(
direction = "horizontal",
title.position = "top",
label.position = "bottom",
label.theme = element_text(angle = 90, hjust = 1, vjust = 0.5)
)
)
```
Created on 2018-05-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
> Close issues #2573 & #2576

- NEWS.md
Reverse inadvertent deletion of 'not' in 'aesthetics that are not length one'
Apologies for the typo!
> Update NEWS.md with correct description of #1932

- R/coord-.r
- R/coord-cartesian-.r
- R/coord-fixed.r
- R/coord-transform.r
- R/facet-.r
- R/facet-grid-.r
- R/facet-wrap.r
- man/ggplot2-ggproto.Rd
Fixes #2594
I’ve added coord_transform to support free scales as I think it simply has been left out in an error. If that is wrong I’ll change it back
> Let Coord objects indicate if they support free scales

- NEWS.md
Improvements to breaking changes
> Breaking changes

- R/aes.r
- R/guide-legend.r
- R/labeller.r
current:
```r
aes(short = 1, veryveryverylong = 2)
```
PR
```r
aes(short = 1, veryveryverylong = 2)
```
The back ticks should not contain the white space around the variable names.  This change keeps the spacing, just moves the back ticks to be directly around the name.
> Aes format ticks are not formatted properly

- R/scale-type.R
- R/scales-.r
- tests/testthat/test-scale-type.R
Fixes #2599
@karawoo any ideas why this behaviour changed?
> Ensure that we don't try and assign scale to NULL

- R/facet-wrap.r
Fix #2622
This PR fixes a bug in facet_wrap that would throw an error during certain axis and strip settings
> Correct result length in vapply

- NEWS.md
- R/geom-.r
- R/layer.r
- R/utilities.r
- tests/testthat/test-layer.r
Fixes #2609 
Tested on a couple of packages that failed the revdepchecks.
> Allow column vector inputs

- R/plot-construction.r
- tests/testthat/test-error.R
The behavior in the dev version is much better than in the CRAN version, but I think we can be even clearer here.
``` r
+ geom_point()
#> Error: There's nothing on the left-hand side of `+`. Did you forget to add this object to a ggplot object?
```
> Created on 2018-05-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
``` r
+ geom_point()
#> Error: Cannot add ggproto objects together. Did you forget to add this object to a ggplot object?
```
> Created on 2018-05-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
> Better error message when using +.gg() as unary operator

- NEWS.md
The error message is now "`coord_*` doesn't support free scales".
``` r
df <- data.frame(x = c(1, 2))
ggplot(df, aes(x, x)) + facet_wrap(~x, scales = "free") + coord_fixed()
#> Error: coord_fixed doesn't support free scales
```
> Minor fix in NEWS.md: update error message for unsupported free scales

- R/labels.r
- man/labs.Rd
`tag` argument seems not documented in `?labs` yet. Since `tag` is intended to be specified by `labs()`, I think this should be described here.
> Add documentation about `labs(tag = )`

- R/quick-plot.r
This closes issue #2671.
I think it's sufficient to treat everything as a parameter that is not in the complete list of aesthetics. This is a heuristic that is not guaranteed to be always right, but it is going to be mostly right. And in any case, it's the heuristic that was used prior to 2.3.0.
> In qplot, don't require I() for parameters. Closes #2671

- R/geom-boxplot.r
- R/geom-point.r
- man/geom_boxplot.Rd
Since there are already at least 4-5 different ways of hiding  outliers, I don't see the need to add a new parameter to the API. Instead, I think updating the documentation is sufficient. I didn't list `outlier.size = -1`, because that option is only guaranteed to work if the stroke value hasn't been modified.
I also fixed the problem where `geom_point()` was trying to match an empty string against the shape names.
> issue #2505, hiding boxplot outliers

- revdep/README.md
- revdep/problems.md
`data.sqlite` is at https://www.dropbox.com/s/xv1hxct2446a9vs/ggplot2_data.sqlite.zip?dl=0
We checked 2105 reverse dependencies (1715 from CRAN + 390 from BioConductor), comparing R CMD check results across CRAN and dev versions of this package.
* We saw 101 new problems
* We failed to check 63 packages
> revdeps for 2.2.1 vs 2.2.1.9000

- R/scale-viridis.r
- man/scale_viridis.Rd
Since viridis is already the default colour scale for ordered factors, these first two examples in http://ggplot2.tidyverse.org/reference/scale_viridis.html#examples make no differences.
``` r
dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
(d <- ggplot(dsamp, aes(carat, price)) +
geom_point(aes(colour = clarity)))
```
``` r
d + scale_colour_viridis_d()
```
Maybe it is proper to use some other data that has factor or character columns, but using `diamond` seems the widespread manner among examples of `scale_colour_*()`. So, I choose converting `clarity` column.
> Do not use ordered factor for viridis example

- .github/lock.yml
* Fixes #2713
* Stop lockbot from marking issues as resolved.
* See https://github.com/dessant/lock-threads/issues/7 re. new `setLockReason` param.
* Add lockComment explaining why issue locked.
> Update lockbot reason 🔒🤖

- R/geom-bar.r
- R/geom-col.r
- tests/testthat/test-geom-bar.R
- tests/testthat/test-geom-col.R
Define non_missing_aes for GeomCol and GeomBar. Closes #2715.
> Define non_missing_aes for GeomCol and GeomBar. Closes #2715.

- DESCRIPTION
- R/aaa-.r
- R/aes.r
- R/ggplot-global.R
- R/quick-plot.r
- R/stat-sum.r
- R/theme-current.R
- R/theme-elements.r
- R/theme.r
- tests/testthat/test-guides.R
This is the first step towards user-defined theme elements as discussed in #2540. This particular PR doesn't add any features yet, it just reorganizes the code so that global variables live in an environment. It could be merged as is, but mostly I'd want quick feedback to make sure I'm on the right track.
> User-defined theme elements

- R/theme-defaults.r
Update the example used in the "complete themes" help page (`ggtheme`). I extended the current `mtcars` example to use more (all?) of the features which themes affect: title, subtitle, tag, caption, and both x- and y-facets.
There are now two plot examples. One with no facets, and one with 2x2 facets. The latter is enclosed in `\donttest{}` to keep R CMD check from complaining about the runtime.
The `mtcars` dataset may not be the best for this, but I wanted to keep it close to the orginal example, and the data isn't as important in this example.
> New examples for theme_*()

- NEWS.md
- R/geom-density2d.r
- R/stat-bin2d.r
- R/stat-binhex.r
- R/stat-contour.r
- R/stat-density-2d.r
- R/stat-density.r
- man/geom_bin2d.Rd
- man/geom_contour.Rd
- man/geom_density.Rd
- man/geom_density_2d.Rd
- man/geom_hex.Rd
- man/ggtheme.Rd
- man/scale_viridis.Rd
- tests/testthat/test-stat-density.R
I added 'scaled' statistics to the `stat_bin2d`, `stat_binhex`, ` stat_density_2d`, and  `stat_contour` functions for plotting 2d distributions normalized to a common height. This would be very useful for faceted 2d plots, where the maximum density/count can vary greatly between panels. 
(This is my attempt to add the feature I had requested in issue #2679.)
---
I tried my best to mirror the corresponding statistics from the 1d functions:
stat_bin | stat_bin2d | stat_binhex |  stat_bin2d (updated) | stat_binhex (updated) 
--- | --- | --- | ---| ---
`count `| `count` | `count` | `count` | `count` 
`ncount` | | | `ncount` | `ncount`
`density`|  `density` | `density` | `density` | `density`
`ndensity`|   | | `ndensity` | `ndensity`
It was a little bit harder to get things to match-up …
> Scaled densities/counts in 2d density/bins plots (#2679)

- R/guide-colorbar.r
> Fix partial argument match in guide_train.colorbar

- R/geom-text.r
- man/geom_text.Rd
Specify non-support of '`angle` aesthetic' rather than '`rot` parameter', as this is clearer.
It is indeed the case that the `angle` aesthetic isn't supported. You can see below that `geom_text` is rotated but `geom_label` isn't, despite the same aesthetics. Perhaps it's worth adding a warning if you try to use the `angle` aesthetic with `geom_label`, although I'm less sure how you'd go about this.
Do I need to render the file for the `man/` directory?
``` r
library(tidyverse)
#> Warning: package 'dplyr' was built under R version 3.5.1
data <- tibble(
text = c('one', 'two', 'three'),
angle = c(0, 45, 90),
x = c(1, 2, 3)
)
ggplot(data, aes(x)) +
geom_text(aes(y = 2, label = text, angle = angle)) +
geom_label(aes(y = 1, label = text, angle = angle))
```
Created on 2018-07-27 by the [reprex …
> Clarify geom_label documentation

- NEWS.md
- R/axis-secondary.R
- tests/testthat/test-sec-axis.R
This PR make a small change to the evaluation of the transform formula of secondary axes to support plots created with tidy evaluation when calling `sec_axis()`. Fixes #2788. 
This PR solves the original issue, and does not break any other secondary axis transformations, but if there is a better way to implement this or something this might break downstream that I'm not seeing, please advise.
> Fix sec.axis() when used with tidyeval (#2788)

- NEWS.md
- R/axis-secondary.R
- tests/testthat/test-sec-axis.R
This PR simplifies the creation of secondary axes to use the transformation of the primary axis when setting breaks and labels rather than relying on an identity transform in all cases. This is a fix for #2729 which was caused by the identity trans calling `extended_breaks()` by default while the breaks on the primary axis were created by `log_breaks()` as is default for log-transformed axes. 
@thomasp85 As I mentioned this morning, my original fix just used a simple conditional to force log transformed axes to use `log_breaks()` but after you mentioned the identity trans this morning I decided to take another look at setting the new scale's `trans` argument by the primary transformation.  Ultimately this solves the problem at its source, and is a much more general fix. For instance, …
> Simplify sec.axis for proper transformed breaks

- R/axis-secondary.R
- tests/testthat/test-sec-axis.R
PR #2095 changed the order in which the range a secondary axis was transformed, sampled, and tested for monotonicity. Sampling over the transformed space rather than the original scale caused the monotonicity test on the secondary axis to fail for certain transformations. This PR fixes those failures by sampling on the original scale rather than the transformed scale, effectively a partial reversal of PR #2095 whose motivating problem was fixed in an alternative way by #2796.
> Fix incorrect monotonicity test failure in sec.axis

- R/axis-secondary.R
- tests/testthat/test-sec-axis.R
This PR adds the calling environment to the transformation evaluation in the secondary axis. This closes #2835.
> Add evaluating environment to tidy eval call. Closes #2835

- R/scale-.r
- man/continuous_scale.Rd
- man/discrete_scale.Rd
- man/scale_discrete.Rd
- man/scale_gradient.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_linetype.Rd
- man/scale_manual.Rd
- man/scale_shape.Rd
The 'palette' parameter has different usage in continuous
vs discrete scales, and the documentation described the
discrete usage.
> Fix #2839: 'continuous_scale' palette param docs

- NEWS.md
- R/sf.R
This closes #2826, allowing `lineend`, `linejoin`, and `linemitre` arguments to be passed through `geom_sf`. I copied the defaults directly from `geom_path`, so this shouldn't alter the results of current code.
The only change I had to make beyond what Claus mentioned on the issue was assigning the parameters to `coord` so they get passed through to `sf_grob`. There may be a simpler way to structure that. If so, let me know and I'll refactor.
For now, I decided against adding them as explicit parameters to `geom_sf`, as while it would make sense for lines, it would sound like they'd apply to polygons, too, which they wouldn't, and thus may cause more confusion than it'd remove.
This builds and performs fine. I didn't add any tests, as the `geom_sf` tests don't currently test its line …
> allow geom_sf to accept line parameters (#2826)

- NEWS.md
- R/geom-.r
Found when looking at #2850. The error message in `compute_aesthetics()` should show the names of aesthetics with mismatched lengths, but as written it showed the names of all aesthetics.
> Only print the names of the aesthetics with mismatched length

- NEWS.md
- R/sf.R
This PR closes #2857. It enables most ways in which axis tick labels can normally be set for `coord_sf()`. The main limitation is that it can only accept character vectors. Parsed expressions will not work. (However, strings that contain the degree symbol will automatically be parsed into expressions.)
``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.3, proj.4 4.9.3
library(ggplot2) 
nc <- st_read(system.file("gpkg/nc.gpkg", package="sf"))
#> Reading layer `nc.gpkg' from data source `/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sf/gpkg/nc.gpkg' using driver `GPKG'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg …
```
> Enable manual setting of axis tick labels with coord_sf. Closes #2857

- .travis.yml
- tests/figs/annotate/line-matches-points.svg
- tests/testthat/helper-vdiffr.R
As discussed under #2842. I have purposefully committed a breaking visual test, so if everything is right with this initial PR then the release build will fail and all others will succeed.
> Improved vdiffr setup

- R/geom-path.r
- man/geom_path.Rd
Minor document fix. This closes #2877.
`geom_path()` (and its family functions) handles `NA` in this manner:
* If `NA` is at the middle of the line, it breaks the line and doesn't show any warnings (so, `na.rm` doesn't matter here)
* If `NA` is at the start or the end of the line and `na.rm` is `FALSE` (default), it removes the `NA` with a warning.
* If `NA` is at the start or the end of the line and `na.rm` is `TRUE`, it silently removes the `NA`.
This PR is intended to improve the document of `geom_path()` to illustrate this behaviour well.
> Improve document about handling of NA in geom_path()

- R/save.r
- R/scale-manual.r
- R/scale-size.r
- R/stat-summary-bin.R
The reprex below triggered the investigation that led to possible instances where "brittle closures" are returned. I have no idea if the other instances I found have an effect, but it feels like good practice to force arguments that are used by closures.
Happy to add tests as necessary.
``` r
library(tidyverse)
scale <- c("red", "green", "blue")
p <-
ggplot(iris, aes(Petal.Length, Petal.Width, color = Species)) +
geom_point() +
scale_color_manual(values = unlist(scale), labels = levels(iris$Species))
scale <- scale[-1]
p
```
> Created on 2018-08-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
> Force arguments that are used in closures

- R/geom-jitter.r
- R/geom-label.R
- R/geom-text.r
- R/sf.R
This is suggested in https://github.com/tidyverse/ggplot2/pull/2761#discussion_r211114877.
The current error messages are like:
> Specify either `position` or `nudge_x`/`nudge_y`
@clauswilke's suggestion is:
> `position` and `width`/`height` cannot both be specified. Please specify only one
I feel the latter follows [the tidyverse style](http://style.tidyverse.org/error-messages.html) of error messages; it consists of "problem statement" + "hint".
> Improve error messages about conflicted parameters

- R/ggplot-global.R
- R/sf.R
- R/theme-elements.r
This PR keeps the currently released ggtern working with ggplot2.
> Minor fixes to keep compatibility with ggtern

- NEWS.md
I have taken a first stab at NEWS.md.
@hadley According to the [style guide](http://style.tidyverse.org/news.html#before-release), package authors should not be listed for items they wrote. Do you want me to remove @clauswilke and @karawoo from all 3.1.0 news items? (I think no other contributors are official authors.)
> fix up NEWS.md for release

- NEWS.md
- R/sf.R
- man/ggsf.Rd
This PR closes #2938.
Example:
``` r
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
p <- ggplot(nc) +
geom_sf(aes(fill = AREA)) +
geom_text(x = -80, y = 37, label = "label outside limits", inherit.aes = FALSE)
p
```
``` r
p + coord_sf(clip = "off")
```
<sup>Created on 2018-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> Make clipping configurable in coord_sf().

- .travis.yml
Fixes #2956 
This PR provides two workarounds:
1. Install dev version of `vdiffr` only when `USE_VDIFFR=true` since vdiffr now requires R >= 3.2.0, which means builds with R 3.1 fails.
2. Use `R_REMOTES_NO_ERRORS_FROM_WARNINGS=true` to avoid errors converted from warnings raised by `devtools::install_deps()`, which didn't seem to exist before devtools 2.0.
> Fix Travis failures

- CONTRIBUTING.md
- R/plot-build.r
Minor edits to the `CONTRIBUTING.md` file:
1. Typo in motivate
2. Cleaned up bulleted-list
3. Define `PR` & format the paragraph
> Documentation:  contributing.md

- .github/CODE_OF_CONDUCT.md
- GOVERNANCE.md
I've removed some duplication, and attempted to refine the description of the different categories of community member. I've also moved away from the "benevolent dictator" language in favour of "project lead".
What other important parts of the ggplot2 governance process have I forgotten?
> Broad review of governance structure

- R/guide-legend.r
For after the 3.1.0 release: This small change enables legend drawing for scales that take lists of complex objects.
Example:
``` r
library(ggtextures)
library(magick)
#> Linking to ImageMagick 6.9.9.39
#> Enabled features: cairo, fontconfig, freetype, lcms, pango, rsvg, webp
#> Disabled features: fftw, ghostscript, x11
images <- list(
giraffe = image_read_svg("http://steveharoz.com/research/isotype/icons/giraffe.svg"),
elephant = image_read_svg("http://steveharoz.com/research/isotype/icons/elephant.svg"),
horse = image_read_svg("http://steveharoz.com/research/isotype/icons/horse.svg")
)
data <- data.frame(
count = c(5, 3, 6),
animal = c("giraffe", "elephant", "horse")
)
ggplot(data, aes(animal, count, image = animal)) +
geom_isotype_col() +
scale_image_manual(values = …
```
> enable legend drawing for list data columns

- NEWS.md
- R/geom-rug.r
- tests/testthat/test-geom-rug.R
The rugs in `geom_rug` are drawn along an axis depending the
`sides` parameter. Since the coordinate system does not alter
the `geom` parameters, the `geom` has to alter any parameters
that determine where the geoms are plotted.
fixes #2987 
----
``` r
df <- data.frame(x = 1:10, y = (1:10)^3)
g <- ggplot(df, aes(x, y)) + geom_point() + geom_rug(sides = 'l')
g
```
``` r
g + coord_flip()
```
<sup>Created on 2018-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> Fix geom_rug + coord_flip

- NEWS.md
- R/layer.r
- tests/testthat/test-layer.r
It's common practice to wrap unsafe calculations with `tryCatch()` and return `NULL`, which allows us to use the result when available and skip when unavailable. But, currently, ggplot2 doesn't accept this in `aes()`:
``` r
df <- data.frame(x = 1:10, y = 1:10)
wrap <- function(...) tryCatch(..., error = function(e) NULL)
ggplot(df, aes(x, y, colour = wrap(no_such_column))) +
geom_point()
#> Error: Aesthetics must be either length 1 or the same as the data (10): colour
```
This is because `Layer$compute_aesthetics()` removes `NULL` aes here BEFORE evaluation:
https://github.com/tidyverse/ggplot2/blob/f5a88a71e7b60b6531ef6c4a936370b5e3c4ef92/R/layer.r#L221-L223
Considering the following facts, I think it's safe to move `compact()` after evaluation
- `ggplot2::compact()` …
> Allow using functions that return NULL in aes()

- DESCRIPTION
To fix this NOTE:
```
* checking DESCRIPTION meta-information ... NOTE
Package listed in more than one of Depends, Imports, Suggests, Enhances:
‘grDevices’
A package should be listed in only one of these fields.
```
https://travis-ci.org/tidyverse/ggplot2/jobs/455860461#L2326
> Remove duplicated grDevices in Imports

- NEWS.md
- R/geom-ribbon.r
This PR streamlines the handling of data in line-like gloms where an implicit sorting of data along the x-axis is happening. Previously GeomLine had the sorting happening in `setup_data` while GeomRibbon (and by extension GeomArea) had it inside `draw_group`.
The motivation is that it solves some issues in gganimate that couldn't be fixed outside of ggplot2, but I also think that conceptually this is the right approach, and we should be consistent in how we treat data operations across kindred geoms/stats
> Sort ribbon/area in setup_data

- R/position-nudge.R
- tests/testthat/test-position-nudge.R
Fix spurious warning in `position_nudge()`, as described in #2977.
``` r
x = c(1,3,2,5),
y = c("a","c","d","c")
)
geom_point() +
geom_text(aes(label = y), nudge_y = c(-0.1, 0.1, -0.1, -0.1))
```
<sup>Created on 2018-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> fix nudging with multiple values. closes #2977

- _pkgdown.yml
Per https://github.com/tidyverse/ggplot2/issues/2890#issuecomment-445902471, adding link to the post for ggplot2 3.1.0 to News section of the pkgdown site.
@hadley, I didn't run `build_site()`, since I'm not yet clear on how the automated pkgdown build is handling this. 😬
> Add 3.1.0 post link to pkgdown News

- R/utilities.r
- man/expand_scale.Rd
For so so long, I've been wondering why `devtools::document()` fails on my Windows if I don't change my locale to `C`:
```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))
Updating ggplot2 documentation
Writing NAMESPACE
Loading ggplot2
Writing aes_group_order.Rd
Error in gsub("\n", "\r\n", contents, fixed = TRUE) : 
input string 1 is invalid in this locale
Calls: suppressPackageStartupMessages ... roclet_output.roclet_rd -> mapply -> <Anonymous> -> same_contents -> gsub
Execution halted
Exited with status 1.
```
But, at last, I found the cause! Let's say goodbye to LEFT SINGLE QUOTATION MARK (U+2018) and RIGHT SINGLE QUOTATION MARK (U+2019).
> Remove smart quotes

- inst/CITATION
Closes #3071 
citation url is now the current ggplot2 webpage.
> Correct url link in citation

- NEWS.md
- R/plot-build.r
- man/ggplot_build.Rd
Closes #2818.
This PR adds documentation for the `i` and `j` arguments in `layer_scales`, `layer_data`, and `layer_grob`.
> add i and j args documention to layer_* functions

- NEWS.md
- R/scale-identity.r
Closes #3029
This PR fixes an issue where `scale_shape_identity` was producing an error with `guide = "legend"`
``` r
df2 <- data.frame(x = 1:5 , y = 1:10, z = 1:10)
s <- ggplot(df2, aes(x = x, y = y))
s + 
geom_point(aes(shape = z), size = 4) + 
scale_shape_identity(guide = 'legend')
```
<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> fix typo in scale_shape_identity

- R/facet-.r
- R/facet-wrap.r
- R/grob-dotstack.r
- R/theme.r
- man/borders.Rd
- man/map_data.Rd
- man/max_height.Rd
This PR addresses several small problems with how ggplot2 treats units that have come up during my rewrite of the unit object. They all centre around the assumptions that units are a numeric vector with attributes, which are only true for freshly created unit objects.
These changes makes ggplot2 work with the new unit spec without breaking backward compatibility with old grid versions.
> Fix unit-to-numeric coercion assumptions

- R/layout.R
Fixes #3099 
Make scale_id a factor before splitting to make sure all levels are part of the output despite not being part of the data
> ensure scale_index matches the number of scales in length

- NEWS.md
- R/coord-sf.R
- tests/figs/coord-sf/no-panel-grid.svg
- tests/testthat/test-coord_sf.R
This PR makes `coord_sf()` behave more similarly to `coord_cartesian()` when drawing the panel grid, by applying the same line-width correction and by respecting `element_blank()`. Closes #2991 and #2525.
Reprex 1:
``` r
df <- data.frame(x = c(1, 2, 3), y = c(1, 2, 3))
p <- ggplot(df, aes(x, y)) + geom_point()
cowplot::plot_grid(
p + coord_fixed() + theme(panel.grid.minor = element_blank()) +
ggtitle("coord_fixed()"),
p + coord_sf() +
ggtitle("coord_sf()")
)
```
``` r
cowplot::plot_grid(
p + coord_fixed() + theme_bw() + theme(panel.grid.minor = element_blank()) +
ggtitle("coord_fixed()"),
p + coord_sf() + theme_bw() + 
ggtitle("coord_sf()")
)
```
``` r
cowplot::plot_grid(
p + coord_fixed() + theme(panel.grid = element_blank()) +
ggtitle("coord_fixed()"),
p + coord_sf() + …
```
> Better respect theme settings when drawing coord_sf() panel grid

- NEWS.md
- R/geom-polygon.r
- R/ggplot-global.R
- man/borders.Rd
- man/geom_map.Rd
- man/geom_polygon.Rd
This PR adds the ability to draw polygons with holes to `geom_polygon`. It does so by adding a new, optional, aesthetic called `subgroup`. If provided, and R >= 3.6 the geom will use the new improved pathGrob to draw the polygons.
Questions to mull over:
- Do you agree on the `subgroup` name. I've elected for a generic name so it can be reused elsewhere if secondary grouping is needed, rather than using something that signifies the "hole"-ness of it
- Currently the geom will draw the path using the "evenodd" rule as this is how most people will probably think it works (winding order is quite specialised knowledge). It could be made a parameter of the geom, but isn't currently as I think it would just muddy the waters
Example:
```r
ids <- factor(c("1.1", "2.1", "1.2", "2.2", "1.3", "2.3")) …
```
> Holed polygons

- R/scale-identity.r
This PR closes #3127 by adding a proper check for the presence or absence of a guide in the identity scales.
``` r
devtools::load_all("~/github/ggplot2")
d <- base::data.frame(
week = seq(1, 52, 1), 
revenue = round(runif(52, 0, 100))
)
ggplot(data = d, aes(x = week, y = revenue, fill = 'lightskyblue')) + 
geom_col() + 
scale_fill_identity(guide = guide_legend())
```
``` r
ggplot(data = d, aes(x = week, y = 1, size = revenue/20)) + 
geom_point() + 
scale_size_identity(guide = guide_legend())
```
<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> Remove warning when guide functions are used in identity scales

- README.Rmd
- README.md
The second edition of the The R Graphics Cookbook has been released, but the READMEs links to the first edition. This pull request should fix this and remove the text stating that a new version is due in 2018.
I have no experience with the amzn.to URL shortener so the link is the full URL obtained by following the current link and then the link to the updated version.
> Update READMEs to reflect 2nd edition cookbook

- NEWS.md
- R/fortify-map.r
- R/stat-quantile.r
- R/utilities.r
- man/geom_quantile.Rd
This is work in progress, as discussed in #3126. There are a few cases where we attach external packages. Ideally, we would never attach external packages.
> Don't attach external packages

- R/backports.R
- R/guide-colorbar.r
- R/guide-legend.r
- R/guides-.r
- R/position-stack.r
- R/scale-.r
- R/utilities.r
It seems the failure on r-devel is related to `R_CHECK_LENGTH_1_LOGIC2`, an option to raise error when multiple logicals are passed to `||` or `&&`.
```
--- failure: length > 1 in coercion to logical ---
```
I'm not sure the next version of R will be released with this strict behaviour, but it's a nice chance to fix inappropriate if conditions.
> Fix Travis failures on r-devel

- NEWS.md
- R/scale-continuous.r
This PR extends the recognised positional aesthetics to include `x0` and `y0`. This is needed for a range of geoms/stats in ggforce to make sure they play nice with scale transformations. `x0` and `y0` are traditionally used to denote center values and a natural fit for many parametrised geometries...
Such a change has happened before in c9f276b60c so it should be fairly safe
> Extend the range of recognised positional aesthetics

- DESCRIPTION
- R/coord-sf.R
- R/geom-sf.R
This PR adapts `geom_sf` and `coord_sf` to make use of the improvements in performance introduced in sf v0.7-3. The changes are as follows:
- Use `st_normalize` during rescaling to greatly speed up `coord_sf
- Construct a single grob from the geometry and let `sf` decide on how/if to split it up to multiple grobs
This PR introduces a new version dependency on sf as it does not make much sense to support both implementations simultaneously
> Better sf support

- R/margins.R
I've uncovered another "bad" assumption in ggplot2's handling of units. The margin constructor will drop any unit subclasses when subclassing the unit it creates. This PR fixes it and makes it work with the experimental unit implementation in https://github.com/thomasp85/grid/pull/1 in a back-compatible way
> prevent margin from changing the unit class when subclassing

- .travis.yml
(See https://github.com/tidyverse/ggplot2/pull/3177#issuecomment-470349699)
R-devel introduced a check for future file timestamps. The check tries to verify the system click is correct by accessing world clock API, but it seems not stable enough to rely on. This PR avoid the check by setting `_R_CHECK_SYSTEM_CLOCK_` to false.
Not sure we'll need this also on the release version of R, but for now let's set only on r-devel.
> Do not check the system clock on r-devel

- R/facet-grid-.r
- R/ggplot2.r
Though `quos()` are imported in `utilities-tidy-eval.R`, I think it's good practice to stick with the fully qualified forms in package code (I'm tolerant for test code). There are a few places that lacks `rlang::`, so this PR added them.
In addition, I want to remove this line to make it clear that we don't encourange the unqualified forms of `quo()` and `quos()`. I guess this was added by mistake.
https://github.com/tidyverse/ggplot2/blob/033fb521a084447c15178c591ab96a158f3b1e1e/R/ggplot2.r#L6
> Use the fully qualified forms for quos()

- NEWS.md
- R/scale-type.R
- tests/testthat/test-scale-type.R
- tests/testthat/test-scales.r
Fix #3184 
In ggplot2, `Inf` might mean continuous value or discrete value. But, currently, the plot fails in the following case
* the first layer's data is all `Inf`
* the second layer's data is discrete
It seems better to skip picking a scale for the layer that has only infinite values. Note that, if all layers are such ones, the plot fails no matter we ignore them or not, because we cannot get a range for plots. So, I think this change is fine.
> Skip picking a scale when the layer data is Inf

- NEWS.md
This PR polishes the NEWS file in preparation for the 3.2 release (#3207)
> polish news

- R/position-.r
The function signature is `compute_panel(self, data, params, scales) -> data`
> Fix Position docs

- R/margins.R
reverse dependency check catched an instance of an extension storing multiple font settings in a title element, which broke the `font_descent()` assumption about only being provided a single setting to calculate descent on. This PR vectorises the function and mitigate the revdep break
> vectorise the font_descent function to allow multiple input

- NEWS.md
- R/utilities-break.r
- man/cut_interval.Rd
This fixes #3055 
I added also a small example but not test as there were none for `cut_*` functions. 
Tell me if you need some.
> Add ... to cut width to pass to cut.default

- NEWS.md
- R/guides-axis.r
Fixes #2983
Prior to this, `guide_axis()` would return a `zeroGrob` when no break position where provided. This meant that axis lines were not drawn in these situations. This fix changes the behaviour so that axis lines always will be drawn (if allowed by the theme)
@hadley I've asked you to review as the old behaviour may have been deliberate
> Draw axis line when length(breaks) == 0

- R/summarise-plot.R
- _pkgdown.yml
- man/summarise_plot.Rd
Fixes #3219
* Add missing topics (c.f. https://travis-ci.org/tidyverse/ggplot2/jobs/512667960#L2175)
* `expand_scale`
* `stat`
* `stat_sf_coordinates`
* `vars`
* Mark `summarise_plot` as internal
> Fix missing references on the pkgdown site

- R/stat-contour.r
- man/geom_contour.Rd
Fixes #3095
This adds the stat aesthetics to the documentation of contour thus properly showing the required `z` aesthetic... I don't really like the look of stacking calls to `rd_aesthetics()` but this is what we got right now...
> Add stat aesthetics to contour docs

- R/guides-.r
Fixes #2914 
This PR makes adding an empty `guides()` a no-op (from the outside look)
> Avoid indexing error when adding an empty guides() specification

- R/geom-raster.r
Fixes #2932
This adds a warning when `geom_raster()` can't truthfully represent the provided data. To avoid recompilation the call to `resolution()` has been changed to direct calculation.
@batpigandme can you have a look at the wording of the warning?
> Add warning when raster data doesn't fall on an even grid

- NEWS.md
- R/geom-violin.r
Fixes #2885 
In certain instances quantiles will have `NA` coordinates and the computed aesthetics will not match the number of lines to draw, leading to grid errors
> Fix grid errors when quantiles falls outside of violin

- NEWS.md
- R/guide-colorbar.r
- R/guide-legend.r
This is a minimal fix for #2943. It guarantees that plot legends look fine when `legend.title = element_blank()`, but otherwise doesn't change the appearance of the legend. In the future, this should be refactored, because the same variables control the overall spacing between the legend title and the legend keys and the spacing between individual legend items. There should be two separate variables for that.
``` r
df <- reshape2::melt(outer(1:4, 1:4), varnames = c("X1", "X2"))
p1 <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
p1 + scale_fill_continuous(guide = guide_legend())
```
``` r
p1 + scale_fill_continuous(guide = guide_legend()) +
theme(legend.title=element_blank())
```
``` r
p1
```
``` r
p1 + theme(legend.title=element_blank())
```
<sup>Created on …
> fix bad default for legend spacing variables. closes #2943.

- R/grob-null.r
- R/theme-current.R
- R/zzz.r
Fixes #3233
Two instances were observed and moved too `.onLoad()` after going through the full source code
> Move build-time calculations to .onLoad()

- R/geom-ribbon.r
reverse dependency check picked up an issue with the new sorting of `geom_ribbon()` in `setup_data()`. When `ymin` is set outside `aes()` it would fail as it wouldn't have access to the variable at setup time. This PR mitigates that.
> fix problems during ribbon data sort

- tests/figs/scale-date/dates-along-x-default-breaks.svg
- tests/figs/scale-date/dates-along-y-default-breaks.svg
- tests/figs/scale-date/scale-x-date-breaks-3-weeks.svg
- tests/figs/scale-date/scale-x-date-breaks-date-breaks-2-weeks.svg
- tests/figs/scale-date/scale-x-date-labels-date-format-m-d.svg
- tests/figs/scale-date/scale-x-date-labels-date-format-w-week.svg
- tests/figs/scale-date/scale-y-date-breaks-3-weeks.svg
- tests/figs/scale-date/scale-y-date-breaks-date-breaks-2-weeks.svg
Fixes #3279
The new random number generator introduced in R 3.6 caused failure in the visual tests that applied sampling to build up the dataset. This PR updates the reference images to match the output on 3.6
> update visual tests for the new rng in 3.6

- NEWS.md
- R/coord-polar.r
Fixes #3185 
This PR adds correct scaling of the secondary axis when used with `CoordPolar()` as proposed by @linzi-sg
> Rescale sec.axis correctly for CoordPolar

- R/geom-boxplot.r
- tests/testthat/test-geom-boxplot.R
This is a PR to fix #3316, where group data with more than 1 row in `GeomBoxplot$draw_layer()` was causing an error that was difficult to diagnose. This may occur when using `geom_boxplot(stat = "identity")`, and is likely to occur if a user wants to draw several boxplots at specific locations on a plot in a boxplot/scatter mashup situation.
```r
ggplot(
data.frame(x = "one value", y = 3, value = 4:6),
aes(x, ymin = 0, lower = 1, middle = y, upper = value, ymax = 10)
) + 
geom_boxplot(stat = "identity", position = "identity")
#> Error: Elements must equal the number of rows or 1
```
> Better error message when geom_boxplot() gets group data with more than 1 row 

- R/stat-smooth.r
- man/geom_smooth.Rd
```
> "lm" %in% ls("package:base")
[1] FALSE
> "loess" %in% ls("package:base")
[1] FALSE
> "lm" %in% ls("package:stats")
[1] TRUE
> "loess" %in% ls("package:stats")
[1] TRUE
```
> prefix lm() and loess() with stats:: instead of base::

- NEWS.md
I added a paragraph about visual changes to the release notes, as discussed in #3304.
@hadley @batpigandme Could you review? I wasn't entirely sure where to place the paragraph, but I feel it should be up on top so people see it even if they don't read through the entire set of notes.
> Improved release notes

- R/zzz.r
This is a PR to fix #3313, where packages that subclass `GeomPolygon` were giving install warnings with the new version of ggplot2 in the revdep checks (#3303).
I was hesitant to prepare this PR, because I don't understand why this works, and because I can't replicate the install warning that occurred in the revdep checks, I can't verify that this PR fixes the problem. I can verify that it doesn't cause any CMD check failures for either ggplot2 or ggspatial, which was one of the packages affected by the revdep check issue.
> Dynamically assign pathGrob in .onLoad()

- R/annotation.r
- R/performance.R
- tests/testthat/test-performance.R
This fixes #3317, and likely some other current issues.
``` r
ggplot() +
annotate("point", x = numeric(0), y = numeric(0), colour = "red")
```
<sup>Created on 2019-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
> Allow empty annotations.

- .travis.yml
- DESCRIPTION
- NEWS.md
Required for #3308.
I also added the missing R versions to the Travis files. Please let me know if you prefer to leave (some of) them out.
> Drop support for R 3.1

- tests/testthat/test-facet-map.r
In previous versions of ggplot2, it was possible to facet by a date variable. This was temporarily broken (#3313) and will be fixed by #3327. It should always be possible to use `facet_wrap()` and `facet_grid()` with date variables, and as @yutannihilation pointed out, there is no test to enforce this behaviour. This PR adds such a test (there are already similar tests in `tests/testthat/test-facet-map.r`). This test currently fails as #3327 isn't merged.
> Tests to make sure facet_wrap() and facet_grid() can facet by date

- CONTRIBUTING.md
Moving the CODE_OF_CONDUCT.md document to the main directory (https://github.com/tidyverse/ggplot2/pull/2973) has broken the link to it within the CONTRIBUTING.md document.
This PR fixes an identical issue to one of the commits in https://github.com/tidyverse/ggplot2/pull/2973 (https://github.com/tidyverse/ggplot2/pull/2973/commits/027a0ddc28f58685ecffa5464999d46b04308737) which fixed a broken link in the GOVERNANCE.md document.
> Fix a broken link to CODE_OF_CONDUCT.md

- NEWS.md
- R/geom-abline.r
- R/geom-hline.r
- R/geom-vline.r
- tests/testthat/test-geom-hline-vline-abline.R
This is a pull request to address #3090, and in part overwrites the work from #2950. This PR ensures that:
- An informative warning is issued when `mapping` and one or more of `yintercept`/`xintercept`/`slope`/`intercept` are provided. 
- An informative warning is issued when `data` and one or more of `yintercept`/`xintercept`/`slope`/`intercept` are provided. 
It is also worth noting that I changed the test for "data is provided" from `missing(data)` to `is.null(data)`. I am not sure if there was a good reason for it to have been `missing(data)` in the first place, as something like
```r
data <- NULL
geom_hline(yintercept = 3, data = data)
```
would possibly not issue a warning.
I may have gone overboard on the gramatically-correct informative warning message function …
> redo warnings for overwritten arguments in abline, hline, and vline

- R/coord-.r
- R/coord-map.r
- R/coord-polar.r
- R/coord-sf.R
- R/guides-axis.r
- R/theme.r
- tests/testthat/test-theme.r
This is a PR to prepare for improvements in axis guides as part of #3322. This PR  renames the internal function `guide_axis()` to `draw_axis()` and includes a complete rewrite of (what is now) `draw_axis()`.
Renaming `guide_axis()` to `draw_axis()` is necessary to make way for an exported `guide_axis()` function that returns a guide (instead of a grob). I used the term "draw" because it is used in many places in ggplot2 for functions that return grobs.
The rewrite of `draw_axis()` is necessary because the current code is difficult to read and contains much duplication. This makes it difficult to change or improve, as is planned for #3322. The rewrite does not introduce any visual changes in the current tests, and I didn't add any new tests because I couldn't find any part of axis …
> Rewrite guide_axis() and rename to draw_axis()

- R/facet-.r
- tests/testthat/test-facet-.r
This PR fixes #2810, which describes the unusual failure of `facet_wrap()` when used with layers containing different numbers of facet variables.
``` r
df_all_vars <- expand.grid(letter = c("a", "b"), number = c(1, 2), x = 1, y = 1)
df_some_vars <- data.frame(letter = c("a", "b"), x = 2, y = 2)
ggplot() +
geom_point(aes(x, y), data = df_all_vars) +
geom_point(aes(x, y), data = df_some_vars) +
facet_wrap(vars(letter, number))
#> Error in gList(structure(list(x = structure(0.5, class = "unit", valid.unit = 0L, unit = "npc"), : only 'grobs' allowed in "gList"
```
This took a very long time to track down. In the end, `FacetWrap$compute_layout()` was generating a layout with 12 rows, when there are only four panels computed by `FacetWrap$map_data()`. This resulted in some …
> Fix behaviour of combine_vars() with more than one facet variable

- R/guides-axis.r
The latest update of the `draw_axis()` code (#3375) broke the ability of `element_text()` subclasses to be rendered as axis labels. This PR fixes this, such that any S3 element inheriting from `element_text()` is rendered correctly. This is important for gridtext integration, which uses `element_text()` subclasses extensively (#3373). An excellent reprex for this is available here: https://github.com/clauswilke/gridtext/blob/master/examples/ggplot2-integration.R
> Ensure that draw_axis() works with element_text() subclasses

- tests/testthat/test-coord_sf.R
After r-spatial/sf#1083 (which addressed #3365), several expectations in the `coord_sf()` test suite will fail with the next version of sf. This PR splits the affected test into several, small, well-labeled tests, and updates the expectations such that they will pass with the new version of sf (and the current version). This PR fixes #3365.
> Update sf graticule label tests that will fail when the next sf version is released

- R/save.r
- man/ggsave.Rd
Closes #3295 
Added clarification that path is a path to a directory, and that filename is appended to path to create the fully qualified file name
> Clarified difference between filename and path arguments in `ggsave()`

- R/scale-brewer.r
- man/scale_brewer.Rd
Fixes #3300.
This pull request addresses the first bullet point of #3300. Davis is not sure if we should do anything for the second bullet point.
> Cross-linked the palette argument with the Palette section

- R/scale-.r
- man/continuous_scale.Rd
- man/geom_ribbon.Rd
- man/scale_continuous.Rd
- man/scale_date.Rd
- man/scale_gradient.Rd
- man/scale_size.Rd
Fixes #2887 
Added an explicit warning in scales documentation about limits sometimes removing data.
> Explicit warning about data removal with limits on positional scales

- R/limits.r
- R/utilities.r
- man/gg_dep.Rd
- man/lims.Rd
These are a few typo fixes from the last few PRs that might cause automatic checks to fail.
> Fix typos that were causing the CMD check not to pass

- R/geom-point.r
- R/stat-function.r
- man/stat_function.Rd
- tests/testthat/test-stats-function.r
> Improved stat_function() documentation #3362

- R/scale-gradient.r
- man/scale_gradient.Rd
Addresses #3299 
Added examples to illustrate the different behaviour when setting `na.value = NA` when used with the fill and colour aesthetics, and data has missing values.
The second suggested bullet point of #3299 is dependent on a bug fix and hence I did not document this.
> Improve documentation for `scale_*_gradient`

- R/geom-histogram.r
- R/stat-bin.r
- man/geom_histogram.Rd
- man/stat_summary.Rd
- Details about modifing binwidths and center/boundary
- Removed repeated word from stat-bin documentation
Closes #3269
> Improving documentation for geom_histogram().

- R/position-dodge.r
- R/scale-continuous.r
- man/position_dodge.Rd
- man/scale_continuous.Rd
- man/scale_date.Rd
issue #2767 
Added some information about position_dodge2()
> Issue 2767

- .travis.yml
Using declarative installation of `apt` packages will result in better caching. Also `sudo` is deprecated and `dist: trusty` is EOL soon, it's better to use the default linux distribution.
> Cleanup Travis config

- R/position-stack.r
- tests/testthat/test-position-stack.R
fixes #3390 
@karawoo I have checked that this fix does not cause regressions in #1552. Basically what this does is avoid positive and negative y-values to get reordered, not fiddle with the group-based reordering
> Do not change order of positive and negative values in PositionStack

- R/quick-plot.r
Closes #3467.
In #2936, I added `.ignore_empty = "all"` to `rlang::enquos()` in `aes()` and in `qplot()` to remove missing `x` and `y` automatically. But, as `qplot()` generates labels directly from the input, missingness should be kept there. This PR reverts #2936's changes about `qplot()`.
``` r
set.seed(2009)
x <- rnorm(100)
qplot(x, geom = "histogram")
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```
<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Keep missingness of qplot() to label axis nicely

- R/theme-defaults.r
- man/ggtheme.Rd
"line drawings" into "line drawing".
> Fix typo in ggtheme docs

- NEWS.md
- R/geom-sf.R
- tests/testthat/test-geom-sf.R
Fix #3483
Currently, `GeomSf` doesn't have `non_missing_aes`, but it should be set to avoid errors reported on #3483. I chose `shape`, `size` and `colour` here because
* As `GeomSf` is a mix of points, lines, and polygons, it should use the combination of `non_missing_aes` of `GeomPoint`, `GeomLine` and `GeomPolygon`.
* `GeomPoint` uses `shape`, `size` and `colour`
* `GeomLine` and `GeomPolygon` don't have their `non_missing_aes`.
* For lines and polygons, `GeomSf` removes rows (e.g. the size is `NA`) that `GeomLine` and `GeomPolygon` won't. But, the result is the same; lines and polygons whose sizes are all `NA` won't be drawn. So, I think it's no problem to remove the whole rows.
``` r
devtools::load_all("~/repo/R/ggplot2")
pts <- sf::st_sf(
geometry = …
```
> Let geom_sf() remove rows when shape, size or colour is NA

- R/facet-.r
Closes #3489 (I think it should be fixed on tibble's side, though)
As we saw #3048, using tibble internally causes unexpected errors because the existing codes expects a bare data.frame. I think #3489 is just a bug on tibble's side, but, I believe it's better for ggplot2 internals to stick with a bare data.frame for consistency.
Note that this pull request leaves these two `tibble()` uses as is because they don't seem the cases when the result is used internally.
https://github.com/tidyverse/ggplot2/blob/b8420241309c8eea00d7086002c01cdf38a50eac/R/summarise-plot.R#L66-L70
https://github.com/tidyverse/ggplot2/blob/b8420241309c8eea00d7086002c01cdf38a50eac/R/summarise-plot.R#L134-L136
> Force eval_facets() to return a data.frame, not a tibble

- R/scale-discrete-.r
- tests/testthat/test-scale-discrete.R
Fix #3463
After #3426, the following fails because `scale$get_limits()` returns `NULL`. This PR fixes this by reverting `if` branches to the previous code while the functional limits are still accepted.
``` r
df <- data.frame(x = c(0, 2, 4), y = 1:3, stringsAsFactors = FALSE)
geom_point() +
scale_x_discrete()
#> Warning in structure(in_domain, pos = match(in_domain, breaks)): Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
#>   Consider 'structure(list(), *)' instead.
#> Warning in structure(in_domain, pos = match(in_domain, breaks)): Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
#>   Consider 'structure(list(), *)' instead.
#> Error in UseMethod("rescale"): no applicable method for …
```
> Fix the discrete scale when all values are continuous

- NEWS.md
- R/geom-.r
- R/layer.r
For unknown reasons `Geom` and subclasses doesn't have a `setup_params()` method. It may have not been needed before, but for consistency this PR add's it and calls it right before `setup_data()`
This will make certain parts of #3506 look better/more consistent
> Add setup_params method to Geom

- R/data.R
- man/diamonds.Rd
- man/economics.Rd
- man/faithfuld.Rd
- man/midwest.Rd
- man/mpg.Rd
- man/msleep.Rd
- man/presidential.Rd
- man/txhousing.Rd
Minor updates to some of the help files for datasets in the package.
The only "correction" is the number of rows in the economics dataset.
> Minor updates to data docs

- R/stat-.r
Fix #3548 
The old call to `remove_missing()` in `Stat$compute_layer()` did not factor in the new `x|y` notation allowed in `Stat$required_aes` for bidirectional layers. This caused missing data to not be removed correctly. This PR fixes the problem
> Fix remove_missing() call in Stat$compute_layer()

- R/stat-boxplot.r
- tests/testthat/test-stat-boxplot.R
Per @clauswilke's [comment on #3548](https://github.com/tidyverse/ggplot2/issues/3548#issuecomment-538767599).
> Use na.rm parameter in StatBoxplot

- R/position-stack.r
- R/utilities.r
revdepchecks have uncovered a few bugs in the sniffing that has been fixed here
> Various fixes to orientation sniffing

- R/theme.r
- tests/testthat/test-theme.r
This closes #3549.
``` r
element_dummyrect <- function(dummy) {
structure(list(
fill = NULL, colour = NULL, dummy = dummy, size = NULL,
linetype = NULL, inherit.blank = FALSE
), class = c("element_dummyrect", "element_rect", "element"))
}
ggplot2:::calc_element(
"panel.background",
theme(
rect = element_rect(fill = "white", colour = "black", size = 0.5, linetype = 1),
panel.background = element_dummyrect(dummy = 5))
)
#> List of 6
#>  $ fill         : chr "white"
#>  $ colour       : chr "black"
#>  $ dummy        : num 5
#>  $ size         : num 0.5
#>  $ linetype     : num 1
#>  $ inherit.blank: logi FALSE
#>  - attr(*, "class")= chr [1:3] "element_dummyrect" "element_rect" "element"
```
<sup>Created on 2019-10-04 by the [reprex package](https://reprex.tidyverse.org) …
> Enable inheritance for derived theme elements

- NEWS.md
- R/plot-construction.r
- R/theme-current.R
- R/theme.r
- R/zzz.r
- tests/testthat/test-theme.r
Here is an attempt at fixing #3039. Recall: That issue shows that adding theme elements piecewise behaves differently from adding them all at once. The problem is that when adding a theme to a plot object, the current implementation pulls missing info from the default theme, but this is not the case when adding a theme to a theme. In my mind, this behavior is inconsistent. The addition should behave the same in both cases. The solution is to delete the plot-specific update function.
This is the reprex from #3039, which now works just fine:
``` r
p <- ggplot(mtcars, aes(wt, mpg)) + geom_point()
p1 <- p + theme_light() + 
theme(axis.line.x = element_line(color = "blue")) +
theme(axis.ticks.x = element_line(color = "red"))
p2 <- p + theme_light() +
theme(axis.line.x = …
```
> Clean up theme addition

- R/aes-calculated.r
Fix #3552
Currently, `strip_dots()` and `is_calculated()` treat a quosure as a call, and it surprisingly works for now, but it's fragile. A quosure should be treated as a quosure...
> Handle a quosure properly in strip_dots() and is_calculated()

- R/plot-construction.r
- R/theme.r
I made a few improvements to the error messages when plot addition fails, based on recommendations in the tidyverse style guide and also based on feedback from this Twitter thread: https://twitter.com/ClausWilke/status/1189725947508989953?s=20
``` r
ggplot() + 1
#> Error: Can't add `1` to a ggplot object.
ggplot() + geom_point
#> Error: Can't add `geom_point` to a ggplot object.
#> Did you forget to add parentheses, as in `geom_point()`?
```
<sup>Created on 2019-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Improved error messages for plot addition.

- R/guide-bins.R
Fix #3582
The result of `do.call("cbind", lapply(guide$geoms, function(g) g$data$size / 10))` can be an empty matrix, which cannot be subsetted. I guess the branch `if (nrow(key_size_mat) == 0 || ncol(key_size_mat) == 0) {` is prepared to handle this.
> Fix guide_bins() when the data has no size

- R/guide-legend.r
- tests/testthat/test-guides.R
This is a PR to fix #3573, a bug whereby guides with repeated labels were merged incorrectly. This bug occurred because the two guides keys were merged using `merge()`, which only works when there are no duplicate values in the `.label` column.
<details>
Current behaviour:
```r
guide1 <- list(
key = tibble::tibble(
colour = 1:4, 
.label = c("low", "low", "high", "high")
)
)
guide2 <- list(
key = tibble::tibble(
linetype = 1:4, 
.label = c("low", "low", "high", "high")
)
)
ggplot2:::guide_merge.legend(guide1, guide2)$key
#>   .label colour linetype
#> 1    low      1        1
#> 2    low      1        2
#> 3    low      2        1
#> 4    low      2        2
#> 5   high      3        3
#> 6   high      3        4
#> 7   high      4        3
#> 8   high      4        4
```
Behaviour after …
> Fix guide merging when there are repeated labels

- NEWS.md
- R/geom-sf.R
- tests/testthat/test-geom-sf.R
Fix #3589
``` r
library(sf)
#> Linking to GEOS 3.7.2, GDAL 3.0.1, PROJ 6.2.0
d <- data.frame(x = 1:5, y = 1:5)
l <- st_linestring(as.matrix(d))
sf <- st_sf(geometry = st_sfc(l))
p1 <- ggplot(d, aes(x, y)) + geom_line(alpha = 0.1) + ggtitle("geom_line()")
p2 <- ggplot(sf) + geom_sf(alpha = 0.1) + ggtitle("geom_sf()")
patchwork::wrap_plots(p1, p2)
```
<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Alpha affects line geom_sf()

- R/bin.R
This closes #3606:
``` r
ggplot() + geom_histogram(aes(x= rep(0.25,10)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```
<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Prevent failure of binning algorithm in rare cases.

- R/geom-ribbon.r
- man/geom_ribbon.Rd
> Add `orientation` argument to geom_ribbon example as it is ambiguous

- R/scale-.r
this pull request try to fix the bug in issue #3574 . 
I set n.breaks as the second parameter of breaks function.
if the n.breaks is not set by users, it will set to the default value 5, which is the same default as trans objects.
n.breaks can be set by end users.
So, after this fix, users can get meaningful breaks by set breaks as a function and get meaningful breaks using the values of limits and n.breaks.
> fix a bug in ScaleBinned$get_breaks()

- R/guides-axis.r
- R/scale-.r
- R/scale-view.r
- tests/testthat/test-scale-discrete.R
- tests/testthat/test-scales-breaks-labels.r
- tests/testthat/test-scales.r
This PR fixes two regressions I introduced in #3398 and #3426. The first affected plots where labels and breaks were specified manually (#3558):
```r
ggplot(mpg, aes(cty, hwy)) +
geom_point() +
scale_x_continuous(
breaks = c(0, 20, 40),
labels = c("0", "20", "40")
)
#> Error: Breaks and labels are different lengths
```
This was because I censored breaks at the wrong place when I introduced `ViewScale`s. This is fixed in this PR.
The second involves plots where there is no data and NA limits (#3560). I think NA limits should be considered "empty" when there is no data, which is how I implemented it in this PR. I also made sure that functional limits work on all discrete scales (#3448), and that NA limits aren't replaced with data limits on discrete scales (I don't even …
> Fix scale- and coord-related regressions

- R/theme-defaults.r
- R/zzz.r
- tests/testthat/test-theme.r
This PR closes #3584 by making sure every theme explicitly defines every possible theme element. The strategy is to simply set every element that hasn't been defined explicitly to `NULL`. This can be done programmatically in a few lines of code.
> Explicitly define all theme elements

- R/guide-bins.R
- R/guide-colorbar.r
- R/guide-legend.r
- R/guides-.r
- R/layer.r
Simplifies and unifies the code that the various guides use to determine which layers to include and exclude. This PR came out of this discussion: https://github.com/tidyverse/ggplot2/pull/3646/files#r353483822
> refactor show.legend code

- DESCRIPTION
- R/utilities-help.r
- man/geom_bar.Rd
- man/geom_boxplot.Rd
- man/geom_linerange.Rd
- man/geom_ribbon.Rd
Fix #3618
```
in utilities-help.r::rd_aesthetics_item, split required
aesthetics specified with pipe operator (e.g. "x|y")
into separate items so that they may be excluded from
the list of all aesthetics prior to rendering the
documentation of parameters.
```
My thoughts on approach included in #3618 comments.
Also have concerns about results of ```testthat``` run, but results are identical to master branch.
> address duplicate aesthetic listings in documentation, re #3618

- DESCRIPTION
- R/theme.r
- man/calc_element.Rd
- tests/figs/deps.txt
- tests/figs/themes/axes-styling.svg
- tests/testthat/test-theme.r
I think this fixes #3662. I still want to add a few additional unit tests to prevent future such regressions.
I had to update one vdiffr reference image because it wasn't drawn correctly previously. (Line styling wasn't properly inherited across a blank element.)
``` r
ggplot(mtcars) + 
geom_point(aes(disp, mpg)) + 
facet_wrap(~gear) + 
theme(strip.text = element_blank(), strip.text.x = element_text())
```
<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Fix theme inheritance when not inheriting from blank

- R/utilities.r
revdepchecks uncovered a small issue in direction flipping for position subclasses that hasn't adapted to the new setup. This PR fixes it
> Make sure flip is never NA

- R/scale-.r
The ScaleContinuous implementation has never specified a `trans` field, despite its methods referencing the field. This has not really been a problem as it is always subclassed, but recent changes mean that it's `print` method will throw an error now.
This PR adds an identity trans object as it's trans field and makes the error go away
> Add trans field to ScaleContinuous

- R/geom-linerange.r
- R/utilities.r
revdepchecks uncovered an edge case in direction detection if position aesthetics are given outside aes(). This PR correctly looks in both data and params when figuring out direction
> Better handle position aesthetics in params

- README.Rmd
- README.md
I see this mixed contents warning on https://ggplot2.tidyverse.org/
> Use HTTPS for CRAN badge

- R/position-stack.r
This PR addresses the problem uncovered in #3529 where position_stack changes the relation of ymin/ymax during stacking, making it difficult to recover the correct line to draw. It is less drastic than what #3607 proposes, and simply ensure minimal changes to the incoming data
> Don't switch relationship of ymin/ymax during stacking

- R/position-collide.r
- tests/figs/deps.txt
- tests/figs/position-stack/area-stacking.svg
- tests/figs/scales-breaks-and-labels/functional-limits.svg
- tests/testthat/test-position-stack.R
- tests/testthat/test-position_dodge.R
Fix #3498 This seems to be the last leftover from moving the area/ribbon reorder into setup_data like the rest of the geoms.
This change make sure that data returned from `collide()` is in the same order is it came in.
I think a general rule should be that positions should never change the order of data, only the content. There are situations where this is not possible, but as a general rule of thumb I think it is sane
> Restore data order after collide

- R/theme-elements.r
- man/register_theme_elements.Rd
@hadley As requested. I wasn't sure whether I should use the prefix `ggxyz` in the code example as well, I can think of reasons for both yes and no.
> Improved docs for register_theme_elements()

- R/guides-axis.r
- R/scale-binned.R
- man/scale_binned.Rd
I just came across a spectacular failure of the new bin scale in combination with the new axis implementation. This PR adresses the two issues: Make sure guide is set to `waiver()` instead of `"none"`. And make sure that breaks are not mapped by the scale unless it is a discrete scale. The old approach worked before because mapping with a continuous position scale was a no-op, but this is not true for the bin scale and it would throw the axis completely off.
> Fix ScaleBinnedPosition for new axis implementation

- R/stat-contour.r
The current implementation of `stat_contour_filled()` does not respect the presence of holes in the contour as it does not provide a `subgroup` column. This PR fixes this:
Before:
``` r
volcano_long <- data.frame(
x = as.vector(col(volcano)),
y = as.vector(row(volcano)),
z = as.vector(volcano)
)
ggplot(volcano_long, aes(x, y, z = z)) + 
geom_contour_filled(aes(fill = stat(level)), bins = 8) + 
scale_fill_brewer()
```
<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
After:
``` r
volcano_long <- data.frame(
x = as.vector(col(volcano)),
y = as.vector(row(volcano)),
z = as.vector(volcano)
)
ggplot(volcano_long, aes(x, y, z = z)) + 
geom_contour_filled(aes(fill = stat(level)), bins = 8) + 
scale_fill_brewer()
``` …
> Respect the presence of holes in calculated contours

- R/stat-contour.r
- tests/testthat/test-stat-contour.R
Currently the `bins` argument in `stat_contour_filled()` is treated as the number of breakpoints, rather than the number of bins. I suspect this is a bug, as most people will use it to set the actual number of bins. This PR fixes it by correcting the bin width from bins calculation
> Make sure nbins are converted to the correct binwidth

- R/guide-bins.R
- R/guide-colorsteps.R
- R/scale-.r
- R/stat-contour.r
- man/guide_bins.Rd
- man/guide_coloursteps.Rd
This PR makes the new bin guides work with discrete scales if the breaks are given in a `cut()` compliant format (e.g. `(4, 19]`).
This, most importantly, makes the bin guides work with `geom_contour_filled()` but also gives a venue for users to pre-bin their data and still benefit from the new guides.
Example:
``` r
volcano_long <- data.frame(
x = as.vector(col(volcano)),
y = as.vector(row(volcano)),
z = as.vector(volcano)
)
ggplot(volcano_long, aes(x, y, z = z)) + 
geom_contour_filled(aes(fill = stat(level)), bins = 8) + 
scale_fill_brewer()
```
``` r
ggplot(volcano_long, aes(x, y, z = z)) + 
geom_contour_filled(aes(fill = stat(level)), bins = 8) + 
scale_fill_brewer(guide = guide_colorsteps())
```
<sup>Created on 2020-01-08 by the [reprex …
> Make bin guides compatible with discrete scales

- R/geom-density.r
- man/geom_density.Rd
- tests/testthat/test-function-args.r
The new stroking of `geom_ribbon()` and `geom_area()` didn't make it to `geom_density()` This PR adds it and make it behave like `geom_area()`
> Set outline type for geom_density as geom_area

- R/compat-plyr.R
- tests/testthat/test-rbind-dfs.R
When I wrote out ply, I inadvertently dropped support for ordered factors. This is such a niche data structure that it didn't set of any alarms, but I noticed it when I wanted `stat_contour_filled()` to return levels as ordered.
This PR fixes the regression by not converting ordered factors into factors when binding data.frames
> don't drop ordering from ordinal factors

- R/geom-ribbon.r
- man/geom_ribbon.Rd
- tests/testthat/test-geom-ribbon.R
Currently only `"both"` and `"upper"` settings are valid for the new stroking in `geom_ribbon()`/`geom_area()` While the need for `"lower"`can perhaps be debated, I don't see a reason to not allow it. This PR adds the functionality
> Allow "lower" outline type in geom_ribbon and family

- _pkgdown.yml
Fixes #3697 
This PR is primarily to fix the following missing topics:
> Warning: Topics missing from index: draw_key, guide_axis, guide_bins, guide_coloursteps, guide_none
(https://travis-ci.org/tidyverse/ggplot2/jobs/633940915#L1365)
In addition, this tweaks the index a bit more:
* Replace `stat()` with `after_stat()`
* Use https URLs
> Improve pkgdown reference index

- R/annotation-map.r
- man/annotation_map.Rd
Fix #3712
The new farver package now raises an error for invalid colour names (c.f. #3644) for example when we typoed `NA` as `"NA"`. This PR fixes the example.
> Fix typos in examples of annotation_map()

- NEWS.md
- R/geom-density.r
- R/geom-ribbon.r
- man/geom_density.Rd
- man/geom_ribbon.Rd
- tests/testthat/test-geom-ribbon.R
(Followup of #3708)
I originally named this option as `"legacy"` to discourage the usage in the hope of deprecating and removing this option eventually. But, this might be needed a bit longer than expected to keep the backward-compatibility of `geom_density()`. This PR
* renames "legacy" to "full",
* removes a warning, and
* describes about `geom_density()` in the NEWS
> Rename outline.type option "legacy" to "full"

- R/guides-axis.r
This fixes #3718. I am confident about this fix. It doesn't touch `merge_element()` at all, only makes a minor change in `draw_axis()`, and simply copies over the relevant properties manually instead of merging the elements. Reprex below shows that things work as expected with this fix.
``` r
library(ggtext)
ggplot(mpg, aes(class)) + 
geom_bar() +
scale_x_discrete(
name = "vehicle *class*",
labels = c("2seater", "*compact*", "midsize", "**minivan**", "pickup", "<sub>sub</sub>compact", "suv")
) +
theme(
axis.title.x = element_markdown(
linetype = 1, fill = "cornsilk", r = unit(5, "pt"), padding = margin(4, 4, 4, 4)
),
axis.text.x = element_markdown(
linetype = 1, fill = "cornsilk", r = unit(5, "pt"), padding = margin(4, 4, 4, 4)
)
)
```
<sup>Created on 2020-01-09 by the …
> Fixes #3718

- R/aes.r
- R/layer.r
This issue is based on failing revdep check of ggspectra and its reverse dependencies
Currently aes name standardisation changes every occurrence of "color" to "colour", not just the exact string "color". This has not been a problem before, but with the new aesthetic evaluation we have chosen to substituted names inside the expressions used in `after_stat()` and `after_scale()` and this causes problems if the expression references a US spelling column in the data.
This PR fixes it by only matching exactly to "color", but I'm unsure about whether there will be unforeseen consequences of this change. Another approach would be to substitute the names of the columns as well
> make sure aes renaming is reflected in data

- NEWS.md
- R/aes-evaluation.r
- tests/testthat/test-aes-calculated.r
@thomasp85 this ensures that when you use the `.data` pronoun with ggplot2, it doesn't adversely affect the labels.
@paleolimbot — this should make your talk slightly simpler 😄
> Strip .data from default labels

- R/zzz.r
* Link to ggplot2 book
* Update link to R Graphics Cookbook
> Refactor and update random tips

- NEWS.md
- R/facet-.r
- R/facet-grid-.r
- R/facet-wrap.r
- tests/testthat/test-facet-.r
(Cherry-picked version of #3735 for v3.3.0-rc branch)
---
Fix #2963
Not all variables in a facet spec are available on all the layers. A solution suggested on https://github.com/r-lib/rlang/issues/888#issuecomment-573691024 is:
> bind the same symbols inside each panel, and when the symbols are undefined use an active binding to throw a typed error? And then you'd only catch these particular errors in the `tryCatch()`
This PR injects such an active bindings on the column names of all the plot data so that we can let `eval_facet()` fail gracefully.
`eval_facet()` evaluates facet specs in these two steps:
1. When the spec is a symbol (the most common case), check if the layer data contains the same name of column. If it does, subset the column and return it. If it doesn't, return `NULL`. In …
> Allow expressions in facet specs even when some variables are not available on some layers

- R/layout.R
- R/utilities.r
- vignettes/profiling.Rmd
When handling large datasets (>1e6 rows), scale_apply ends up being the main bottleneck (around 50% of the rendering time) This is all due to a call to `factor()` on the vector identifying which positional scale each row belongs two (this happens 8 time in total, as the scales are trained and mapped twice for both x and y).
This PR simplifies the factor construction as well as bypass it completely in the case of only a single scale (which is the predominant case). It speeds up the step 1000-fold for single panel plots and 2-3 fold otherwise
> Faster scale_apply

- R/geom-text.r
- man/geom_text.Rd
- man/ggsf.Rd
> Improve geom_text documentation (#3753)

- R/position-dodge.r
- man/position_dodge.Rd
Fixes #2767 
Uncertain if this is clear enough based on discussion in issue; suggestions very welcome! :)
> describe dif strategies used by position_dodge and position_dodge2

- R/scale-.r
Fixes #3468 -- prints "function()" instead of "NA NA" for limits when printing scales where limits are set by function.
New result:
``` r
g <- ggplot(iris, aes(Sepal.Width, Sepal.Length,
colour = Petal.Width)) +
geom_point()
goodprint <- g + scale_colour_continuous(limits = range(iris$Petal.Width))
badprint <- g + scale_colour_continuous(limits = function(lims) {1 * lims})
print(goodprint$scales$scales[[1]])
#> <ScaleContinuous>
#>  Range:  
#>  Limits:  0.1 --  2.5
print(badprint$scales$scales[[1]])
#> <ScaleContinuous>
#>  Range:  
#>  Limits: function()
```
<sup>Created on 2020-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Modify printing when limits are a function

- R/theme-current.R
- R/theme.r
- man/theme.Rd
- man/theme_get.Rd
> update theme documentation reference links & clarify differences between theme_set and theme_update()

- R/legend-draw.r
Resolves: #3455 
Below is reprex of this working:
```
dat <- data.frame(
x = as.factor(1:10),
y = c(20,30,13,37,12,50,31,2,40,30),
z = rep('a', 10)
)
ggplot(dat) +
geom_segment(
aes(x = x, xend = x, y = 0, yend = y+15, linetype = z), 
arrow = arrow(length = unit(0.25, 'cm'), type = 'closed'),
size = 0.7
) 
```
New output:
Old output:
> Pass fill value to legend key icons

- R/utilities.r
Fix #3761
Currently, we try to make a precise guess in `has_flipped_aes()`, but it seems the guess goes wrong in some cases when both axis are discrete like. I don't know what the proper fix would be, but I think it's rather safe to stay unflipped when we are not fully sure it's flippable, considering we want to avoid introducing some big change to the current RC branch.
> Do not flip eagerly when both axis are discrete like

- NEWS.md
- R/annotation-raster.r
- man/annotation_raster.Rd
Small change to allow passing a `nativeRaster` object to `annotation_raster()`. This is a significant performance improvement for large rasters.
I didn't include an example because I don't see a source for a native raster in `{ggplot2}`. I could use the R logo from `{png}` but that package is not currently used by ggplot2. If you think an example is called for, please advise.
> Add support for native rasters to `annotation_raster()` #3388

- R/stat-boxplot.r
- R/utilities.r
- man/bidirection.Rd
Superseedes #3764 
This PR introduces a new switch in `has_flipped_aes()` which confines the single value check to those requesting it (currently only boxplot)
> Make sure boxplot check doesn't polute other stats/geoms

- R/guide-bins.R
- R/guide-legend.r
Fixes #3729 
This PR catches any errors happening when applying `after_scale()` modifications to legend keys. If it errors it will simply discard them all with a warning.
It may be done more fine grained, but not without a lot of weird refactoring of the code to accommodate this edge-case. This PR fixes the surprise of the legend disappearing and gives a meaningful warning. If we get a lot of requests for better support (I doubt it) we can revisit it in the future
> Catch errors when applying after_scale mods to legend keys

- R/guides-axis.r
- R/scale-.r
This PR addresses an issue in scales. If a label function converts an `NA` break to a `character(0)` label we will get an error later on when we enlist the label list. This is fixed here in the `ScaleContinuous$get_labels()` function by converting such list elements to empty strings (`""`) instead.
It can be argued that this should get fixed in `scales::label_number_auto()` (and perhaps it should as well), but I think it makes sense to have a guard in ggplot2 as well, since otherwise this problem will be carried all the way to `guide_axis()` and create an unintelligible error there.
> Handle label functions that return character(0)

- NEWS.md
Two missing backticks and a several missing newlines were causing incorrect or inconsistent rendering of markdown.
> Fix missing backticks and newlines in NEWS.md

- icons/icons.R
- tests/testthat/test-aes-setting.r
- tests/testthat/test-geom-quantile.R
Fix partial argument names for `seq` by specifying the full arg name `length.out`.
> Fix seq partial argument names

- R/geom-bar.r
- man/geom_bar.Rd
Closes #3809.
``` r
ggplot(iris, aes(x = Sepal.Length)) +
geom_bar(stat = "bin", binwidth = 0.1)
```
``` r
ggplot(mtcars, aes(factor(gear))) +
geom_bar(binwidth = 0.1)
#> Warning: Ignoring unknown parameters: binwidth
```
<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Remove `binwidth` entirely from geom_bar()

- R/stat-bin.r
- man/geom_histogram.Rd
`width` is deprecated, yet the documentation for using `center`/`boundary` still reference it instead of `binwidth`.
> reference binwidth instead of width in documentation

- NEWS
- NEWS.md
- R/save.r
Devices like `devEMF::emf` or `Cairo::CairoSVG` use `file` instead of `filename`. They currently fail when provided in `device` to ggsave. This fixes that.
Closes https://github.com/tidyverse/ggplot2/issues/3807
> Permit function devices to use `file` argument

- tests/testthat/helper-facet.r
Avoids making assumptions about internals of quosure lists. Fixes a test failure with dev rlang.
> Use rlang to generate quosure list

- R/aes-evaluation.r
- tests/testthat/test-aes-calculated.r
This fixes a regression in the `.data` stripping code for default labels that would remove it before evaluation as well
> Avoid stripping .data pronoun during evaluation

- R/limits.r
- man/lims.Rd
improve lims docs: closes #3752
> add warning in lims docs about values outside of limits being removed from data

- R/scale-.r
Fix #3867 
``` r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(x = rep(1:3, 2), y = rep(1:2, 3), z = 1:6) %>% 
mutate(z = ifelse(x == 1 & y == 1, NA, z))
p <- ggplot(df, aes(x = x, y = y)) +
geom_tile(aes(fill = z))
p + scale_fill_viridis_b(na.value = "red")
```
<sup>Created on 2020-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Use na.value in ScaleBinned$map()

- R/guides-axis.r
- tests/testthat/test-guides.R
This is a fix for #3874, which gave warnings when changing the position of a `guide_axis()`. I *think* this is a four character fix (typo in my implementation of `guide_merge.axis()`). The warnings are now gone:
``` r
ggplot(mpg) +
geom_bar(aes(x = manufacturer)) + 
guides(x = guide_axis(position = 'top'))
```
<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Fix merge warning for `guide_axis()` when merging with `guide_none()`

- .github/workflows/R-CMD-check.yaml
`covr::codecov()` keeps failing on GitHub Action CI.
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Calls: <Anonymous> ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted
##[error]Process completed with exit code 1.
```
https://github.com/tidyverse/ggplot2/runs/509138337?check_suite_focus=true#step:13:14
I tried some tweaks on my forked repo (https://github.com/yutannihilation/ggplot2/pull/4/), but none of these worked. As the other repos (e.g. [roxygen2](https://github.com/r-lib/roxygen2/blob/2a068b181bc15ec55545ddd752f5341471f5e74a/.github/workflows/R-CMD-check.yaml#L83-L86)) works without error, this seems specific to ggplot2. So, I think it takes some time to figure out what's …
> Temporarily disable Test coverage step on GitHub Action CI

- DESCRIPTION
- R/zzz.r
This seems to address #3900 
I don't really understand why though 🤷‍♂
> Import lifecycle

- R/stat-contour.r
- tests/testthat/test-stat-contour.R
Closes #3906.
``` r
v <- ggplot(faithfuld, aes(waiting, eruptions, z = density)) +
geom_point(aes(color = density)) + geom_contour(color = "white")
v
```
``` r
v + scale_x_log10()
```
<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> fix stat_contour() for irregular data grids.

- tests/testthat/test-coord-.r
removed a seemingly  unneeded expect_equal(2 * 2, 4). Please let me know if this test serves a purpose. I was reading through this project to see good examples of testthat.
> removed expect_equal(2 * 2, 4)

- .travis.yml
I'm pretty sure vdiffr hasn't been running on Travis CI since https://github.com/tidyverse/ggplot2/commit/9fdf452d34be3986c778c9f4306ce96c7c14af8e
> Run visual tests on CI

- R/layer-sf.R
Fixes #3941.
``` r
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
p <- ggplot(nc[1:3, ]) +
geom_sf(aes(color = NAME), show.legend = "point")
p
```
``` r
p
```
<sup>Created on 2020-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Don't modify legend key settings in geom_sf() during plot build.

- README.Rmd
- README.md
- _pkgdown.yml
ggplot2 extension site has been moved to exts.ggplot2.tidyverse.org. For more details, see ggplot2-exts/gallery#87.
> Move the domain of ggplot2-exts to exts.ggplot2.tidyverse.org

- R/geom-bar.r
- R/utilities.r
- man/bidirection.Rd
Fixes #3866 
The check for `range_is_orthogonal` in `geom_bar()` was unneeded and resulted in failure with edge cases
> ignore min/max variables when detecting orientation in geom_bar

- _pkgdown.yml
👋 team,
I am working on DocSearch. [We have an integration for pkgdown](https://pkgdown.r-lib.org/). We thought it is a shame you can not also used this search.
This PR will add DocSearch to the documentation website. It will allow a user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.
Let me know if you need anything.
> feat: add DocSearch as recommended by pkgdown

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/test-coverage.yaml
This PR addresses the following issues:
* ~~Add a workaround for problem about Rcpp on macOS runner (https://github.com/RcppCore/Rcpp/issues/1060).~~ (Rcpp is fixed on CRAN)
* Install xml2 from GitHub on macOS runner (c.f https://github.com/r-lib/xml2/issues/296).
* Install covr from GitHub to enable codecov again (c.f. https://github.com/tidyverse/ggplot2/pull/3862#issuecomment-599557468).
* Add `cache-version` to enable cache clear.
> Various fixes on GitHub Actions CI

- DESCRIPTION
- _pkgdown.yml
* Mark RStudio as funder
* Use second level headings on reference page
* Use new news metadata structure
> Minor website tweaks

- NEWS.md
- R/layer-sf.R
- tests/testthat/test-geom-sf.R
Fixes #3963.
``` r
nc <- sf::read_sf(system.file("shape/nc.shp", package="sf"))
nc$BIR74_bin <- cut_number(nc$BIR74, 3)
nc_tibble <- tibble::as_tibble(nc)
ggplot(nc_tibble) +
geom_sf(aes(geometry = geometry, fill = BIR74_bin))
```
<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> make legend detection code more robust.

- .github/workflows/R-CMD-check.yaml
- .travis.yml
- DESCRIPTION
Now R 4.0.0 is released, ~~let's drop support for R 3.2 (c.f. we support only 4 previous versions of R https://www.tidyverse.org/blog/2019/04/r-version-support/).~~ let's add R 4.0 runners on CI
In addition, this PR contains the following tweaks:
* Remove a workaround related to xml2 installation problem, as the new version of xml2 was released on CRAN
* Add `cran:libgit2` PPA to avoid conflicts related to `libcurl4-gnutls-dev` (c.f. https://github.com/r-hub/sysreqsdb/issues/77#issuecomment-620025428)
> Test R 4.0 on CI

- R/guide-colorsteps.R
This PR addresses #3877 without providing a true fix. The `even.steps = FALSE` feature piggybacks on the `guide_colourbar()` rendering which does not work on discrete scales. A complete rewrite of the functionality would be needed which is not a priority before the guide rewrite.
This PR simply emits a warning about the feature not working for that particular case
> warn user when even.steps=FALSE is used with a discrete scale

- NEWS.md
- R/scale-colour.r
- man/scale_colour_continuous.Rd
> Type argument in scale_[fill/colour]_[continuous/binned] can accept a function

- NEWS.md
> Add news item for facet strip themeing

- NEWS.md
- R/stat-function.r
- tests/testthat/test-stats-function.r
Closes #3905.
``` r
library(tidyverse)
library(patchwork)
fn <- function(x) {exp(x)}
data <- tibble(x = c(1:10), y = exp(x))
p <- ggplot(data, aes(x)) + stat_function(fun = fn)
q <- ggplot(data, aes(x, y)) + geom_point() + 
stat_function(fun = fn)
p / q
```
``` r
(p + scale_y_log10()) / q + scale_y_log10()
```
``` r
(p + scale_y_sqrt()) / q + scale_y_sqrt()
```
``` r
(p + scale_y_reverse()) / q + scale_y_reverse()
```
``` r
(p + scale_x_log10()) / q + scale_x_log10()
```
``` r
(p + scale_x_log10() + scale_y_log10()) /
q + scale_x_log10() + scale_y_log10()
```
<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Fix stat_function() for transformed scales

- R/scale-.r
- R/scale-expansion.r
- tests/testthat/test-scale-expansion.r
- tests/testthat/test-scales-breaks-labels.r
This PR fixes the case where only continuous values were provided to a discrete scale, which was also provided continuous limits. I introduced this bug in #3380, which changed the way that discrete scales were expanded into continuous limits ([old logic](https://github.com/tidyverse/ggplot2/blob/v3.2.1/R/scale-discrete-.r#L111), [new logic](https://github.com/tidyverse/ggplot2/blob/master/R/scale-expansion.r#L204))
``` r
df <- data.frame(x = 1:14, y = -2:-15)
scale_y_discrete(limits = -1:-16, labels = LETTERS[1:16])
```
<sup>Created on 2020-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Note that `is.discrete()` in this PR is linked to `is.discrete()` in `ScaleDiscretePosition$train()`...I don't think that the discrete …
> Fix bug in discrete position scales with continuous limits (fixes #3918)

- R/facet-grid-.r
This fixes the inconsistent naming in the `gtable` of `facet_grid()` panels to result in the pattern `panel-[row.nr]-[col.nr]`.
Reprex in issue: https://github.com/tidyverse/ggplot2/issues/3978
> Renamed panel titles in gtable of plot with facet_grid()

- R/coord-sf.R
- man/ggplot2-package.Rd
- man/ggsf.Rd
- man/scale_discrete.Rd
- man/scale_manual.Rd
- man/scale_shape.Rd
> Improved docs for coord_sf().

- .github/workflows/test-coverage.yaml
Now test-coverage GitHub action keeps failing due to this error:
```
Error : package ‘rex’ was installed before R 4.0.0: please re-install it
```
This is my fault that I forgot to take care of `test-coverage.yaml` in #3961. This PR fixes it.
> Explicitly specify the R version on test-coverage action

- R/scale-view.r
- tests/testthat/test-scales-breaks-labels.r
Fix #3952
`ylim` and `xlim` of `coord_cartesian()` can be specified in arbitrary order. But, `ScaleContinuous$get_breaks()` always expects the limits are in the same order to their order. If not, it returns `NA` and we'll see no ticks. So, the limits should be sorted before passing to it.
I think scale should raise more explicit warnings or errors, but it's out of scope of this PR.
``` r
devtools::load_all("~/repo/ggplot2/")
library(patchwork)
d <- base::data.frame(
x = 1:4,
y = 1:4
)
p <- ggplot(d, aes(x, y)) +
geom_point()
p1 <- p + coord_cartesian(ylim = c(1, 10)) + ggtitle("(usual plot)")
p2 <- p + coord_cartesian(ylim = c(10, 1)) + ggtitle("Coord is reversed")
p3 <- p + scale_y_reverse() + coord_cartesian(ylim = c(1, 10)) + ggtitle("Scale is reversed, but Coord is …
```
> Allow specifying the limit of Coord in the opposite order to the Scale

- R/utilities.r
- man/bidirection.Rd
- man/ggtheme.Rd
Fixes a typo and a missing word in the documentation for `has_flipped_aes()`. Rendering the .Rd files also turned up a roxygen/Rd mismatch from #3787. It's just a tiny change, so I've included it here.
> Fix typo in docs

- R/geom-ribbon.r
- tests/figs/geom-smooth/ribbon-turned-on-in-geom-smooth.svg
- tests/figs/position-stack/area-stacking.svg
Fix #3891 This PR fixes the oversight of adding the line aesthetics to the polygonGrob for `outline.type = 'full'`
> make sure linetype and linewidth is passed on to the polygongrob

- R/stat-.r
This comes out of the discussion in #3860 which surfaced that Stat did not have the same `optional_aes` field as Geom. This PR simply mirrors the Geom implementation so that Stats can declare optional aesthetics.
I'd like to get this into 3.3.1 so I can use it in the book
> Allow using optional_aes in Stat

- R/guide-bins.R
- R/guide-colorsteps.R
Fix #3876 This PR makes sure NA are not represented in the guide. Whether these guides (and colourbar) should actually represent `NA` (in a more aesthetically pleasing way) is a discussion for later when a guide rewrite is done
> remove NA breaks before creating the guides

- NEWS.md
- R/stat-contour.r
Closes #4004.
``` r
library(tidyverse)
ggplot(faithfuld, aes(waiting, eruptions, z = density)) + 
geom_contour_filled(bins = 2)
```
``` r
ggplot(faithfuld, aes(waiting, eruptions, z = density)) + 
geom_contour_filled(bins = 5)
```
``` r
ggplot(faithful, aes(waiting, eruptions)) +
geom_density_2d_filled(bins = 3)
```
``` r
ggplot(faithful, aes(waiting, eruptions)) +
geom_density_2d_filled(bins = 4)
```
``` r
ggplot(faithful, aes(waiting, eruptions)) +
geom_density_2d_filled(bins = 6)
```
``` r
df <- volcano %>%
as_tibble() %>%
rowid_to_column(var = "x") %>%
gather(key = "y", value = "z", -1) %>%
mutate(y = as.numeric(gsub("V", "", y)))
#> Warning: `as_tibble.matrix()` requires a matrix with column names or a `.name_repair` argument. Using compatibility `.name_repair`.
#> This warning is …
```
> Better binning algorithm for contours

- R/geom-function.R
- R/stat-function.r
- tests/testthat/test-stat-function.R
``` r
library(RBesT)
#> Warning: package 'RBesT' was built under R version 3.6.2
#> Loading required package: Rcpp
#> This is RBesT version 1.6.0
bm <- mixbeta(weak=c(0.2, 2, 10), inf=c(0.4, 10, 100), inf2=c(0.4, 30, 80))
bm[[c(2,3)]]
#> Univariate beta mixture
#> Mixture Components:
#>   inf   inf2 
#> w   0.4   0.4
#> a  10.0  30.0
#> b 100.0  80.0
plot(bm[[c(2,3),rescale=TRUE]])
```
<sup>Created on 2020-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> fix stat_function() regression

- R/geom-ribbon.r
- tests/testthat/test-geom-ribbon.R
Fix #4023
The current implementation squashes the upper and lower lines together and tweaks the lower one's `id` on the assumption that the upper and the lower has the same number of rows as the original data. But, it's not true when the Coord is non-cartesian.
<details>
https://github.com/tidyverse/ggplot2/blob/48268385c414702bc343e46d51144846d39232fa/R/geom-ribbon.r#L131-L135
https://github.com/tidyverse/ggplot2/blob/48268385c414702bc343e46d51144846d39232fa/R/geom-ribbon.r#L139
https://github.com/tidyverse/ggplot2/blob/48268385c414702bc343e46d51144846d39232fa/R/geom-ribbon.r#L158-L164
</details>
This PR fixes this issue by processing the upper and the lower separately.
``` r
devtools::load_all("~/repo/ggplot2/")
d <- base::data.frame(x = c(1, 2), y = c(3, 4)) …
```
> Fix geom_ribbon() on non-cartesian Coords

- R/geom-text.r
- R/scale-hue.r
- man/geom_text.Rd
- man/ggsf.Rd
Fix a typo in the `geom_text()` documentation and a roxygen2 bug introduced in recent PR #3833.
> Minor documentation fixes.

- NEWS.md
This should have been done as a part of #3833 (sorry!)
> Update NEWS to include discrete color scale options from #3833

- R/coord-polar.r
- man/coord_polar.Rd
Motivation: current documentation for coord_polar() does not mention that 'start' offset can be applied either clockwise or anticlockwise. Added note in docs that the offset is applied depending on orientation specified by 'direction' parameter (1 = clockwise, -1 = anticlockwise).
> Add details to start parameter of coord_polar (#3893).

- R/scale-.r
- man/discrete_scale.Rd
- man/scale_discrete.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_linetype.Rd
- man/scale_manual.Rd
- man/scale_shape.Rd
> Explain possible arguments for discrete limits

- R/stat-density-2d.r
- man/geom_density_2d.Rd
Close #3946
I have borrowed the parameter description from [geom-contour](https://github.com/tidyverse/ggplot2/blob/2b03e4723f0b91875667ffb4f952ad6e471ac9f8/R/geom-contour.r#L16).
(This is my first pull request for ggplot2, and I'm not familiar with roxygen2, so apologies if I have missed something obvious.)
> Add description of undocumented parameters

- .github/workflows/R-CMD-check.yaml
- .travis.yml
Fix #4045 
We need two fixes here:
* For the macOS (devel) runner, bump cache version to clear the cache
* For the Linux (<3.6) runner, install the dev version of rmarkdown package. This will be unnecessary after the next version of rmarkdown is released on CRAN.
> Fix CI failures

- .github/workflows/R-CMD-check.yaml
The new version of rmarkdown was released on CRAN and it now contains the fix for `tools::vignetteInfo()` errors.  The workaround is no longer needed.
> Remove a workaround about rmarkdown on R <3.6

- R/scale-shape.r
- man/scale_shape.Rd
Fixed typo in scale_shape documentation.
> subsequence -> subsequent in docs

- R/facet-grid-.r
- R/facet-null.r
- R/facet-wrap.r
When providing a reversed scale along with certain coords the aspect ratio may end up as negative and the panel will get a negative null dimension. This can wreck havoc (see https://github.com/thomasp85/patchwork/issues/195)
This PR fixes it by ensuring the dimension is always positive
> Make sure panels are always set to a positive size

- R/coord-sf.R
- man/sf_transform_xy.Rd
> Use sf::sf_project() to transform spatial coordinates.

- R/scale-.r
Closes #4087, specifically the issue where a named palette that didn't match the limits would still get used if too many colors were requested. We now use a more accurate check for whether the palette has names, so if the colors don't match the limits it won't be used. This is the conventional behavior, though as discussed on the issue it can be confusing. This PR makes the behavior consistent, but we might want to separately revisit whether to change the behavior of `scales::manual_pal()`.
> More accurate check for palette names

- R/zzz.r
There's a typo in one of the random tips shown when loading the package, "Cookbook" is spelled "Cookbok".
> typo in startup message random tip

- .github/workflows/R-CMD-check.yaml
Close #4095 
According to [R-internals](https://cloud.r-project.org/doc/manuals/r-patched/R-ints.html#index-_005fR_005fCHECK_005fRD_005fXREFS_005f), we can avoid the warning by setting  `_R_CHECK_RD_XREFS_` to `FALSE`.
> Ignore Rd xref warnings on R 3.2

- R/coord-polar.r
I encountered this strange error. It took me a while to get a reprex because it is incredibly elusive. 
``` r
grid <- expand.grid(x = seq(0, 360, by = 2.5), y = seq(-90, -20, by = 2.5))
grid$z <- with(grid, x^2*y)
ggplot(grid, aes(x, y)) +
geom_contour(aes(z = z)) +
coord_polar() +
scale_x_continuous(breaks = seq(0, 360, by = 30), labels = NULL)
#> Error in labels[[n]] <- combined: attempt to select less than one element in integerOneIndex
```
The issue was that `coord_polar()` tries to combine labels even if they are `NULL`. I added a check. All tests succeed and the bug is fixed.
> Doesn't try to combine labels if labels are NULL

- .github/workflows/R-CMD-check.yaml
Close #4116 
Googling the error message "Graphics API version mismatch" led me to the possibility that the version of R devel might be bumped up. Clearing the cache seems solve the problem. 
c.f. https://github.com/davidgohel/ReporteRs/issues/126#issuecomment-226176502
> Clear cache to handle R-devel change

- NEWS.md
- R/stat-ydensity.r
Addresses https://github.com/tidyverse/ggplot2/issues/4111
`stat_ydensity` now drops groups with fewer than 2 data points (previously 3) and displays a warning.
``` r
table(mtcars$cyl, mtcars$am)
#>    
#>      0  1
#>   4  3  8
#>   6  4  3
#>   8 12  2
ggplot(mtcars, aes(x = factor(cyl), y = mpg, fill = factor(am))) + 
geom_violin(scale = "width")
```
``` r
mtcars_sub <- mtcars[-31, ]
table(mtcars_sub$cyl, mtcars_sub$am)
#>    
#>      0  1
#>   4  3  8
#>   6  4  3
#>   8 12  1
ggplot(mtcars_sub, aes(x = factor(cyl), y = mpg, fill = factor(am))) + 
geom_violin(scale = "width")
#> Warning: Groups with fewer than two data points have been dropped.
```
<sup>Created on 2020-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Bring stat_ydensity behavior in line with stat_density 

- NEWS.md
- R/guides-.r
- tests/testthat/test-guides.R
Fix #4097
`guides(... = FALSE)` was a very old syntax and is not mentioned in any documentations. This should be deprecated to inform the users about the recommended way (`guides(... = "none")`).
> Deprecate guides(... = FALSE)

- R/layer-sf.R
- tests/testthat/test-geom-sf.R
Fix #4122 
Currently, `LayerSf$setup_layer()` uses `as_name(self$mapping$geometry)` in the assumption that `geometry` is a quosure of a symbol, which is not always the case. Possible fix would be
1. actually evaluate it
2. give up guessing the type nicely
and I chose option 2. because option 1. seems too much for this rare use case.
``` r
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc) +
geom_sf(aes(fill = AREA, geometry = sf::st_centroid(geometry)))
#> Warning in st_centroid.sfc(geometry): st_centroid does not give correct
#> centroids for longitude/latitude data
#> Warning in st_centroid.sfc(geometry): st_centroid does not give correct
#> centroids for longitude/latitude data
```
<sup>Created …
> Handle when `geometry` is not a symbol

- R/bin.R
Fix #4131
``` r
ggplot(tibble::tibble(x=c(1, 1e12)), aes(x)) + geom_histogram(binwidth=1)
#> Warning: Computation failed in `stat_bin()`:
#> The number of histogram bins must be less than 1,000,000.
#> Did you make `binwidth` too small?
```
<sup>Created on 2020-07-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Warn too many breaks before doing `seq()`

- DESCRIPTION
- R/stat-boxplot.r
- R/stat-smooth.r
- man/geom_boxplot.Rd
- man/geom_smooth.Rd
Fix #4124
These four stat have variables whose names differ depending on the orientation.
- `stat_boxplot()`: `middle`, `lower`, and `upper`. This feels a bit tricky at least in two points; the flipped names are asynmetric (e.g. `middle` vs `xmiddle`, not `ymiddle` vs `xmiddle`), and `notchlower` and `notchupper` doesn't have their flipped form.
- `stat_smooth()`: `y`, `ymin`, and `ymax`
- `stat_function()` ~~`stat_ecdf()`~~ : these generate both `x` and `y`, so the documentation would be cryptic like below, so I don't address them in this pull request (at least they don't have undocumented computed variables)
```
#' `stat_function()` computes the following variables:
#' \describe{
#'   \item{x or y}{x or y values along a grid}
#'   \item{y or x}{value of the function evaluated at …
```
> Document flipped computed variables

- R/scale-binned.R
- R/scale-continuous.r
I happened to find `scale_{x,y}_binned()` doesn't include `x0` and `y0`, which I think is unintended. Probably we should refer to `ggplot_global` directly in these cases. Hard coding the same list on 4 places is a bit hard to maintain.
> Refer to ggplot_global for x and y aesthetics variables

- man/scale_viridis.Rd
- tests/testthat/test-scales.r
Followup of #4048
* Regenerate the document to fix the build failure (it complains because there's no alias of `scale_color_viridis_b`)
* Add a test to check if all `scale_colour_*()` have their corresponding `scale_color_*()`.
> Regenerate document and add a test to ensure no missing scale_color_*()

- R/scale-brewer.r
- man/scale_brewer.Rd
Use ColorBrewer project name rather than obsolete website name.
Not sure what is meant by "use blender variants" in the last example. Should it be "use binned variants"?
> typos; stick to en-GB; prefer project to website

- .github/workflows/pkgdown.yaml
pkgdown action now fails with the following error. It seems we now need to configure username and email explicitly (c.f. https://github.com/r-lib/actions/issues/135). Since [the latest `pkgdown.yml`](https://github.com/r-lib/actions/blob/e9e2c876f3578ce790f0242ba27e67a85b3a9081/examples/pkgdown.yaml) already handles this and it contains some other improvements, I copied it and added some tweaks (including `publish` event, installing binary packages, and installing tidytemplate).
<https://github.com/tidyverse/ggplot2/runs/921163458#step:7:520>:
```
── Commiting updated site ──────────────────────────────────────────────────────
Running git add -A .
Running git commit --allow-empty -m \
'Built site for ggplot2: 3.3.2.9000@8f7b03c'
*** Please tell me who you are.
Run
git config --global …
```
> Update pkgdown GitHub Action

- R/stat-summary.r
- man/stat_summary.Rd
Fix #4150 
Replace cyl with factor(cyl) in discrete orientation example of stat_summary
> Fix discrete orientation example in stat_summary

- .github/workflows/pr-commands.yaml
Sorry, I found I needed to add `git config` also to pr-commands.yaml... This PR updates pr-commands.yaml to [the latest one on r-lib/actions](https://github.com/r-lib/actions/blob/9b0e9a42c639483e129d48f25f338015ef243b3a/examples/pr-commands.yaml). This time, I confirmed `/document` works on my forked repo: https://github.com/r-lib/actions/blob/9b0e9a42c639483e129d48f25f338015ef243b3a/examples/pr-commands.yaml
> Update pr-commnads.yaml to the latest

- R/geom-.r
- man/ggplot2-ggproto.Rd
Per #4158, the docs used to say that Geoms don't have the `setup_params()` method, which is no longer true (#3506). I've deleted this paragraph.
> Docs no longer say Geoms don't have setup_params() method

- DESCRIPTION
- NEWS.md
- R/save.r
- man/ggsave.Rd
- tests/testthat/test-ggsave.R
Closes #4057. @clauswilke I took your proposed approach and calculated the theme element to get the background color. I imagine people will still typically want to edit their theme to remove the plot border.
I'm opening this as a draft because I think it needs a test but I'm not sure how best to write one. Is there a way to have vdiffr compare two files rather than comparing a plot object against a file? I imagine there is and that vdiffr is doing this under the hood normally, but I tinkered with it a bit and couldn't figure it out.
``` r
library("ggplot2")
p <- ggplot(mtcars, aes(disp, mpg)) +
geom_point() +
coord_fixed() + # using coord_fixed() just to emphasize what's the plot and what's the image background
theme(plot.background = element_rect(fill = "forestgreen")) …
```
> Set file background from plot theme

- R/quick-plot.r
Fix #4170 
qplot(1:10)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
<sup>Created on 2020-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Avoid "<empty>" labels with qplot()

- .github/workflows/R-CMD-check.yaml
- tests/testthat/helper-vdiffr.R
- tests/testthat/test-ggsave.R
I'm not sure if systemfonts will be available again on R 3.3 and 3.2 (if we follow the 5 version policy, the support for 3.2 might be dropped), but I think the tests should handle this gracefully anyway, as vdiffr is not actually used for testing on the versions. It seems we also need to skip the ggsave test newly added by #4164 as svglite also depends on systemfonts.
Also, this PR reflects some changes on [r-lib/action's check.full.yaml](https://github.com/r-lib/actions/blob/master/examples/check-full.yaml) (Use RStudio package manager, and use binary packages on R-devel as well).
> Fix CI by skipping visual tests when vdiffr is not available

- NEWS.md
- R/scale-date.r
- man/scale_date.Rd
This PR aims to fix #4199 by adding `oob` arguments to date and datetime position scales that are passed along to `ggplot2:::datetime_scale()`.
> Add `oob` arguments to date/datetime position scales.

- R/fortify.r
The error currently reads something like the following:
```
Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class uneval
Did you accidentally pass `aes()` to the `data` argument?
```
This PR adds a period at the end of the first sentence.
> Add missing period at the end of sentence

- .github/workflows/R-CMD-check.yaml
- tests/testthat/test-ggsave.R
All visual tests fail on R-devel with this error:
```
> test_check("ggplot2")
── 1. Error: aesthetics are drawn correctly (@test-aes.r#160)  ─────────────────
Graphics API version mismatch
Backtrace:
1. vdiffr::expect_doppelganger(...)
2. vdiffr:::writer(fig, testcase, title)
3. vdiffr:::svglite(file, user_fonts = get_aliases())
4. vdiffr:::svglite_(...)
```
(<https://github.com/tidyverse/ggplot2/pull/4227/checks?check_run_id=1239216870#step:10:132>)
I tried clearing cache, but it still failed. I bet this is because some binary on RStudio package manager is outdated. This might be solved by just waiting for some package to get rebuilt, but it kept failing at least for this 2 weeks, so I think there's little hope. This pull request removes RStudio Package Manager on R-devel runner and …
> Do not use RStudio Package Manager for R-devel

- R/save.r
- tests/testthat/test-ggsave.R
Fixes #4212. When the `plot.background` itself is NULL, `ggsave()` will set the device bg to `"transparent"`. This seems to work for devices that support transparent backgrounds. JPEGs and PDFs will have a white background, which seems ok.
> Fix saving plots with no background

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- NEWS.md
Fix #4247
digest package now requires R >= 3.3, and it seems there's no handy alternatives for it at the moment. We might eventually restore the support in future, but let's drop it for now.
> Drop support for R 3.2

- R/stat-smooth.r
- man/geom_smooth.Rd
It can be surprising that `span` argument has no effect when number of observations is large (cf. https://github.com/tidyverse/ggplot2/issues/3174).
> Clarify that span is only used for loess in stat_smooth

- R/data.R
- man/midwest.Rd
Attempts to address concerns and more in https://github.com/tidyverse/ggplot2/issues/4213
> Update documentation to midwest variables

- R/geom-polygon.r
Fix #4279
* Was incorrectly set to "NA"
> Fix geom_polygon default colour to NA (#4279)

- tests/testthat/test-facet-.r
(As probably some of you also got the email about this,) `all.equal()` now compares environments on R-devel. And actually the GitHub Action runner on R-devel kept failing from some days ago. This pull request fixes it by narrowing the comparing from the whole ggproto objects to only the meaningful elements.
Note that, this behavior is consistent with that of `expect_equal()` in testthat 3rd edition, which uses `waldo::compare()` and it has no option to ignore the environment generally. If we stick with 2nd edition, we can use `check.environment = FALSE` as a workaround, but probably we will want to move to 3rd edition at some point, so I didn't choose `check.environment`.
> Compare facet params instead of the whole objects in tests

- R/stat-summary.r
- man/mean_se.Rd
- man/stat_summary.Rd
Following [this gist](https://gist.github.com/hadley/fcfc99dc05478c8ab8e383223d56d099)  I discovered `mean_se`. However I think it is poorly documented.
Also the error is not informative if someone provides a vector for mult:
```r
x <- rnorm(100)
mean_se(x, mult = c(1, 2)
```
I open this draft PR to know if something like this would be welcomed.
> Describe what is ymin, ymax

- R/guides-.r
- R/labels.r
Fix #4237 
labs(x = "x", )
#> $x
#> [1] "x"
#> 
#> attr(,"class")
#> [1] "labels"
guides(x = "x", )
#> $x
#> [1] "x"
#> 
#> attr(,"class")
#> [1] "guides"
<sup>Created on 2020-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Allow trailing commas in guides() and labs()

- tests/testthat/helper-vdiffr.R
Fix #4293
At the time of implementing #4192, I was afraid that visual tests would be silently ignored on the CI (and we would oversight some bugs), so I chose the following logic:
* When vdiffr is not available, do raise an error unless `VDIFFR_RUN_TESTS` envvar is explicitly set to *`false`*
but this ends up failure on CRAN checks. So, this pull request toggle the logic to the following for safety. This should fix the CRAN checks.
* When vdiffr is not available, do NOT raise an error unless `VDIFFR_RUN_TESTS` envvar is explicitly set to *`true`*
> Toggle the logic of skipping visual tests

- DESCRIPTION
- NEWS.md
- R/coord-map.r
- R/fortify-map.r
- R/fortify.r
- R/stat-binhex.r
- R/stat-quantile.r
- R/stat-summary-hex.r
- R/stat-summary.r
- R/utilities.r
This PR replaces various `requireNamespace()` + `abort()` checks with the new rlang function `check_installed()`, which offers to install the suggested package then proceeds or aborts. This PR also bumps the rlang dependency to 0.4.10
I didn't use the `reason` argument in any `check_installed()` calls, which can add a bit of context. I'd be happy to add that, if desired.
Closes #4370, fixes #4344
> Use rlang::check_installed()

- R/coord-sf.R
Fix #4362
Currently, transformation is done by `sf::st_transform()` on the `sf` data, but in this case only the "active" geometry column is transformed, which is the intended behaviour (c.f., https://github.com/r-spatial/sf/issues/1620#issuecomment-790654565).
https://github.com/tidyverse/ggplot2/blob/4555055ce6e23e5b0630122fd9cc2aaf8cb1f91a/R/coord-sf.R#L55-L67
This pull request applies the transformation on all of the `sfc` columns in the data independently.
> Transform all the sfc columns independently

- NEWS.md
- R/facet-.r
- R/facet-grid-.r
- R/facet-wrap.r
Resolves #4379
Piping a plot into a `layer()` gives a helpful error with a hint:
``` r
ggplot(diamonds) %>% 
geom_point(aes(price, carat))
#> Error: `mapping` must be created by `aes()`
#> Did you use %>% instead of +?
```
This pull request adds this hint and better captures the error when piping into facets:
**Before**
``` r
library(magrittr)
ggplot(diamonds) %>% 
facet_grid(vars(cut))
#> Error: `rows` must be `NULL` or a `vars()` list if `cols` is a `vars()` list
ggplot(diamonds) %>% 
facet_grid()
#> <ggproto object: Class FacetGrid, Facet, gg>
#>     compute_layout: function
#>     draw_back: function
#>     draw_front: function
#>     draw_labels: function
#>     draw_panels: function
#>     finish_data: function
#>     init_scales: function
#>     map_data: function …
```
> Capture error with hint when piping plots into facets

- .github/workflows/pkgdown.yaml
- _pkgdown.yml
Fix  #4376
I'm not sure when the behaviour changed, but it seems pkgdown now requires to list all the topics in `structure`. At least this works fine on my forked repo:
https://yutannihilation.github.io/ggplot2/dev/
> Fix pkgdown navbar

- R/zxx.r
As per #1901: [“gray” is the predominant US spelling](https://www.merriam-webster.com/dictionary/gray). The purpose of this PR is to increase discoverability for en-US speakers as well as non-native English speakers whose first exposure is to US English spelling rather than UK/AU/NZ.
This PR keeps the existing, less common spelling `scale_color_grey` for backwards compatibility.
> Add missing US spellings for “scale_grey”

- NEWS.md
- R/guide-bins.R
Fix #4085
It seems we simply forgot to pass `override.aes` to the guide object. `guide_merge.bins()` and `guide_geom.bins()` seem to handle `override.aes()` properly.
``` r
ggplot(mtcars, aes(x = drat, y = wt, size = hp, fill = cyl)) + 
geom_point(shape = 21) + 
scale_size_binned(guide = guide_bins(override.aes = list(colour = "red", shape = 21, fill = "blue")))
```
<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Make guide_bins() respect override.aes

- R/facet-.r
- tests/testthat/test-facet-.r
Fix #4319 
This is a follow-up of #3162; at that time I considered only `NULL`, but probably missing arguments should be ignored as well. Here's the use case:
``` r
f <- function(facet) {
geom_point() +
facet_wrap(vars({{ facet }}))
}
f()
```
``` r
f(cyl)
```
<sup>Created on 2021-03-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
> Ignore missing facet specs

- NEWS.md
While this sentence is in the section of version 3.3.2 on NEWS.md, I believe #3659 is not released yet.
> * `coord_sf()` now has an argument `default_crs` that specifies the coordinate
reference system (CRS) for non-sf layers and scale/coord limits. ...snip...
Actually, the released NEWS doesn't this.
https://ggplot2.tidyverse.org/news/index.html
> Fix a NEWS item misplaced on version 3.3.2

- R/save.r
- man/ggsave.Rd
Currently the document says
> Can either be a device function (e.g. `png()`), or ...
but we cannot specify `png()`, but `png`. This seems slightly misleading.
c.f. https://github.com/tidyverse/ggplot2/issues/4347#issuecomment-800095723
> Show a function name instead of function call on ggsave's doc

- NEWS.md
- R/save.r
Implements #3379 so that ggsave returns the file (with path) of the plot.
> Adds return value for ggsave

- R/zxx.r
Closes #4148. 
Could be seen as a follow-up of sorts to #3833, which added the ability to configure qualitative (i.e., non-ordinal) colourscale defaults. This PR adds a similar ability to configure ordinal colourscale defaults via new `ggplot2.ordinal.{colour/fill}` options:
```r
p <- ggplot(diamonds, aes(price, colour = cut, fill = cut)) + geom_density()
p
```
```r
withr::with_options(
list(ggplot2.ordinal.fill = viridisLite::cividis(10)), p
)
```
> Allow scale_{colour/fill}_ordinal() to be configured via new ggplot2.ordinal.{colour/fill} global options. 

- .github/workflows/R-CMD-check.yaml
Ubuntu 16.04 reaches EOL in this April. I found r-lib/action moved to Ubuntu 18.04 at last (c.f. https://github.com/r-lib/actions/pull/257), so I think now it's time for this.
> Use Ubuntu 18.04

- NEWS.md
- R/position-jitter.r
Fix #2941 
This PR changes the jitter position implementation to calculate a jitter once for `x` and `y` and then apply that to all position aesthetics
> Make sure jitter is only calculated once

- NEWS.md
- R/position-dodge2.r
- tests/testthat/test-position-dodge2.R
Fix #2905
This fix catches rows with NA values and assigns them to a new group before they can cause error in the comparison
> Allow NA values in position_dodge2

- NEWS.md
- R/position-jitter.r
Fix #2507 
This PR implements @paleolimbot suggested fix. I think it is brittle to rely on calling the constructor, because it is also valid (but weird) to pass in PositionJitter directly
I think we should aim for all ggproto objects to be self-sufficient, i.e. have next to no logic in the constructors
> Move seed setup in `position_jitter()` to `setup_params()` from the constructor

- R/zxx.r
This reverts commit a8352072a048249224f6e517e817e6ac72477c47.
As discussed, adding the additional spelling is more trouble than it is worth so this PR reverts it
> Revert "Add missing US spellings for “scale_grey” (#4299)"

- NEWS.md
- R/quick-plot.r
Fix #4027 
This PR simply catches the case where the user supplies `c(NA, NA)` as limits and ignores it
> Only apply limits if they are not NA in plot

- NEWS.md
- R/labeller.r
Fix #4084 
There is one "issue" in that parsing is either, or. Right now it will re-add parsing if *any* label is an expression which could potentially lead to errors if there is a mix of expressions and not (I'm not sure if that is possible) and the non-expressions cannot be parsed...
Alternatively we could only do this if *all* labels are expressions...
``` r
library("ggplot2")
dat <- data.frame(x = 1, y = 1, a = "a", b = 1)
ggplot(dat, aes(x, y)) +
geom_point() +
facet_grid(
~ a + b,
labeller = labeller(
a = c("a" = "a^2"),
.default = label_parsed,
.multi_line = FALSE
)
)
```
<sup>Created on 2021-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> Make sure that expressions are reencoded as expressions when collapsed

- NEWS.md
- R/geom-abline.r
- tests/figs/geom-hline-vline-abline/cartesian-lines-intersect-mid-bars.svg
- tests/figs/geom-hline-vline-abline/flipped-lines-intersect-mid-bars.svg
Fix #4024
This PR only fixes the issue in `geom_abline()` leaving `geom_function()` as it is because it is not really feasible to fix it right now/for this
> Extent the range of `geom_abline()` outside the panel range

- NEWS.md
- R/guide-colorsteps.R
Fix #4019 
This PR fixes the issue with extended terminal bins in `guide_coloursteps()` by removing breaks if they coincide
> Fix extended bins in `guide_coloursteps()`

- NEWS.md
- R/ggplot-global.R
Fix #3741 
This makes `geom_abline()` react to y scale transformations so that intercept gets correctly transformed
> Add intercept to list of known y aesthetics

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/test-coverage.yaml
- DESCRIPTION
Fix #4424
Test build: https://github.com/yutannihilation/ggplot2/runs/2361972393
> [CI] Switch to pak

- R/stat-smooth-methods.r
Closes #3806
``` r
library(locfit)
#> locfit 1.5-9.4    2020-03-24
mtcars$x <- mtcars$disp
grid <- seq(71, 470, length.out = 100)
fit <- locfit::locfit(mpg ~ x, data = mtcars)
prd <- predict(fit, data.frame(x = grid), se.fit = TRUE)
resid_df <- fit$dp["df2"]
lower_95 <- prd$fit + qt(0.025, df = resid_df) * prd$se.fit
upper_95 <- prd$fit + qt(0.975, df = resid_df) * prd$se.fit
res_95 <- ggplot2:::predictdf(fit, xseq = grid, se = TRUE, level = 0.95)
all.equal(res_95$ymin, lower_95, tolerance = 0.0001)
#> [1] TRUE
all.equal(res_95$ymax, upper_95, tolerance = 0.0001)
#> [1] TRUE
lower_99 <- prd$fit + qt(0.005, df = resid_df) * prd$se.fit
upper_99 <- prd$fit + qt(0.995, df = resid_df) * prd$se.fit
res_99 <- ggplot2:::predictdf(fit, xseq = grid, se = TRUE, level = 0.99) …
```
> compute the correct interval for locfit smoothers 

- NEWS.md
- R/stat-bin2d.r
Fix #3824 
This PR fixes the reported bug by removing the last bin if it lies completely outside the the scale range
> Create the requested number of bins in `bin2d_breaks()`

- NEWS.md
- R/facet-grid-.r
Fix #3834 
This PR adds a check for when aspect ratio has been set by the theme and free space is requested in facet_grid and throws an error
> Throw error with illigal combination of space in facet_grid and aspect.ratio in theme

- NEWS.md
- R/scale-date.r
Fix #4007 
Currently the timezone argument in `scale_[x|y]_datetime()` is ignored. This PR rectifies that
> Construct time_trans with the given timezone

- NEWS.md
- R/scale-date.r
Fix #3965 
This PR implements a fix for the misalignment by calling `floor()` on the breaks returned in `get_breaks()`
> Round down breaks in scale_date to avoid misalignment

- NEWS.md
- R/axis-secondary.R
Fix #4368 
This PR implements the fix proposed by @yutannihilation in the issue
> Remove warning when creating secondary axis with no minor breaks

- NEWS.md
- R/plot-build.r
Fix #3635 
This PR aims to address the issue of correctly justifying legends if they are larger than the space available. It does so by setting the viewport size to the size of the legend...
re-rendering of the issue example to show it is working
``` r
library(magrittr)
p <- iris %>%
ggplot(
aes(x = Sepal.Length, 
y = Sepal.Width, 
color = Petal.Length, 
shape = Species, 
fill = Petal.Width)
) + 
geom_point() + 
theme(legend.position = "bottom")
p + theme(legend.justification = "left")
```
``` r
p + theme(legend.justification = "right")
```
<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
(@clauswilke I'm setting you as reviewer as I think you are the other person most familiar with the intricacies of grid. If you don't have …
> Allow justification of legends larger than the available space

- R/coord-flip.r
- tests/figs/test-coord-flip-r/turning-off-secondary-title-with-coord-flip.svg
- tests/testthat/test-coord-flip.R
Fix #4289 
This PR changes the order of calls in `labels()` to make sure that any guide_axis parts gets correctly applied
> Make sure guide_axis can modify labels in coord_flip

- tests/testthat/test-prohibited-functions.R
> Fix tests/testthat/test-prohibited-functions.R

- NEWS.md
- R/guide-bins.R
Fix #4210 
This fixes a bug when reversing the bin guide because the terminal row that held irrelevant `NA` values ended up as the first row
> Ensure all keys in `guide_bins(..., reverse = TRUE)`

- NEWS.md
- R/annotation-logticks.r
Fix #3954 
This PR ensures that `annotate_logticks()` works in the presence of `coord_flip()`. It does so by flipping around the ranges and aesthetic names.
Important notice: With this PR, `sides = "b"` will not get translated to `sides = "l"`. Since the `sides` argument is positional and not tied to aesthetic names it makes sense to me to leave it alone
> Make annotate_logticks coord_flip-aware

- tests/testthat/test-prohibited-functions.R
(Fix https://github.com/tidyverse/ggplot2/pull/4446#issuecomment-826799440)
Tests in `tests/testthat/test-prohibited-functions.R` needs to parse R files to do static analysis. But, files are not always available, so this test might fail and `covr::coverage()` is the case.
https://github.com/tidyverse/ggplot2/blob/bb8f960356a55fe2e72cfd0569179835818f00d8/tests/testthat/test-prohibited-functions.R#L49-L51
This pull requests let the test skip on `covr::coverage()`, and also on CRAN for safety.
> Fix failures on test coverage CI

- NEWS.md
- R/labeller.r
- tests/testthat/test-labellers.R
Fix #4141
This PR fixes `label_bquote()` so it can once again look up functions etc from the calling environment
> Give `label_bquote()` access to calling environment

- NEWS.md
- R/plot.r
> Add support for the BrailleR package

- R/scale-colour.r
- man/scale_colour_continuous.Rd
- tests/testthat/test-scale-colour-continuous.R
Addresses this comment: https://github.com/tidyverse/ggplot2/pull/4450#issuecomment-828231861
Reprex:
``` r
v <- ggplot(faithfuld, aes(waiting, eruptions, fill = density)) +
geom_tile()
options(ggplot2.continuous.fill = "viridis")
v
```
``` r
v + scale_fill_binned()
```
``` r
options(ggplot2.continuous.fill = scale_fill_viridis_c)
v
```
``` r
v + scale_fill_binned()
```
<sup>Created on 2021-04-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
> Don't switch scale type when using defaults

- NEWS.md
- R/scale-colour.r
- R/scale-hue.r
- man/scale_colour_discrete.Rd
- tests/testthat/test-scale-discrete.R
Fix #4149 
This PR removes the inheritance across fill/colour defaults in discrete scales making it behave as continuous and binned scales. It further adds type checking to default functions
> Add type checking to default discrete scales

- NEWS.md
- R/labeller.r
- R/scale-manual.r
- man/scale_manual.Rd
- tests/testthat/test-scale-manual.r
Fix #3451 
This PR relaxes the requirement on the manual scale `values` vector and allow it to contain fewer elements than the data. Non-existing values are implicitly considered `NA` and mapped to the `na.value` value
> allow fewer elements in named values vector in manual scales

- R/guide-bins.R
- R/guide-colorbar.r
- R/guide-legend.r
- R/guides-.r
- R/layer-sf.R
- R/layer.r
- tests/testthat/test-layer.r
This PR fixes the "statefulness" of the `mapping` field introduced in #4265 by aligning it with how we now treat `geom_params` and `stat_params`. In fact the state has existed since the introduction of `LayerSf` where the mapping would be modified to ensure the geometry was catched.
This clean-up leaves a couple of dangling issues, mainly the fact that `default_mapping` no longer needs to be passed around. It is kept as-is so we don't change the signature of the guide calculation and break extension packages. We can remove it entirely when we rewrite the guide functionality to ggproto
> Make sure `mapping` is not stateful

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- R/annotation-map.r
- R/coord-sf.R
- R/geom-sf.R
- man/annotation_map.Rd
- man/ggsf.Rd
- tests/figs/coord-sf/non-sf-geoms-using-long-lat.svg
- tests/figs/coord-sf/non-sf-geoms-using-projected-coords.svg
- tests/figs/deps.txt
- tests/testthat/test-coord_sf.R
Set `default_crs = NULL`, as discussed in #4494.
> Make coord_sf() default use projected coords

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- NEWS.md
* Use the dev version
* Revert the tweaked settings for GitHub Actions CI
* Add a note that `+ ggsave()` no longer works, fix #4513
> Followup after v3.3.4 release

- R/save.r
Fix #4521 
#4164 adds `bg` arg to `ggsave()`, but `grDevices::win.metafile()` is the exception in that it doesn't have `bg` argument. We need to absorb it in the wrapper function.
> Do not pass bg arg to grDevices::win.metafile()

- R/fortify-map.r
- man/borders.Rd
- man/map_data.Rd
Apologies for not testing building the package before submitting the pull request, but given that this only touches the function documentation text, I did not think it would be necessary.
> minor typos and formatting fixes in documentation

- NEWS.md
Just fixing a typo discovered when looking at this entry find out what was the reason for deprecation and whether there are some ramifications, so having a correct link might be helpful to others too (if you agree, please also consider updating it manually in the release notes on GitHub).
The correct issue is #4097 but #4094 was referenced in the changelog.
> Fix a typo in changelog (wrong issue number)

- .github/workflows/pkgdown.yaml
- _pkgdown.yml
Fix #4540
Currently the CRAN version of pkgdown seems to have a bug on linking topics. @maelle adviced me to use the dev version of pkgdown (c.f. https://github.com/r-lib/pkgdown/issues/1733), and I confirmed it works as expected on my forked repo: https://yutannihilation.github.io/ggplot2/dev/reference/theme.html
> Use the dev version of pkgdown

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/test-coverage.yaml
- R/geom-segment.r
- R/geom-sf.R
- README.Rmd
- README.md
- codecov.yml
- man/geom_segment.Rd
- man/ggsf.Rd
- tests/testthat/test-annotate.r
- tests/testthat/test-coord-map.R
- tests/testthat/test-geom-hline-vline-abline.R
This updates our CI scripts to the latest version, hopefully removing the need for continuous keeping up with best practices.
> Update to newest CI

- R/position-jitterdodge.R
- R/scale-brewer.r
- R/scale-hue.r
- R/scale-shape.r
- R/scale-viridis.r
- man/position_jitterdodge.Rd
- man/scale_brewer.Rd
- man/scale_hue.Rd
- man/scale_shape.Rd
- man/scale_viridis.Rd
This code is heavily used in our examples. Shouldn't we set a seed to make this deterministic?
```r
dsub <- diamonds[sample(nrow(diamonds), 1000), ]
```
> set.seed() before sample()

- NEWS.md
- R/geom-contour.r
- R/stat-contour.r
- man/geom_contour.Rd
- man/geom_density_2d.Rd
- tests/testthat/test-stat-contour.R
This is a refreshed version of #2320
``` r
v <- ggplot(faithfuld, aes(waiting, eruptions, z = density))
v + geom_contour(binwidth = 0.001)
```
``` r
my_breaks <- function(range, binwidth) {
b <- scales::fullseq(range, binwidth)
b[b != 0.002]  # remove the 0.002 contour
}
v + geom_contour(breaks = my_breaks, binwidth = 0.001)
```
<sup>Created on 2021-10-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
> Allows `breaks` to be a function in `geom_contour()`

- NEWS.md
- R/geom-sf.R
- tests/testthat/_snaps/geom-sf/north-carolina-county-boundaries-with-arrow.svg
- tests/testthat/_snaps/geom-sf/north-carolina-county-boundaries-with-more-than-one-arrow.svg
- tests/testthat/test-geom-sf.R
My vague recollection when I opened #4391, was I thought adding arrow was basically adding it to the list. As you can see from this commit it doesn't work. 
I expected the following to work, but no. 
````
library(sf)
coords <- tibble::tibble(lat = c(26.562855, 28.538336), 
lon = c(-81.949532, -81.379234)) %>%
st_as_sf(coords = c("lon", "lat"),  crs = 4326, remove = FALSE) %>%
st_coordinates() %>%
st_linestring()
ggplot() + 
geom_sf(data = coords, size = 2, 
arrow = arrow(angle = 45, ends = "last", type = "open", length = unit(0.5, "inches")))
````
I'm not sure I understand enough to complete this task
> Add arrow to line params

- R/geom-function.R
- man/geom_function.Rd
Output:
I believe this new example is useful because it might not be straightforward how to use the `fill` aesthetic with `geom_function()`/`stat_function()`.
My first try was to simply add `fill = "blue"` but it doesn't work because the `geom_line()` doesn't understand `fill`.
> Add example showing how to use the fill argument in stat_function()

- NEWS.md
- R/stat-bin2d.r
Fix #4646 - This PR adds a default value to the `weight` aesthetic ensuring that it doesn't emit a warning when given
> Make weight a recognised aesthetic in stat_bin_2d

- NEWS.md
- R/geom-point.r
Fix #4624 by treating ´NA` as `0` when calculating point size
> Don't allow stroke = NA to mess up point sizing

- NEWS.md
- R/guide-legend.r
- tests/testthat/test-guides.R
Fix #4559 
This is a simple fix that converts all instances of `NA` in the size aesthetic to `0`
> Convert size = NA to 0 before rendering guide_legend

- NEWS.md
- R/geom-.r
- R/layer.r
- tests/testthat/test-aes-setting.r
Fix #4588 
This PR allows mix of 0-length and 1-length vectors (recycled to 0) in aesthetics... It both puts ggplot2 in line with our decided recycling rules and makes it less error-prone to set aesthetics to scalars as these values can now be mixed with all sizes of data (even 0)
> follow tidyverse recycling rules for aesthetics

- NEWS.md
- R/facet-grid-.r
- tests/testthat/test-facet-strips.r
Fix #4610 
This PR adds the same type of check for presence of axis that happens in `facet_wrap()` to `facet_grid()` before adding padding between the strip and axis
> check if axis is present before adding padding to facet_grid

- NEWS.md
- R/scale-.r
Fix #4510 
This PR fixes a rare bug when the scale derives new limits to make the terminal bins equal size and these limits ends up being invalid for the given transformation (e.g. `log10`)
> Check if transformed limits in binning scales are valid before assigning them

- NEWS.md
- R/save.r
Fix #4539 
This PR make it so that only file _or_ filename is passed on as argument to the custom device
> Remove filename from the call to custom devices if file is present in the formals

- NEWS.md
- R/axis-secondary.R
Fix #4509 
This adds a simple check in secondary axes for whether there is any range available to make the monotonity check on
> Check for range == NULL - happens if no data has been added to plot

- NEWS.md
- R/geom-hex.r
- R/hexbin.R
- tests/testthat/_snaps/geom-hex/hex-bin-plot-in-polar-coordinates.svg
- tests/testthat/_snaps/geom-hex/hex-bin-plot-with-sqrt-transformed-y.svg
- tests/testthat/_snaps/geom-hex/single-hex-bin-with-width-and-height-of-0-1.svg
- tests/testthat/test-geom-hex.R
Fix #4580 
This PR makes `stat_bin_hex()` write `width` and `height` to the data which `geom_hex()` can pick up instead of deriving the resolution from data. This fixes issues with very sparse data where the bin resolution is not obvious from the bin centers
> Pass on binwidth and height to geom

- NEWS.md
- R/geom-tile.r
Fix #4495
Correctly declare min, xmax, ymin, and ymax as aes needing values
> Add non_missing_aes to geom_tile

- R/scale-discrete-.r
Fix #4746 
This PR should not affect anything at all, but prepare for the deprecation of `default.stringsAsFactors()` in the next major release of R
> remove stringsAsFactor for the mapped_discrete as.data.frame method

- NEWS.md
- R/geom-contour.r
- man/geom_contour.Rd
> Corrects bins / binwidth override documentation

- R/scale-identity.r
- man/scale_identity.Rd
Replace the old `coord_equal()` function, mentioned in the example code, with `coord_fixed()`
> Replace coord_equal in scale-identity.r

- NEWS.md
- R/geom-violin.r
- tests/testthat/test-geom-violin.R
Fix "collapsing to unique 'x' values" warnings. Closes #4455
A test will follow in a later commit.
> Fix warning in geom_violin with draw_quantiles

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- R/geom-contour.r
- man/geom_contour.Rd
Only needed for a single doc link? And requires RcppEigen which is having install problems.
> Don't install interp

- NEWS.md
- R/stat-smooth.r
- man/geom_smooth.Rd
Clearer documentation indicating that fullrange may extend beyond the data but does not fill the area created by expansion.
Docs regenerated by devtools::document() did create some warnings that are unrelated to these changes. Presumably known issues?
> Fixes #4399

- R/aes-evaluation.r
- R/stat-density.r
- man/aes_eval.Rd
- man/geom_density.Rd
Fixes #4476 by clarifying that n is a computed value of stat_density() that can is not available as original mapping in after_stat. Also wording better specifies that after_stat masks original mapping, but not variables in parent scope(s).
> Documentation clarifying stat_density/after_stat n

- R/aes.r
- R/utilities-tidy-eval.R
- man/aes.Rd
- man/aes_.Rd
- man/tidyeval.Rd
I noticed some documents about tidyeval are a bit out of date. This pull request is an attempt reflect some updates.
> Update docs related to tidyeval

- R/guide-legend.r
- man/guide_bins.Rd
- man/guide_colourbar.Rd
- man/guide_coloursteps.Rd
- man/guide_legend.Rd
> document default values for label justifications in guides

- R/ggproto.r
- R/layer-sf.R
- R/layer.r
- R/plot-build.r
- tests/testthat/_snaps/annotate.md
- tests/testthat/_snaps/geom-.md
- tests/testthat/_snaps/geom-dotplot.md
- tests/testthat/_snaps/geom-linerange.md
- tests/testthat/_snaps/geom-path.md
- tests/testthat/_snaps/geom-raster.md
- tests/testthat/_snaps/geom-ribbon.md
- tests/testthat/_snaps/geom-sf.md
- tests/testthat/_snaps/geom-violin.md
- tests/testthat/_snaps/guides.md
- tests/testthat/_snaps/layer.md
- tests/testthat/_snaps/position-jitterdodge.md
- tests/testthat/_snaps/stat-bin.md
- tests/testthat/_snaps/stat-boxplot.md
- tests/testthat/_snaps/stat-count.md
- tests/testthat/_snaps/stat-density.md
- tests/testthat/_snaps/stat-density2d.md
- tests/testthat/_snaps/stat-ecdf.md
- tests/testthat/_snaps/stat-qq.md
This PR improves the error reporting when errors occur during evaluations of a layer. It also adds an improvement to all errors in ggproto methods since the methods are now called by name so we avoid the useless `Error in f()` we get now.
The new look of layer errors is:
``` r
ggplot(economics_long, aes(date, value01, colour = date)) +
geom_point() + 
geom_line(linetype = 2)
#> Error in `geom_line(linetype = 2)`:
#> ! Problem converting geom to grob
#> ℹ Error occurred in the 2nd layer
#> Caused by error in `draw_panel()` at ggplot2/R/ggproto.r:179:18:
#> ! `geom_line()` can't have varying colour, size, and/or alpha along the line when
#>   linetype isn't solid
```
which is a mouthful but a huge improvement in terms of letting the user understand how their code is wrong
The remaining …
> Chained errors with contextual info in layers

- DESCRIPTION
- NEWS.md
- R/guide-bins.R
- R/guide-colorbar.r
- R/guide-colorsteps.R
- R/guide-legend.r
- R/guides-axis.r
- tests/testthat/_snaps/draw-key/horizontal-boxplot-and-crossbar.svg
- tests/testthat/_snaps/draw-key/horizontal-linerange-and-pointrange.svg
- tests/testthat/_snaps/draw-key/rectangle-and-dotplot-key-glyphs.svg
- tests/testthat/_snaps/draw-key/time-series-and-polygon-key-glyphs.svg
- tests/testthat/_snaps/guides.md
- tests/testthat/_snaps/guides/legend-inside-plot-bottom-left-of-legend-at-center.svg
- tests/testthat/_snaps/guides/legend-inside-plot-bottom-left.svg
- tests/testthat/_snaps/guides/legend-inside-plot-centered.svg
- tests/testthat/_snaps/guides/legend-inside-plot-top-right.svg
- tests/testthat/_snaps/guides/padding-in-legend-box.svg
Fix #4458 
This PR removes the digest dependencies in favour of `rlang::hash()`.
Since guides are sorted by their hash value and the hash value changes it can lead to changes in the automatic ordering of legends, as reflected in the change in visual tests. Since we make no promises on how they are sorted I think this is fine but should of course be communicated
> Use rlang::hash instead of digest

- R/coord-map.r
- R/geom-map.r
- man/coord_map.Rd
- man/geom_map.Rd
This fixes #3721. 
Marked as WIP as I want to give it one more careful review before I consider it final.
> Update documentation for geom_map()

- tests/testthat/_snaps/guides/guide-bins-understands-coinciding-limits-and-bins-3.svg
- tests/testthat/_snaps/guides/guide-colorsteps-understands-coinciding-limits-and-bins-3.svg
- tests/testthat/test-guides.R
> Shorten the titles of visual tests to suppress warnings

- R/geom-crossbar.r
- R/geom-pointrange.r
- R/geom-sf.R
- R/geom-smooth.r
Fix #4883 
``` r
ns <- asNamespace("ggplot2")
geoms_names <- ls(ns, pattern = "Geom.*")
geoms <- lapply(geoms_names, \(x) get(x, ns))
idx <- vapply(geoms, \(x) {
use_linewidth <- "linewidth" %in% x$aesthetics()
dont_rename_size <- !isTRUE(x$rename_size)
use_linewidth && dont_rename_size
}, logical(1L))
geoms_names[idx]
#> [1] "GeomCrossbar"   "GeomPointrange" "GeomSf"         "GeomSmooth"
```
<sup>Created on 2022-06-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
> Add rename_size=TRUE to GeomSf, GeomCrossbar, GeomPointrange, and GeomSmooth

- tests/testthat/test-geom-sf.R
It seems this currently errors because `sf::st_crs(nc)` returns `NA` (as `nc` is a sf**g** object, it doesn't have any CRS). This pull request just removes the line.
``` r
nc_tiny_coords <- data.frame(
x = c(-81.473, -81.741, -81.67, -81.345, -81.266, -81.24, -81.473),
y = c(36.234, 36.392, 36.59, 36.573, 36.437, 36.365, 36.234)
)
nc <- sf::st_linestring(
sf::st_coordinates(sf::st_as_sf(nc_tiny_coords, coords = c("x", "y"), crs = 4326))
)
nc2 <- sf::st_cast(
sf::st_sfc(
sf::st_multilinestring(lapply(
1:(length(sf::st_coordinates(nc)[, 1]) - 1),
function(x) rbind(
as.numeric(sf::st_coordinates(nc)[x, 1:2]),
as.numeric(sf::st_coordinates(nc)[x + 1, 1:2])
)
)
), sf::st_crs(nc)
), "LINESTRING"
)
#> Error in CPL_get_bbox(obj, 2): Not compatible with requested type: [type=character; …
```
> Fix a failing test on geom_sf()

- R/coord-polar.r
For unknown reason, `CoordPolar` has two `render_fg()`s. I just happened to find this, and found no clue on the context why this happened (it has had the two versions since 2015: https://github.com/tidyverse/ggplot2/commit/1487e0100515312b4ff2777163d09fdaf4f86655).
I think this is almost harmless, but this should be removed to avoid confusion. The code is already diverged a bit, but I believe the second is the one actually used (e.g. https://github.com/tidyverse/ggplot2/pull/4115 goes only to the second one), so I remove the first one.
> Remove duplicated CoordPolar$render_fg()

- R/save.r
A small followup of #4868.
I found this warning on our CI.
```
* checking R code for possible problems ... NOTE
Warning: Warning: <anonymous>: ... may be used in an incorrect context: ‘list(...)’ (/home/runner/work/ggplot2/ggplot2/check/ggplot2.Rcheck/00_pkg_src/ggplot2/R/save.r:176)
plot_dev: ... may be used in an incorrect context: ‘list(...)’
(/home/runner/work/ggplot2/ggplot2/check/ggplot2.Rcheck/00_pkg_src/ggplot2/R/save.r:176)
Warning: Warning: <anonymous>: ... may be used in an incorrect context: ‘list(...)’ (/home/runner/work/ggplot2/ggplot2/check/ggplot2.Rcheck/00_pkg_src/ggplot2/R/save.r:176)
```
Looking at the corresponding line before vctrs, I guess this was the intention.
https://github.com/tidyverse/ggplot2/blob/7571122f6a9455ccce9f8ceb9a2196c0a70be646/R/save.r#L176
> Fix a warning "... may be used in an incorrect context"

- R/facet-.r
- R/facet-grid-.r
- R/facet-wrap.r
- tests/testthat/_snaps/facet-layout.md
- tests/testthat/test-facet-layout.r
Fix #4138 
Provide meaningful error when using reserved names in faceting specs. Down the line we may want to explore removing the constraints altogether but for now a better error is all we need
> check the input faceting names

- R/position-dodge2.r
Fix #4327 
This PR fixes the bug that misplaced geom objects when they had zero width.
> fix misplacing points in position_dodge2

- NEWS.md
- R/position-jitter.r
Fix #4790 
This PR fixes a bug where infinity values were dropped in a jitter plot.
> fix dropping of inf values from jitter plot

- R/scale-view.r
Fix #4516.
This PR fixes the bug when `coord_cartesian()` has limits in descending order.
The issue and its solution are similar to issue #3952.
> fix dropping minor breaks

- vignettes/ggplot2-specs.Rmd
A followup of #3672
Just happened to find this still uses `size` for line width. This pull request replaces them with `linewidth` for consistency.
> Use linewidth in ggplot2-spec.Rmd

- R/geom-ribbon.r
- man/geom_ribbon.Rd
A followup of #4889. I think the document should have one or two examples to show how `stat_align()` works.
``` r
devtools::load_all("~/GitHub/ggplot2/")
g = c("a", "a", "a", "b", "b", "b"),
x = c(1, 3, 5, 2, 4, 6),
y = c(2, 5, 1, 3, 6, 7)
)
a <- ggplot(df, aes(x, y, fill = g)) +
geom_area()
a + geom_point(size = 8) + facet_grid(g ~ .)
```
``` r
a + geom_point(stat = "align", position = "stack", size = 8)
```
<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
> Add an example for stat_align()

- R/legend-draw.r
Address https://github.com/tidyverse/ggplot2/pull/4667#issuecomment-1210419214
``` r
devtools::load_all("~/GitHub/ggplot2/")
ggplot(mtcars, aes(wt, mpg)) + geom_point(aes(size = qsec), alpha = .5, stroke = NA)
```
<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
> Apply the same fix as #4667 to draw_key_point()

- R/geom-tile.r
- R/utilities-help.r
- man/geom_tile.Rd
Fix #3935
This pull request also adds `extra_note` argument to the internal function `rd_aesthetics`. I don't come up with particular issue other than #3935, but I expect some extra note will be useful in several places so I believe this is worth adding.
> Add a note that geom_raster() ignores `colour`

- R/geom-bar.r
- R/geom-col.r
> Add rename_size = TRUE to GeomBar

- R/annotation-map.r
- R/annotation.r
- R/fortify-lm.r
- R/geom-density2d.r
- R/geom-linerange.r
- R/geom-path.r
- R/geom-polygon.r
- R/geom-quantile.r
- R/geom-segment.r
- R/scale-linetype.r
- R/stat-summary.r
- man/annotate.Rd
- man/annotation_map.Rd
- man/fortify.lm.Rd
- man/geom_density_2d.Rd
- man/geom_linerange.Rd
- man/geom_path.Rd
- man/geom_polygon.Rd
- man/geom_quantile.Rd
- man/geom_segment.Rd
- man/scale_linetype.Rd
- man/stat_summary.Rd
During reviewing #4956, I found several examples still use `size` where it should be `linewidth`. This pull request mainly fixes it as well as
* Added `sf::` prefix to the examples in `annotation_map()`. These don't fail just because they are in dontrun.
* Fixed `annotation_map()`. It seems it was broken.
* Add a note that `pointrange()` also understands `size` aesthetics in actual.
> Use linewidth more

- R/theme-defaults.r
- R/theme-elements.r
- R/theme.r
- man/element.Rd
- man/theme.Rd
- tests/testthat/_snaps/theme.md
- tests/testthat/test-guides.R
- tests/testthat/test-scales-breaks-labels.r
- tests/testthat/test-theme.r
- vignettes/articles/faq-customising.Rmd
- vignettes/ggplot2-in-packages.Rmd
Fix #4953 
This fixes the oversight in the size to linewidth change in the element functions.
I believe I've fixed all instances of calls to the `element_*()` functions but please review carefully
> rename size -> linewidth in element_rect and element_line

- R/stat-.r
- tests/testthat/test-stats.r
Fix https://github.com/tidyverse/ggplot2/issues/4394
ggplot2 drops an aesthetic when the values are not constant within the group. Currently, this happens per group. Even when the dropping happens, if any of the groups still have the aesthetics, the result keeps the column because `vec_rbind()` kindly fills the mismatch with `NA`.
https://github.com/tidyverse/ggplot2/blob/10eba36a92f9a0f91a9a5a11b27f38fe7a2432ae/R/stat-.r#L133
This creates incomplete result like below. As discussed on #4394, this should drop the aesthetic instead of just showing a warning (which I tried in #4916).
``` r
d <- data.frame(
id = c("a", "a", "b", "b", "c"),
attr = 1:5
)
ggplot(d, aes(id, fill = attr)) +
geom_bar()
```
<sup>Created on 2022-07-27 by the [reprex …
> Drop non-constant aesthetics more thoroughly

- DESCRIPTION
- NEWS.md
- R/aes-evaluation.r
- R/layer.r
- tests/testthat/_snaps/aes-calculated.md
- tests/testthat/_snaps/layer.md
- tests/testthat/test-aes-calculated.r
- tests/testthat/test-geom-sf.R
- tests/testthat/test-layer.r
- tests/testthat/test-stat-contour.R
- tests/testthat/test-stat-sf-coordinates.R
Fix #3693
Considering the wide use of them, now I feel it's a bit difficult to deprecate them. Still, I think it's a good idea to issue a non-warning message at least because we want to advertise `after_stat()` more.
> Warn on the use of `..var..` and `stat(var)`

- R/plot-build.r
- tests/testthat/_snaps/layer.md
- tests/testthat/test-layer.r
@Hadley am I right in remembering that you ultimately didn't want the full call in the error message out of fear that it would be too long?
> Don't use I() to format the layer call

- R/geom-pointrange.r
- R/geom-sf.R
This PR partly reverses #4884 as the omission of `rename_size = TRUE` in geom_pointrange()` and `geom_sf()` was intentional since `size` remains a valid aesthetic.
> Remove rename_size = TRUE for sf and pointrange geoms

- R/geom-.r
The word 'aesthetic' is misspelled in the deprecation message issued by `check_linewidth()`. This PR fixes the typo.
> Correct spelling of 'aesthetic' in `check_linewidth()`

- NEWS.md
- R/ggplot-global.R
This PR attempts to fix #5051 based on @clauswilke's suggestion.
> Make `lwd` an alias for `linewidth`

- NEWS.md
- R/coord-.r
- tests/testthat/test-coord-.r
Fix #5063 
This fixes the names of aesthetics being dropped by `intersect()` by moving the assigning of names until after the `intersect()` call.
> Restore names of guides after setup_panel_guides()

- .github/workflows/R-CMD-check.yaml
- tests/testthat/test-geom-quantile.R
- tests/testthat/test-geom-smooth.R
Currently the CI fails with this error:
```
Error: 
! error in pak subprocess
Caused by error: 
! Cannot install packages:
* deps::.: Can't install dependency quantreg
* quantreg: Can't install dependency MatrixModels
* MatrixModels: Needs R >= 3.6.0
```
This pull request bumps the version of `ignore-before-r` for quantreg, and remove unnecessary `ignore-before-r` as the oldest one is now R 3.5.
Also, it seems `warnPartialMatchArgs` did not accept `FALSE` at the time of R 3.5. So this pull request skips the tests on R < 3.6.
```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error (???): geom_quantile matches quantile regression ──────────────────────
Error in `options(old_options)`: invalid value for 'warnPartialMatchArgs'
Backtrace:
▆
1. └─withr …
```
> Fix CI failures on oldrel-4 (i.e. R 3.5)

- R/scale-date.r
- man/scale_date.Rd
- tests/testthat/_snaps/scale_date/scale-x-date-breaks-breaks-width-2-weeks.svg
- tests/testthat/_snaps/scale_date/scale-y-date-breaks-breaks-width-2-weeks.svg
- tests/testthat/test-scale_date.R
This PR attempts to partially fix #4970. Moreover, it replaces using the `date_breaks()` function, which was retired >3 years ago in https://github.com/r-lib/scales/commit/1eb66ea1311ef5f7413e7aa2ae6928f92328f313 and superceded by `breaks_width()`. If the error message in #4970 needs to be improved, the {scales} package is the appropriate place for that.
> Date break doc improvement

- R/save.r
- tests/testthat/test-ggsave.R
This PR aims to fix #5048.
In brief, all units are written out in full in the error message (not just inches). Also, there was a possibility that the user could see a confusing error like this:
> "Dimensions exceed 50 inches (height and width are specified in pixels not pixels)."
Which is now being avoided by omitting the 'not pixels' ending of the error message.
> Write out units in full in `ggsave` error

- NEWS.md
- R/save.r
- tests/testthat/test-ggsave.R
This PR comes out of the discussion in #5114.
`ggsave()` gives some unhelpful error messages when the `filename` argument was inappropriate:
``` r
p <- ggplot(mtcars, aes(mpg, disp)) + geom_point()
filenames <- c("plot1.png", "plot2.png")
ggsave(filenames, p)
#> Error in `ggsave()`:
#> ! `device` must be "NULL", a string or a function.
ggsave(filenames, p, "png")
#> Saving 7 x 5 in image
#> Error in if (!dir.exists(dir)) {: the condition has length > 1
ggsave(character(), p, "png")
#> Saving 7 x 5 in image
#> Error in if (!dir.exists(dir)) {: argument is of length zero
```
With this PR:
``` r
ggsave(filenames, p)
#> Warning: `filename` must have length 1, not length 2.
#> ! Only the first, 'plot1.png', will be …
```
> Handle `filename` better in `ggsave()`

- R/stat-.r
- man/ggplot2-ggproto.Rd
I think that this is a typo in the documentation.  If not, then can the difference between `compute_panel` and `compute_panel_` please be clarified?
> Fix typo for `compute_panel_` to remove the trailing underscore

- R/geom-.r
Splitting a data frame according to a factor with one level will give a list with the data frame.
On layers with 1E7 data points, this `split` call costs 1.7 seconds out of the 18 seconds it currently takes me to build the plot. I intend to drive those 18 seconds to 6 seconds or less.
I have (maybe too extensively) documented my progress at:
- https://github.com/tidyverse/ggplot2/issues/4989
This is the second low hanging fruit after #4990.
Happy to further discuss this :smiley: 
Proposed NEWS entry (not added to avoid trivial conflicts)
```
* Performance improvement on plots without facets and lots of data
points (@zeehio, #4991)
``
> Performance: Avoid split.data.frame if there's only one panel

- R/stat-bin.r
This PR aims to fix #2756.
In brief, it removes a deprecation warning in `stat_bin()` for the `width` argument that has been deprecated 7 years ago. The deprecation warning that suggested `geom_bar()` was particularly confusing when using `geom_bar()` + `stat = "bin"`. It now just gives the usual 'Ignoring unknown parameters: `width`' message when used in combination with a geom that has no `width` parameter.
> stat_bin deals with `width` per usual

- R/scale-.r
- man/binned_scale.Rd
- man/scale_binned.Rd
- man/scale_steps.Rd
This PR aims to fix #5092.
Contains no code changes, just a documentation change.
> Fix `right` description in binned scales

- R/geom-ribbon.r
- man/geom_ribbon.Rd
This PR aims to fix #5026.
It tries to do so by being more clear in the documentation on how one can turn off the automatic alignment.
> Mention `stat = "identity"` in `geom_area()` docs

- R/plot.r
- man/ggplot.Rd
* changed "component" to "components"
* used "pattern" instead of "way" and "method"
* broke each pattern description in to separate paragraph used more explicit names in example code
* used more explicit data frame and variable names in example code
* added more explicit comments in example code
* removed error bars in last pattern of example code (and removed standard deviations from the summary stats calculated)
> Improve clarity of docstring for ggplot()

- R/geom-text.r
The placement of the text in the plot is slightly adjusted. The current placement is not very exact. c("bottom-left", "top-left", "bottom-right", "top-right", "center")
> Placement of text elements on the plot

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- R/geom-text.r
- tests/testthat/test-geom-text.R
This PR aims to fix #2757.
Briefly, it adds the angle to the non-missing aesthetics, causing the `GeomText$handle_na()` method to drop these observations with missing angles.
> `geom_text()` drops rows with `angle = NA`

- R/facet-grid-.r
- man/facet_grid.Rd
This PR aims to fix #5189.
Briefly, the `facet_grid(facets = ...)` argument has been silently and informally deprecated since ggplot2 2.2.0 based on the git blame. This PR uses the lifecycle deprecation system to also start emitting warnings. Example:
``` r
f <- facet_grid(facets = vars(cyl))
f <- facet_grid(facets = vars(cyl))
#> Warning: The `facets` argument of `facet_grid()` is deprecated as of ggplot2 2.2.0.
#> ℹ Please use the `rows` argument instead.
```
<sup>Created on 2023-02-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Deprecate `facets`

- R/aes.r
- R/facet-.r
- man/aes.Rd
- man/vars.Rd
This PR aims to fix #4998.
This simply reflects the docs of `?after_stat`: https://github.com/tidyverse/ggplot2/blob/2c5a78cbf1cbba8dac090dff4d7de467df6cb22b/R/aes-evaluation.r#L20
> Mark `aes()` and `vars()` as <data-masking>

- R/axis-secondary.R
- R/facet-.r
- R/guides-axis.r
- R/position-collide.r
- R/position-dodge.r
- R/position-jitterdodge.R
- R/stat-.r
- R/stat-align.R
- R/stat-boxplot.r
- R/stat-smooth.r
- R/stat-ydensity.r
- R/utilities.r
- tests/testthat/test-aes-grouping.r
- tests/testthat/test-facet-.r
I've noticed that `length(unique0(x))` is a common pattern in ggplot2 code. However, up to vectors with 1000 members, `vctrs::vec_unique_count()` seems to be faster (they perform about equal thereafter). For small vectors, the memory footprint is also better and about equal for larger vectors. The improvement is small, but the pattern is common enough that I thought this was warranted to save a few microseconds per plot.
A benchmark:
``` r
lengths <- 2^(0:24)
bms <- lapply(lengths, function(n) {
x <- sample(LETTERS, n, TRUE)
bench::mark(
length(unique0(x)),
vec_unique_count(x), 
iterations = 50
)
})
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> Warning: Some expressions had a GC in every …
```
> Peformance: vec_unique_count

- tests/testthat/test-ggsave.R
I think it's not strictly necessary for CRAN, but it is consistent with the rest of the suite.
(discovered because we run tests without local write permissions, this is the only test in the suite with this issue)
Also moved one test out of the `withr()` environment because it's independent of it, I think it's for the best.
> use tempfiles for plots

- R/aes.r
This PR aims to fix #5194.
Briefly, it updates the deprecation message to the following:
``` r
aes_string()
#> Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
#> ℹ Please use tidy evaluation idioms with `aes()`.
#> ℹ See also `vignette("ggplot2-in-packages")` for more information.
#> Aesthetic mapping: 
#> <empty>
```
<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Update `aes_string()` info bullets

- R/annotation.r
- R/compat-plyr.R
- R/geom-.r
- R/guide-bins.R
- R/guide-legend.r
- R/layer.r
- R/limits.r
- R/scale-.r
- R/scale-hue.r
- R/stat-summary-2d.r
- R/utilities.r
A common pattern in the codebase was to use `vapply(x, length, integer(1)` to get the length of every member in a list. That can be replaced by the consistently faster (and more readable) `lengths()` function. Overall, I don't think it makes a ton of difference, but may shave the occasional microsecond off a plot.
``` r
lengths <- 2^(0:20)
set.seed(42)
lens <- sample(0:1000, max(lengths), replace = TRUE)
my_list <- lapply(lens, rnorm)
bms <- lapply(lengths, function(n) {
x <- my_list[seq_len(n)]
bench::mark(
lengths(x),
vapply(x, length, integer(1)), 
iterations = 50
)
})
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
df <- do.call(rbind, bms)
df$n <- …
```
> Performance: use `lengths()`

- R/grob-dotstack.R
The `makeContext()` function in {grid} has only one argument: `x`.
The proposed change will remove the argument `recording` from `makeContext.dotstackGrob`, which didn't seem to be used anyway. 
This brings the method in line with the generic.
Tested on r-devel/4.3.0 on Windows
> Fix `makeContext.dotstackGrob()` method inconsistency

- NEWS.md
- R/annotation-logticks.R
This PR aims to fix #5229.
Briefly, it adds two checks to ensure the x/y range is finite before drawing ticks and erroring in the calculation.
> `annotation_logticks()` skips panels with non-finite range

- README.Rmd
- README.md
- vignettes/articles/faq-annotation.Rmd
- vignettes/articles/faq-axes.Rmd
- vignettes/articles/faq-bars.Rmd
- vignettes/articles/faq-customising.Rmd
- vignettes/articles/faq-faceting.Rmd
- vignettes/articles/faq-reordering.Rmd
- vignettes/extending-ggplot2.Rmd
- vignettes/ggplot2-specs.Rmd
This PR aims to fix #5222.
Briefly it adds alt text to plots in the readme, vignettes and articles. I tried to structure alt text for plots in the following way:
* What is being plotted?
* What are details of the plot we should pay attention to?
Because the docs are structured a lot along the lines 'here is a basic plot that we'll modify in various ways', a lot of repetition occurs in describing what is being plotted. I don't know if this repetition is preferred or not by the target audience of alt text. Instead of this repetition, one could alternatively describe 'as the previous plot, but with the following changes'.
> Alt text for documentation

- .github/workflows/R-CMD-check.yaml
Related: https://github.com/tidyverse/ggplot2/issues/5230
Now Hmisc cannot be installed on R < 4.1. This pull request make the CI ignore the installation failure on these old versions.
> Do not require Hmisc on the CI with R < 4.1

- DESCRIPTION
As I commented on https://github.com/tidyverse/ggplot2/issues/5230#issuecomment-1475221409, lattice used to be used for documenting how the users can migrate from lattice code to `qplot()` code, but the document was removed when we deprecated `qplot()` in https://github.com/tidyverse/ggplot2/pull/4079. So, it's used nowhere.
> Remove lattice from the dependency

- NEWS.md
- R/utilities-resolution.R
- tests/testthat/test-utilities.R
This PR aims to fix #5211.
It does so by having `resolution()` consider the `mapped_discrete` class as it does integers, where the resolution is set to 1.
I've added some tests so that it becomes easier to see if `resolution()` breaks in the future.
> `mapped_discrete` has resolution of 1

- R/facet-grid-.R
- tests/testthat/test-facet-strips.R
This PR aims to fix #5251.
In brief, whether strip padding was necessary depended on whether the size of the axis was 0. With this PR, that now depends on whether there is a relevant axis present. This fixes a problem with axis placement when the axis had acquired 0-size due to missing text and negative tick length (which begets the ticks a 0-size slot in the axis gtable for text alignment reasons).
Although, this example below might 'look' like there should be no padding between axis and strip, this behaviour is consistent with axes with normal dimensions.
``` r
facet_grid("foo" ~ drv, switch = "both") +
theme(
strip.placement = "outside",
axis.ticks.length = unit(-3, "pt"),
axis.text = …
```
> Negative tick strips

- NEWS.md
- R/annotation-logticks.R
This PR aims to fix #5248.
Briefly, it adds checks to ensure that there are ticks to be drawn before attempting to draw them.
> `annotation_logticks()` skips ticks it hasn't found

- R/theme-current.R
- tests/testthat/_snaps/theme.md
- tests/testthat/test-theme.R
This PR aims to fix #3117.
It adds a type check to `theme_set()`, that is all it does.
Examples (backtraces omitted):
``` r
theme_set(theme_bw())
theme_set(theme_bw)
#> Error in `theme_set()`:
#> ! `new` must be a <theme> object, not a function.
theme_set("foo")
#> Error in `theme_set()`:
#> ! `new` must be a <theme> object, not the string "foo".
```
<sup>Created on 2023-03-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Add type check to `theme_set()`

- R/geom-pointrange.R
This PR aims to fix #5261.
It now passes on the `na.rm` parameter to downstream drawing functions.
``` r
trt = factor(c(1, 1, 2, 2)),
resp = c(1, 5, 3, 4),
group = factor(c(1, 2, 1, 2)),
upper = c(1.1, NA_real_, 3.3, NA_real_),
lower = c(0.8, NA_real_, 2.4, NA_real_)
)
p <- ggplot(df, aes(trt, resp, colour = group))
p + geom_pointrange(aes(ymin = lower, ymax = upper), na.rm = FALSE)
#> Warning: Removed 2 rows containing missing values (`geom_segment()`).
```
``` r
p + geom_pointrange(aes(ymin = lower, ymax = upper), na.rm = TRUE)
```
<sup>Created on 2023-04-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> `geom_pointrange()` passes on `na.rm`

- R/geom-dotplot.R
- R/stat-bindot.R
- R/stat-ydensity.R
- man/geom_dotplot.Rd
This PR aims to fix #5263.
It continuous the saga of silencing dropped weight warnings, like #5071 and #5218 before it.
I also found `geom_dotplot()` to use a `weight` aesthetic, but it reports it doesn't and throws a warning about dropped weights when present. I fixed this by promoting it to a visible aesthetic and silencing the warning. In the example below, only the bin width warnings persist.
``` r
p <- ggplot(mtcars, aes(x = mpg))
p1 <- p + geom_dotplot(aes(weight = cyl))
#> Warning in geom_dotplot(aes(weight = cyl)): Ignoring unknown aesthetics: weight
p2 <- p + geom_dotplot()
patchwork::wrap_plots(p1, p2)
#> Bin width defaults to 1/30 of the range of the data. Pick better value with
#> `binwidth`.
#> Warning: The following aesthetics were dropped during statistical …
```
> Silence additional weight warnings

- R/geom-tile.R
- man/geom_tile.Rd
This PR aims to fix #5257.
It adds a details section to the documentation of `geom_tile()`/`geom_rect()` that mentions how the geoms respond to scale transformations.
> Add scale transformation note to `geom_tile()`/`geom_rect()`

- R/geom-abline.R
- R/geom-hline.R
- R/geom-vline.R
- R/layer.R
- tests/testthat/_snaps/layer.md
- tests/testthat/test-layer.R
This PR aims to fix #5253.
Briefly, it adds a warning when using an all-constant mapping in a layer:
``` r
p <- ggplot(mtcars, aes(x = 1)) +
geom_point(aes(y = 2))
b <- ggplot_build(p)
#> Warning: All aesthetics have length 1, but the data has 32 rows in `geom_point()`.
#> ℹ Did you mean to use `annotate()`?
```
It does take into account inherited aesthetics, so no warning is issued here:
``` r
p <- ggplot(mtcars, aes(x = seq_along(mpg))) +
geom_point(aes(y = 2))
b <- ggplot_build(p)
```
There is an ambiguous case where I was unsure a warning should be emitted. If a layer inherits an aesthetic that it does not use, should the warning been thrown for the aesthetics it does use?
``` r
p <- ggplot(mtcars, aes(label = cyl)) + …
```
> Warn when using constant aesthetics

- R/scale-.R
- tests/testthat/_snaps/scales.md
- tests/testthat/test-scales.R
This PR aims to fix #5271.
Briefly, `reciprocal_trans()`'s domains are [-Inf, Inf]. The reciprocal of this domain is [0,0]. The limits get squished to [0,0]. We cannot compute breaks on this. Hence, in this PR, we refuse to squish limits to zero-range domains. 
Moreover, it adds a series of tests for computing breaks with almost all transformd (boxcox is broken though), so we might see better when we might break a particular transfomation.
> Scales don't squish to zero-range domains

- tests/testthat/_snaps/theme/custom-strip-elements-can-render.svg
- tests/testthat/test-theme.R
It recently came to my attention in https://github.com/tidyverse/ggplot2/pull/5273#discussion_r1169222970 that a visual test wasn't testing what it should.
Briefly, the test is supposed to test whether custom `element_*()` classes can be drawn in strips. However, the `element_grob.element_test()` method wasn't recognised in the `expect_doppelganger()` test. This PR fixes the test by registering the method.
> Fix custom strip test

- R/geom-path.R
- R/geom-sf.R
- R/utilities.R
- tests/testthat/_snaps/geom-dotplot.md
- tests/testthat/_snaps/stat-boxplot.md
- tests/testthat/test-geom-bar.R
- tests/testthat/test-geom-col.R
- tests/testthat/test-geom-path.R
- tests/testthat/test-geom-sf.R
- tests/testthat/test-scales.R
This PR aims to fix #5250.
Briefly, it updates the warning message that is omitted by `Geom$handle_na()` and their kin to read:
```r
#> Warning message:
#> Removed 10 rows containing missing or excluded values (`stat_boxplot()`). 
```
Where the 'or excluded' is new. This is to better reflect that values might have been excluded by the out-of-bounds functions, in addition to being properly missing.
> Update missing value warning

- R/stat-density.R
- man/geom_density.Rd
- man/geom_violin.Rd
- tests/testthat/_snaps/stat-density.md
- tests/testthat/test-stat-density.R
This PR aims to prevent a newly introduced warning.
From the R4.3.0 [NEWS](https://cran.r-project.org/bin/windows/base/NEWS.R-4.3.0.html) bullets:
> density(x, weights = *) now warns if automatic bandwidth selection happens without using weights; new optional warnWbw may suppress the warning. Prompted by Christoph Dalitz' [PR#18490](https://bugs.r-project.org/show_bug.cgi?id=18490) and its discussants.
This affects ggplot2 when it uses weights:
``` r
cutoff <- min(mtcars$mpg)
p <- ggplot(mtcars, aes(mpg, weight = cyl)) +
stat_density()
invisible(ggplotGrob(p))
#> Warning in density.default(x, weights = w, bw = bw, adjust = adjust, kernel =
#> kernel, : Selecting bandwidth *not* using 'weights'
```
<sup>Created on 2023-04-22 with [reprex …
> Silence new `density()` warning

- R/plot-build.R
- tests/testthat/_snaps/theme.md
- tests/testthat/test-stat-summary.R
Before this PR
```r
ggplot() +theme(plot.title.position = "Null")
Error in `ggplot_gtable()`:
! `plot.title.position` should be either
"\"panel\"" or "\"plot\"".
```
With this PR
```r
ggplot() +theme(plot.title.position = "Null")
Error in `ggplot_gtable()` 
! `plot.title.position` should be either "panel" or "plot".
```
I wonder how we could better improve this message, so it becomes:
```r
ggplot() +theme(plot.title.position = "Null")
Error in `theme()` 
! `plot.title.position` should be either "panel" or "plot".
```
But I don't know how to do that.
Edit: I added suggestion to use `rlang::arg_match()` to get rid of the `if ()`, but this doesn't solve the error call.
> Improve error message when `plot.title.position` is not correctly mentioned.

- R/coord-cartesian-.R
- R/geom-tile.R
- R/guide-.R
- R/guide-colorsteps.R
- R/layer.R
- R/position-dodge.R
- R/scale-.R
- R/scale-brewer.R
- R/scale-colour.R
- R/scale-manual.R
- R/scale-viridis.R
- R/stat-contour.R
- R/stat-sf-coordinates.R
- R/utilities.R
- man/bidirection.Rd
- man/coord_cartesian.Rd
- man/geom_contour.Rd
- man/geom_tile.Rd
- man/ggplot2-ggproto.Rd
- man/guide_coloursteps.Rd
- man/layer.Rd
- man/new_guide.Rd
- man/position_dodge.Rd
- man/scale_brewer.Rd
- man/scale_colour_continuous.Rd
- man/scale_manual.Rd
- man/scale_viridis.Rd
- man/stat_sf_coordinates.Rd
This PR continues #5307, fixing typos in doc strings that needed to be re-documented.
> Fix typos part III

- NEWS.md
- R/coord-.R
- R/coord-cartesian-.R
- R/coord-fixed.R
- R/coord-flip.R
- R/coord-map.R
- R/coord-quickmap.R
- R/coord-sf.R
- R/coord-transform.R
- tests/testthat/_snaps/coord-cartesian.md
- tests/testthat/_snaps/coord-flip.md
- tests/testthat/_snaps/coord-map.md
- tests/testthat/_snaps/coord-transform.md
- tests/testthat/_snaps/coord_sf.md
- tests/testthat/test-coord-.R
- tests/testthat/test-coord-cartesian.R
- tests/testthat/test-coord-flip.R
- tests/testthat/test-coord-map.R
- tests/testthat/test-coord-transform.R
- tests/testthat/test-coord_sf.R
The original issue is that `coord-*` functions don't validate `xlim` and `ylim` arguments leading to confusing error output when these functions are called with bad arguments. See https://github.com/tidyverse/ggplot2/issues/4601 and https://github.com/tidyverse/ggplot2/issues/5297.
> Nicer error message in coord-* functions

- tests/testthat/helper-density.R
This PR aims to fix an issue with the visual tests on R devel.
Briefly, R [changed](https://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2023/05/03#n2023-05-03) the `density()` calculation, which means that visual tests of e.g. `geom_violin()` and `geom_density()` fail on R devel. The way this is resolved is by conditionally overriding the default density method to use the backward compatibility argument `old.coord`.
> Resolve R devel visual tests

- R/save.R
- man/ggsave.Rd
This PR aims to fix #5341.
Briefly, the old argument description was somewhat suggestive that `ggsave()`'s width and height arguments should be supplied as `grid::unit()` objects. This PR separates the description of width/height from the unit description to be more clear about the expected input.
In addition, it was suggested in https://github.com/tidyverse/ggplot2/issues/5323#issuecomment-1615228420 that the docs could clarify that the device may be guessed from the filename extension and that there was no example of passing device arguments through `...`. This is also included.
> Update `ggsave()`'s docs

- NEWS.md
- R/theme-elements.R
- tests/testthat/_snaps/labels.md
- tests/testthat/_snaps/theme.md
- tests/testthat/test-theme.R
This PR aims to fix #5369.
Briefly, in the element tree, some elements were expect to be `"numeric"`. In `inherits()`, this is interpreted as 'double', not 'integer or double' as one would expect in `is.numeric()`. This PR explicitly permits these elements to inherit from 'numeric' or 'integer'.
> Integers as valid input to theme

- R/scale-.R
- man/binned_scale.Rd
- man/continuous_scale.Rd
- man/scale_binned.Rd
- man/scale_continuous.Rd
- man/scale_gradient.Rd
- man/scale_linewidth.Rd
- man/scale_size.Rd
- man/scale_steps.Rd
This PR aims to fix #5359.
The scales documentation now mentions how to pass parameters to transformations fed into the `trans` argument.
> Passing parameters to `trans` argument

- NEWS.md
- R/backports.R
- tests/testthat/helper-density.R
Due to my fumbling git skills, this is the PR that #5367 should have been.
> Fix version comparison

- R/coord-cartesian-.R
- R/guide-.R
- R/guide-axis.R
- R/guide-bins.R
- R/guide-colorbar.R
- R/guide-colorsteps.R
- R/guide-legend.R
- R/guide-old.R
- R/guides-.R
- man/ggplot2-ggproto.Rd
- tests/testthat/test-guides.R
This PR aims to fix a series of backward compatibility issues that the `GuideOld` class didn't (perfectly) solve, in addition to a few polishes. It originates from a reverse dependency check which revealed what issues packages have with the guide system. This exercise has surfaced some problems that are being addressed in this PR. The main issues I have found are:
* The S3 guide extensions that relied upon S3 `NextMethod()` class inheritance. Since we've gutted these in ggplot2, we had anticipated that these needed to be reimplemented in the package extensions themselves. This is mostly handled in PRs towards these packages.
* We may have been too strict in letting `guides()` throw an error with empty or unnamed input. Some of the packages relied on `guides() == NULL`, which is now the …
> Miscellaneous improvements to guides

- R/stat-ydensity.R
This PR aims to fix #5374.
Briefly, it solves a partial matching bug that would accept `weights` as the `weight` aesthetic.
Specifying `weights` now just throws a warning, instead of being accidentally used as the `weight` aesthetic.
``` r
options(warnPartialMatchDollar = TRUE)
p <- ggplot(iris, aes(Species, Sepal.Width)) + 
geom_violin(aes(weights = Sepal.Length))
#> Warning in geom_violin(aes(weights = Sepal.Length)): Ignoring unknown
#> aesthetics: weights
```
<sup>Created on 2023-08-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Fix partial matching in `geom_violin()`

- NEWS.md
- R/guide-legend.R
- tests/testthat/_snaps/guides/enlarged-guides.svg
- tests/testthat/test-guides.R
This PR aims to fix #5160.
Briefly, key size is now determined by `size + linewidth` instead of just `size`.
> Consider `linewidth` in legend key sizes

- R/scale-brewer.R
- man/scale_brewer.Rd
Capturing in documentation that scale_*_distiller has a non-intuitive default direction = -1, and that to reverse, user needs to specify direction = 1
Source:
https://github.com/tidyverse/ggplot2/issues/1439
https://github.com/tidyverse/ggplot2/issues/4444
> Update documentation and example in scale-brewer.R to reflect scale_*_distiller's non-intuitive "direction"

- R/geom-boxplot.R
Testing out the new `lintr::length_test_linter()` (https://github.com/r-lib/lintr/pull/2124) came across this. I think the code does as intended "by accident", but it's better to use the "correct" code instead and not rely on some coercions producing the right answer incidentally.
> Correct length() usage in geom-boxplot

- NEWS.md
- R/stat-ydensity.R
- tests/testthat/test-stat-ydensity.R
This PR aims to fix #5396.
Briefly, `geom_violin()` calls `resolution()` to determine the default width of a violin. 
In `resolution()`, we're (correctly) making an exception for integers and 'mapped_discrete' vectors to have resolution 1.
However, the 'mapped_discrete' class got dropped from `data$x` due to a `mean()` operation.
In this PR, we skip the mean calculation when `data$x` only has 1 unique value, thereby preserving the 'mapped_discrete' class that gets forwarded to `resolution()`.
Small demo:
``` r
dplyr::filter(diamonds, cut %in% c("Ideal", "Good")) |>
ggplot(aes(price, cut)) +
geom_violin() +
scale_y_discrete(drop = FALSE)
```
<sup>Created on 2023-08-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Violin resolution

- _pkgdown.yml
A followup of #5159
cf. https://pkgdown.r-lib.org/reference/build_site.html#navigation-bar
> Add "Get started" section on the pkgdown site

- DESCRIPTION
As reported in #5421, ggplot2 now actually requires R >= 3.5 for rlang. Let's reflect it to the DESCRIPTION.
> Require R >= 3.5

- tests/testthat/test-annotate.R
Doing so makes tests less hermetic since `library()` has permanent side effects (of course, `loadNamespace()` does too, but generally less serious).
> Don't attach Suggests package in test

- NEWS.md
- R/labeller.R
- tests/testthat/test-labellers.R
This is an attempt to fix the issue https://github.com/tidyverse/ggplot2/issues/4599
> Improve labeller() behavior for lookup tables

- R/aes.R
- tests/testthat/test-aes.R
This PR aims to fix #5392. It calls `unrowname()` on the data before checking.
> Omit rownames from aesthetic usage check

- R/coord-sf.R
- R/guide-axis.R
This PR doesn't fix any issue, but it amends #5293.
I have become mildly frustrated by the lines below in the axis guide:
https://github.com/tidyverse/ggplot2/blob/69e74305386094cb1fc0b10495d18492cec5b012/R/guide-axis.R#L138-L141
Which I believe should be the coord's responsibility, not the axis' responsibility. This PR moves that ressponsibility from the axis to the coord.
> Move CRS responsibility from GuideAxis to CoordSf

- R/scale-continuous.R
- tests/testthat/test-scales.R
This PR aims to fix #5436.
Briefly, instead of checking if the calling function *is* a `scale_`-prefixed function, it checks if any component of the calling function is a `scale_`-prefixed function. Added some test for other tricky call situations as well.
> Scale call check

- R/coord-.R
- R/guides-.R
- tests/testthat/test-guides.R
This PR aims to fix #5425.
Briefly, when a scale had multiple aesthetics, the guide training could become asynchronous. This PR ensures that the guide training part receives the scales and aesthetics in a paired fashion, as to prevent this asynchrony.
> Guide training bugfix

- R/geom-label.R
The code in `geom_label()` should pass to `compute_just()` the same arguments that `geom_text()` passes, including both `x` and `y` and `angle` in each of the two calls, one for `hjust` and one for `vjust`. This affects the handling of `"inward"` and `"outward"` justification that depending on the angle require different numerical values for justification.
Reprex run AFTER applying this bug fix.
(There is a separate problem in `compute_just()`, affecting both geometries as `vjust` for the 90 degrees rotated text seems to be "outward" instead of "inward", while `hjust` is correct. I will try fix this separate problem and make a separate pull request in a few days.)
``` r
x = c(0, 0, 1, 1, 0.5),
y = c(0, 1, 0, 1, 0.5),
text = c("bottom-left", "top-left", …
```
> Bug-fix: text justification with rotation not implemented in `geom_label()` 

- NEWS.md
- R/guide-legend.R
- tests/testthat/_snaps/guides/left-aligned-legend-key.svg
- tests/testthat/test-guides.R
This PR aims to fix #3587.
Briefly, if the legend title produces a `<zeroGrob>` object, such as by setting `theme(legend.title = element_blank())`, it now no longer takes up space. This makes it easier to align legends to plot panels.
The implementation is pretty straightforward: all title-specific adjustments are made conditional.
> Absent legend titles take up no space

- NEWS.md
Fixes #5478. Change "the upcoming retirement of rproj, rgeos, and maptools" to "the upcoming retirement of rgdal, rgeos, and maptools"
> Fix Version 3.4.4 NEWS Typo

- R/annotation.R
- man/annotate.Rd
In `annotate`'s doc:
"You can use these geoms **directory** for annotations."
should read 
"You can use these geoms **directly**   for annotations."
> fix typo in doc

- NEWS.md
- R/geom-violin.R
- R/stat-ydensity.R
- man/geom_violin.Rd
Closes #5493
With this PR: 
``` r
set.seed(42)
data.frame(x = runif(9999)) |> 
ggplot(aes(1, x)) +
geom_violin(fill = NA, bounds = c(0, 1)) +
geom_violin(fill= NA, color = "red") +
coord_flip()
```
<sup>Created on 2023-10-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Adds `bounds` to `geom_violin()`

- R/scale-brewer.R
- man/scale_brewer.Rd
This PR fixes a NOTE in the CI:
```
❯ checking Rd line widths ... NOTE
Rd file 'scale_brewer.Rd':
\examples lines wider than 100 characters:
These lines will be truncated in the PDF manual.
```
This example was last updated in #5381
> Put linebreak in example of `scale_brewer`

- R/annotation-logticks.R
- R/axis-secondary.R
- R/coord-map.R
- R/fortify-map.R
- R/fortify.R
- R/scale-continuous.R
- R/scale-date.R
- R/stat-binhex.R
- R/stat-quantilemethods.R
- R/stat-summary-hex.R
- man/annotation_logticks.Rd
- man/scale_continuous.Rd
- man/sec_axis.Rd
- tests/testthat/test-guides.R
- tests/testthat/test-scale_date.R
- tests/testthat/test-scales-breaks-labels.R
Also added a period at the end of the `check_installed()` messages for consistency. https://style.tidyverse.org/error-messages.html
> Use `scales::label_*` over scales::*format()`

- R/guide-axis.R
I caught this testing ggnewscale. This is using the latest dev.
``` r
options(warnPartialMatchDollar = TRUE)
geom_point(aes(colour = factor(year)), size = 5) 
#> Warning in grobs$label: partial match of 'label' to 'labels'
#> Warning in grobs$label: partial match of 'label' to 'labels'
```
I think this is the correct change.
> Fixes partial matching on guides

- NAMESPACE
- R/theme.R
- tests/testthat/test-theme.R
This PR aims to fix #2724. It supersedes #5335.
Briefly, it implements https://github.com/tidyverse/ggplot2/issues/2724#issuecomment-401388408 by using `.subset2()` as the dollar-subsetting method for themes.
Quick demo:
``` r
t <- theme(foobar = 12)
t$foo
#> [1] 12
t$foobar
#> [1] 12
t$foo
#> NULL
t$foobar
#> [1] 12
```
<sup>Created on 2023-11-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> No partial matching in theme subsetting

- NEWS.md
- R/theme-defaults.R
- R/theme-elements.R
- tests/testthat/_snaps/guides/left-aligned-legend-key.svg
- tests/testthat/_snaps/theme/caption-aligned-to-entire-plot.svg
- tests/testthat/_snaps/theme/theme-classic-large.svg
- tests/testthat/_snaps/theme/theme-classic.svg
- tests/testthat/_snaps/theme/theme-gray-large.svg
- tests/testthat/_snaps/theme/theme-gray.svg
- tests/testthat/_snaps/theme/titles-aligned-to-entire-plot.svg
This PR aims to fix #5549.
Briefly, it sets `legend.key` to inherit from `panel.background` and eliminates the `legend.key` element from the built-in themes.
This causes the key backgrounds to automatically adhere to the panel background style.
``` r
geom_point(aes(shape = factor(cyl))) +
theme(
panel.background = element_rect(fill = "cornsilk")
)
```
<sup>Created on 2023-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
For many built-in themes, this was already achieved by encoding the `legend.key` element and `panel.background` seperately in the same style. With this PR, this doesn't need to happen seperately anymore.
However, because the default `theme_gray()` had a slightly …
> Key background inherits panel background

- NEWS.md
- R/stat-contour.R
This PR Closes #5555 (Huh, neat issue number!) 
With this PR:
``` r
options(OutDec= ",")
ggplot(faithfuld, aes(waiting, eruptions, z = density)) +
geom_contour_filled()
```
``` r
ggplot(faithfuld, aes(waiting, eruptions, z = density)) +
geom_contour(aes(color = after_stat(factor(level))))
```
<sup>Created on 2023-12-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Uses OutDec in isolines

- NEWS.md
- R/theme.R
- R/utilities.R
- man/theme.Rd
- tests/testthat/test-theme.R
This PR aims to fix #5542.
Briefly, `...` is moved to the first argument of the theme (which is technically a breaking change, I suppose), so that it can catch splicing operators. Then `find_args()`, which does the argument collection, just uses `list2()` to support the splicing.
Reprex from #5542:
``` r
red_axis <- list(
axis.line = element_line(colour = "red"),
axis.text = element_text(colour = "red"),
axis.ticks = element_line(colour = "red"),
axis.title = element_text(colour = "red")
)
geom_point() +
theme(!!!red_axis)
```
<sup>Created on 2023-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> `theme()` supports splicing arguments

- R/geom-segment.R
This PR aims to fix #5517.
`geom_segment()` no longer drops rows with missing `shape` aesthetic, as `shape` doesn't actually correspond to a property of the line that is being drawn.
Reprex from #5517:
``` r
x = 0, 
xend = 1, 
y = c(0, 1), 
yend = c(1, 0), 
shape = c("A", NA)
)
ggplot(df, aes(x, y, xend = xend, yend = yend)) +
geom_segment(aes(shape = shape))
#> Warning in geom_segment(aes(shape = shape)): Ignoring unknown aesthetics: shape
```
<sup>Created on 2023-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Remove `shape` as non-missing aes in `geom_segment()`

- R/utilities-checks.R
- man/check_device.Rd
This PR aims to implement https://github.com/tidyverse/ggplot2/pull/5299#issuecomment-1842747716.
Briefly, if there is no device open, the 'device' is the null device. When that is the device name, `maybe` is returned early.
> `check_device()`: Early exit for null device

- DESCRIPTION
- GOVERNANCE.md
Hi Team
Teun has been instrumental in many of the great things that has happened with ggplot2 in the last year or so. The next feature release is predominantly his work. I see it only fitting to include him as author together with the rest of us. Please approve this PR to show your support or discuss below
There will be a 3 weeks deadline beyond which silence is considered consent
> Add Teun as author

- R/guide-axis-theta.R
I apologise for not filing an issue first, but I ran into the following bug.
On the main branch, expressions aren't rendered properly with `guide_axis_theta()`. You can see in the example below, the subscript and superscript aren't drawn appropriately.
``` r
ggplot(data.frame(x = 1:2), aes(x, x)) +
geom_point() +
coord_radial() +
scale_x_continuous(
breaks = c(1.2, 1.8),
labels = expression(A^2, B[2])
)
```
<sup>Created on 2023-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
The same reprex with this PR draws them appropriately:
The implemented fix is easy: instead of taking the native labels as extracted from the scale, we use the `validate_labels()` function that handles expressions correctly.
> Fix `guide_axis_theta()` expression label bug

- NEWS.md
- R/scale-alpha.R
- R/scale-brewer.R
- R/scale-discrete-.R
- R/scale-gradient.R
- R/scale-grey.R
- R/scale-hue.R
- R/scale-identity.R
- R/scale-linetype.R
- R/scale-linewidth.R
- R/scale-manual.R
- R/scale-shape.R
- R/scale-size.R
- R/scale-steps.R
- R/scale-viridis.R
- R/zxx.R
- man/ggplot2-package.Rd
- man/scale_alpha.Rd
- man/scale_brewer.Rd
- man/scale_discrete.Rd
- man/scale_gradient.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_identity.Rd
- man/scale_linetype.Rd
- man/scale_shape.Rd
- man/scale_size.Rd
- man/scale_steps.Rd
- man/scale_viridis.Rd
- tests/testthat/test-scale-gradient.R
This PR aims to fix #5535.
Briefly, it explicitly sets the first argument of many scales to the `name` argument. Thereby, we're circumventing the issue that `...` would funnel the first argument to the deprecated `scale_name` argument.
> Scale name first

- vignettes/articles/faq-customising.Rmd
I think it's a common case that the user wants to customize both the size of theme and that of geoms. So, probably this FAQ should have some mention about the difference of the unit.
https://ggplot2.tidyverse.org/articles/faq-customising.html#fonts
> Add a minor note about the difference of the unit of size to FAQ

- R/legend-draw.R
This PR fixes a bug introduced in #5562.
Briefly, I forgot to set proper defaults for some values that would make `draw_key_text()` and `draw_key_label()` incompatible with non-text geoms. In this PR, these defaults are set, so you can mix the text key with a point layer, for example.
``` r
ggplot(mpg, aes(displ, hwy, colour = factor(cyl))) +
geom_point(key_glyph = "text")
```
``` r
ggplot(mpg, aes(displ, hwy, colour = factor(cyl))) +
geom_point(key_glyph = "label")
```
<sup>Created on 2023-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Set defaults in text based keys

- R/geom-.R
- R/layer.R
This PR to the RC branch aims to fix #5593.
Briefly, instead of coercing a plain pattern to a list in `Geom$use_defaults()`, it does so in the `layer()` function.
This has two consequences:
1.  Other internals, like `GuideLegend$get_layer_key()` or `Geom$use_defaults()` don't have to deal with plain patterns.
2. If a pattern is provided to another aesthetic than 'fill', it is also coerced to a list, opening up 'fill'-variant aesthetics for patterns. For example, a package might use a 'fill_box' aesthetic for a geom.
Reprex from #5593:
``` r
grad <- grid::linearGradient(pal_viridis()(10))
ggplot(mpg, aes(factor(cyl), colour = "fixed")) +
geom_bar(fill = grad)
```
<sup>Created on 2023-12-18 with [reprex …
> Ingest plain patterns as lists in `layer()`

- R/guide-axis-theta.R
- tests/testthat/_snaps/guides/guide-axis-theta-in-cartesian-coordinates.svg
This PR aims to fix a bug in GuideAxisTheta extensibility.
Briefly: measuring the grob directly makes more sense than measuring the grob's children when a theta axis is at a class left/right/top/bottom position.
Less briefly: at the time I wrote these lines of code, the labels were a grobTree with individual labels packed into its children. Since then, the label construction has been vectorised in d7e9a2dae2e77f6545a7de6edaaf005587bd599f, and I forgot to adjust the axis measurement code. The problem I ran into is that the code expects that `$children` is not NULL, whereas they might be. In addition, this brings the `guide_axis_theta()` behaviour closer to `guide_axis()` for non-polar coordinates in terms of spacing.
> Bugfix `guide_axis_theta()` label size

- R/coord-radial.R
This PR to the RC aims to fix #5599.
The reprex from that issue with correct label justification:
``` r
ggplot(mtcars, aes(x = seq_along(disp), y = disp)) +
geom_col() +
geom_text(aes(y = Inf, label = rownames(mtcars)), hjust = 1, angle = 90) +
coord_radial(rotate_angle = TRUE)
```
<sup>Created on 2023-12-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> flip justification along with angle

- R/guide-legend.R
This PR to the RC aims to fix a bug uncovered in revdepchecks affecting ~19 packages.
One such example is this:
https://github.com/tidyverse/ggplot2/blob/rc/3.5.0/revdep/problems.md#newly-broken-119
Briefly, `vec_in()` is too strict in that it cannot compare incompatible vectors, like `logical` and `character` vectors.
To reproduce this error, combine a logical and character level for the same aesthetic.
The fix is to replace `vec_in()` with `%in%`.
``` r
library(ggplot2) # RC branch
geom_point(aes(colour = hwy > 30)) +
geom_line(aes(colour = "foo"))
#> Error in `vec_in()` at ggplot2/R/guide-legend.R:727:5:
#> ! Can't combine <character> and <logical>.
```
How it should work:
```r
devtools::load_all("~/packages/ggplot2") # This PR …
```
> Swap `vec_in()` for `%in%`

- R/utilities.R
This PR to the RC aims to fix a bug uncovered in revdepchecks affecting ~32 packages.
One such example is this:
https://github.com/tidyverse/ggplot2/blob/rc/3.5.0/revdep/problems.md#newly-broken-126
Briefly, due to allowing splicing in `theme()`, we're no longer ignoring trailing arguments.
The fix is to explicitly ignore empty arguments using `dots_list()` instead of `list2()`.
A reprex to reproduce the issue:
``` r
library(ggplot2) # RC branch
theme(axis.title = element_text(), )
#> Error in `list2()` at ggplot2/R/utilities.R:323:3:
#> ! Argument 1 can't be empty.
```
Fixed behaviour:
``` r
devtools::load_all("~/packages/ggplot2/") # This PR
theme(axis.title = element_text(), )
#> List of 1
#>  $ axis.title:List of 11
#>   ..$ family       : NULL
#>   ..$ face …
```
> Ignore empty arguments in `theme()`

- R/guide-.R
- R/guide-legend.R
- R/theme.R
This PR to the RC aims to fix a bug uncovered in revdepchecks affecting ~28 packages.
One such example is this:
https://github.com/tidyverse/ggplot2/blob/rc/3.5.0/revdep/problems.md#newly-broken-21
Briefly, `title.position` gets partially matched to `legend.title` instead of `legend.title.position`.
The fix is not to use a `list()` as theme placeholder but an empty `theme()` (where we disallow partial matching).
A reprex to reproduce the issue:
``` r
library(ggplot2) # RC branch
guide_colourbar(title.position = "top")
#> Error in `mapply()` at ggplot2/R/theme.R:536:3:
#> ! The `legend.title` theme element must be a <element_text> object.
```
In addition, I found that the reported call for `mapply()` was uninformative, so I wired some calls to `validate_theme()`.
Now it reports the guide …
> Fix partial match in deprecated guide arguments

- R/guide-custom.R
- man/guide_custom.Rd
This PR to the RC aims to fix #5601.
Briefly, it applies the same refactoring in #5554 to `guide_custom()`.
Quick demonstration that the theme inheritance is correct: grey fill from guide's theme and blue outline from the plot's theme.
``` r
geom_point() +
guides(custom = guide_custom(
title = "My circle",
circleGrob(r = unit(1, "cm")),
theme = theme(legend.background = element_rect(fill = 'grey90'))
)) +
theme(legend.background = element_rect(colour = "blue"))
```
<sup>Created on 2023-12-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Guide custom theme

- R/scale-continuous.R
This PR to the RC aims to fix a bug uncovered in revdepchecks affecting ~44 packages.
One such example is this:
https://github.com/tidyverse/ggplot2/blob/rc/3.5.0/revdep/problems.md#newly-broken-29
Briefly, if a position scale is invoked in an non-standard way, where the first element of the call is not a name, it provoked an error.
To reproduce this error, the code below causes a function to be the scale's `call[[1]]`:
``` r
library(ggplot2) # RC branch
f <- function() {
geom_point() +
scale_y_continuous()
}
do.call(f, list())
#> Error in as.character(call[[1]]): cannot coerce type 'closure' to vector of type 'character'
```
This is now wrapped in a `try_fetch()` block so that this does not cause a failure. If `call[[1]]` is not coercible to a character, it …
> Protection for position scale's `call` parameter

- R/guide-axis-stack.R
The aims of this PR to the RC is to fix a bug found with the `spacing` argument in `guide_axis_stack()`.
Briefly, it is currently ignored because it isn't passed to `new_guide()`.
``` r
geom_point() +
guides(x = guide_axis_stack("axis", "axis", spacing = unit(1, "cm")))
```
With this PR, spacing is applied properly:
``` r
geom_point() +
guides(x = guide_axis_stack("axis", "axis", spacing = unit(1, "cm")))
```
<sup>Created on 2023-12-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Propogate `guide_axis_stack(spacing)` argument.

- R/geom-label.R
- R/geom-text.R
- R/legend-draw.R
- R/margins.R
This PR to the RC aims to fix #5614.
Briefly, the issue at hand is that the `draw_key_text()` and `draw_key_label()` functions did not know how to handle character-based justification such as `"right"` or `"outward"`.  This PR fixes that by resolving the justification through `compute_just()`.
As a related change, `rotate_just()` now also handles character justification.
The reprex from #5614:
``` r
mycars <- mtcars
mycars$name <- rownames(mycars)
ggplot(mycars, aes(wt, mpg, label = name)) +
geom_text(aes(size = wt), nudge_x = -0.1, hjust = "right")
```
<sup>Created on 2024-01-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Text key justification

- R/facet-grid-.R
As discussed internally, the order of strips and axes does not follow the `strip.placement` setting for empty axes. This is fixed with this PR
> adhere to strip placement even if the axis is empty

- R/geom-raster.R
This PR to the RC aims to fix a bug uncovered during reverse dependency checks.
When feeding continuous data to `geom_raster()` but using discrete scales confers the `mapped_discrete` class even upon the continuous data. We use the heuristic that `mapped_discrete` values have resolution 1 in https://github.com/tidyverse/ggplot2/pull/5247. This leads to problems in `geom_raster()`:
``` r
t <- c(0.1, 0.9, length.out = 2)
df <- expand.grid(c(0.1, 0.9), c(0.1, 0.9))
df$fill <- LETTERS[1:4]
ggplot(df, aes(Var1, Var2, fill = fill)) +
geom_raster() +
scale_x_discrete() +
scale_y_discrete()
```
In this PR, the data of `geom_raster()` is `unclass()`'ed so that `resolution` correctly pick up on its continuous nature:
``` r
#> ℹ Loading …
```
> Do not use class information for raster resolution calculation 

- R/scale-date.R
This PR to the RC aims to fix a bug uncovered during reverse dependency checks.
Briefly, in #5569 we moved the censoring of breaks from the scales to the guides.
`ScaleContinuousDate` was overlooked, since it didn't do the usual `scales::censor()`.
In turn, the scale could censor a break, which may result in mismatched labels/breaks.
In this PR, we remove the scale's censoring, because we handle that elsewhere now.
To reproduce issue with current RC:
``` r
limits <- as.Date(c("2000-01-01", "2010-01-01"))
df <- data.frame(x = limits, y = 1:2)
geom_point() +
scale_x_date(
breaks = as.Date(c("2000-01-01", "2011-01-01")), #2nd breaks is oob
labels = c("2000", "2011")
)
#> Error in `scale_x_date()`:
#> ! `breaks` and `labels` have different lengths.
``` …
> Do not censor date breaks

- R/axis-secondary.R
This PR to the RC aims to fix a reverse dependency check issue with `dup_axis()`.
Briefly: we renamed `trans` to `transform`, but kept the deprecated `trans` argument as the second argument.
Folks use position-based argument matching, so that the `trans` argument gets populated with what should go into the `name` argument. This PR restores the original order by putting the deprecated argument last.
> Put deprecated `trans` last in `dup_axis()`

- R/facet-grid-.R
- R/facet-wrap.R
This PR to the RC aims to fix an issue uncovered during reverse dependency checks.
Briefly, we introduced `axes` and `axis.labels` arguments in `facet_grid()` and `facet_wrap()`.
Extensions likely do not have these arguments forwarded to the facet's parameters and may be missing, causing errors in the panel drawing stage.
This PR fills these parameters when they are absent, so that extensions continue to work.
> Fill potentially missing arguments in facets

- R/geom-bar.R
This PR aims to fix #5632.
As the title suggests, this PR adds a `drop = TRUE` to a `split()` that could return a list with 0-length elements in it. With `drop = TRUE`, those 0-length elements are absent and the calculation proceeds without warnings.
> Drop empty groups from bar width calculation

- R/coord-munch.R
This PR to the RC aims to fix a bug uncovered during reverse dependency checks.
Briefly, for reasons beyond my understanding, `coord_munch()` might receive a very large segment, let's say `1e20` for `x` or `y`. It might then attempt to break up this large segment into many tiny pieces. You'd then get `failed to allocate vector of 7Gb` types of errors. Setting an upper limit on the number of pieces prevents this unreasonable demand on the machine's memory.
> Do not munch data too much

- R/guides-.R
- tests/testthat/test-guides.R
This PR to the RC aims to fix a bug uncovered during reverse dependency checks.
Briefly, in some unnatural circumstances you can create a guide that survives all steps but decides to draw a `zeroGrob()`.
`Guides$package_box()` cannot estimate the gtable size of these guides.
``` r
ggplot(mpg[1:2, ], aes(displ, cty, colour = c(1, 4))) +
geom_point() +
scale_colour_continuous(
limits = c(2.4, 2.6), breaks = c(1, 4),
guide = "legend"
)
#> Error in upgradeUnit.default(x): Not a unit object
```
<sup>Created on 2024-01-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
The solution in this PR is to drop empty guides at the `Guides$draw()` step. The reason we might not want to censor guides as soon as we detect the key is empty, is because some (extension) guides might …
> Drop `zeroGrob()` guides

- R/scale-.R
This PR to the RC aims to fix a bug found in reverse dependency checks.
Briefly, people can implement custom versions of the `scales::ContinuousRange` and `scales::DiscreteRange` classes.
We should only throw errors if the `range` object is of the expected class.
> Be more conservative in throwing scale training error

- R/geom-.R
- tests/testthat/test-geom-smooth.R
- tests/testthat/test-layer.R
This PR to the RC aims to fix #5656.
Briefly, using ``base::`<-.data.frame` `` in `Geom$use_defaults()` causes classes to be stripped on the RHS of the assignment.
This PR uses `vec_cbind()` to do the same job without stripping classes.
I encountered some reordered rownames during a test, but as these are not important in ggplot2, I'm not concerned.
> Don't strip classes in `Geom$use_defaults()`

- R/guide-.R
- R/guide-axis-theta.R
- R/guide-axis.R
- R/guide-legend.R
- tests/testthat/_snaps/guides/legend-byrow-true.svg
- tests/testthat/test-guides.R
This PR to the RC aims to fix #5661.
Briefly the `legend.byrow` setting wasn't working because the code assumed it was in `params` whereas we swapped it to `elements` later. 
This made me realise that `Guide$arrange_layout()` needed access to the `elements` (instead of sneakily passing it through `size` ), so this PR also adds `elements` as an argument. 
I was also surprised that there was no test for the `legend.byrow` setting, so I added one.
> Restore `legend.byrow`

- R/guide-colorbar.R
This PR to the RC solves a reverse dependency issue.
Briefly, if scale limits are set to e.g. `c(0, NA)`, but all values are `NA`, the limits never get updated to finite values, causing a problem for the colourbar. This PR intercepts such problems by discarding colourbars that have 0 breaks.
> Discard empty colourbars

- R/geom-.R
This PR to the RC aims to fix a revdep bug.
Briefly, in #5657, we used `vec_cbind()` to preserve AsIs vectors. However, {vctrs} does not treat expressions as vectors. Any geom declaring an expression outside of `aes()` would fail. This PR restores the old subassignment method, but instead explicitly restores AsIs vectors.
> Revert #5657

- vignettes/extending-ggplot2.Rmd
This PR adds a section to the 'Extending ggplot2' vignette about making guide extensions.
The content was mostly lifted from the putative blog post about the new release.
We can then just link to the relevant section of the vignette in the release blog.
> Vignette section about guide extension

- R/scale-alpha.R
- man/scale_alpha.Rd
This PR aims to fix #2865.
Rendered examples:
``` r
geom_point(aes(alpha = year))
p
```
``` r
p + scale_alpha(range = c(0, 1))
```
``` r
p + scale_alpha("cylinders")
```
<sup>Created on 2024-02-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
> Update `scale_alpha()` examples

- R/geom-function.R
- man/geom_function.Rd
This PR aims to fix #3181.
Briefly, it comments out various options of providing the function to `geom_function()`. I didn't find the duplicated examples for facets mentioned in #3181, so I think removing the duplicates for `geom_functino()` suffices.
> Deduplicate `geom_function()` examples

- R/scale-.R
- man/binned_scale.Rd
- man/continuous_scale.Rd
- man/scale_binned.Rd
- man/scale_continuous.Rd
- man/scale_gradient.Rd
- man/scale_linewidth.Rd
- man/scale_size.Rd
- man/scale_steps.Rd
This PR aims to fix #3445.
It simply adds a line to the function option for breaks that position scales get expanded limits. Since discrete scales document their own `breaks` param, this should only appear in continuous and binned scales.
> Clarify that limits are given after expansion

- R/guide-legend.R
This PR aims to fix #5738.
Briefly, when `theme(text = element_blank())`, it has no margin. This messes up some assumptions made in the legend that it would have a margin. In this PR, we just use 0-margins when this occurs.
> Deal with `NULL` margins in legend

- R/scale-.R
- man/discrete_scale.Rd
- man/scale_discrete.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_linetype.Rd
- man/scale_manual.Rd
- man/scale_shape.Rd
This PR aims to fix #5715.
It adjust the parameter documentation for `discrete_scale(drop)`, to point out that layers should set `show.legend = TRUE` if one aims to display all legend items.
> Add note on `scale_*_discrete(drop)` and legend interaction

- vignettes/ggplot2-in-packages.Rmd
This PR aims to fix #5181.
The surrounding text in the current vignette already covers to the surrounding text proposed in #5181, so I interpreted the issue as a request to include examples for facets. That is what this PR adds.
> Add facet examples to programming vignette

- R/scale-manual.R
- man/scale_manual.Rd
This PR aims to fix #5625.
It just removes `palette` from the documentation that `scale_{aes}_manual()` inherits from `discrete_scale()`.
> Remove `palette` from manual scale docs

- R/axis-secondary.R
- man/sec_axis.Rd
- tests/testthat/_snaps/sec-axis.md
This PR aims to fix #5579.
Briefly, the error mentions that the transformation must be strictly monotonic, as well as the docs.
> Mention secondary transformation must be *strictly* monotonic

- R/scale-gradient.R
- R/scale-grey.R
- R/scale-hue.R
- R/scale-size.R
- R/scale-steps.R
- man/scale_gradient.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_size.Rd
- man/scale_steps.Rd
This PR aims to fix #5698.
Briefly, through `@inheritDotParams`, some non-position scales inherited the documentation for the `expand` and `position` arguments that only work for position scales. This PR removes these.
> Remove `expand` and `position` from non-position scale docs

- NEWS.md
- R/annotation.R
- tests/testthat/_snaps/annotate.md
- tests/testthat/test-annotate.R
This PR aims to fix #5151.
Briefly, `annotate()` is hardcoded to use `StatIdentity` and `PositionIdentity` so any `stat` or `position` argument to `annotate()` ends up in the `params` to the layer. This PR warns about such cases and pre-emptively removes these arguments.
Demo:
``` r
geom_point() +
annotate(
"point", x = 3, y = 40,
position = position_jitter()
)
#> Warning: `annotate()` can't accept `position` argument.
```
<sup>Created on 2024-03-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
> `annotate()` gives warning when passing `position` or `stat`

- R/stat-summary-bin.R
- man/stat_summary.Rd
This PR aims to fix #3480.
Briefly, `stat_summary_bin()` inherits documentation from `stat_bin()`, but doesn't have `boundary` or `center`.
This PR removes the mention of these arguments from the docs, preventing confusion demonstrated in #3480.
> Redocument `stat_summary_bin()`'s  `breaks` argument.

- DESCRIPTION
This PR aims to fix #5810.
Briefly, `vec_run_sizes()` was introduced in {vctrs} 0.6.0 and we use it in ggplot2, so we should require at least that version of vctrs.
> Bump vctrs version

- R/geom-blank.R
This PR aims to fix #5772.
It uses the mechanism we included to opt-out of the warning.
> Silence length 1 aesthetics warning for `geom_blank()`

- R/theme.R
- man/theme.Rd
This PR aims to fix #5766.
Briefly, one example used the old (pre-3.5.0) way of setting a legend inside the panel bounds. This PR updates that example.
> Update example in `theme()` documentation

- NEWS.md
- R/guide-bins.R
- R/guide-colorsteps.R
- tests/testthat/test-guides.R
This PR aims to fix #3877.
Briefly, when binning is done outside the scale with `cut()`, the coloursteps guide understood how to display this, but couldn't display this with uneven steps. This PR makes the guide work with uneven steps.
Reprex from the linked issue:
``` r
mtcars |>
transform(mpg_cut = cut(mpg, c(seq(10, 25, 5), 35))) |>
ggplot(aes(hp, mpg, color = mpg_cut)) +
geom_point() +
guides(color = guide_colorsteps(show.limits = TRUE, even.steps = FALSE))
```
<sup>Created on 2024-03-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
@thomasp85 mentioned why this was unsupported before [here](https://github.com/tidyverse/ggplot2/issues/3877#issuecomment-597047227), but I didn't figure out why it was unsupported.
> `guide_coloursteps(even.steps = FALSE)` works with discrete data

- R/layer.R
- tests/testthat/_snaps/layer.md
This PR aims to fix #5762.
Briefly, it updates a warning that lead to some confusion based on a suggestion by Claus.
> Update aesthetics of length 1 warning

- R/theme.R
This PR aims to fix a revdep failure reported in #5822.
Subsetting a theme drops the <theme> class:
``` r
class(theme())
#> [1] "theme" "gg"
class(theme()[])
#> [1] "list"
```
<sup>Created on 2024-04-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
We subsetted the theme in #5743 to drop unknown elements, but an extension (mine, guilty as charged) relied on classed behaviour of theme settings (invoking `add_theme()` via `+`). This PR replaced the subsetting operation with assigning `NULL` to unknown theme settings, preserving the <theme> class.
> Preserve theme class

- NEWS.md
- R/geom-defaults.R
- man/update_defaults.Rd
- tests/testthat/test-geom-.R
This PR reverts #5781 in the prep/3.5.1 branch.
Briefly, #5781 was giving some grief with reverse dependencies so this PR allows us to postpone #5781 to a later release.
> Roll back updates to `update_geom/stat_defaults()`

- R/geom-point.R
- man/geom_point.Rd
- vignettes/ggplot2-specs.Rmd
This PR aims to fix #4358.
It just rephrases a sentence in the vignette and adds a note to the `geom_point()` aesthetics section.
> Be clearer when the `fill` aesthetic applies in points

- R/save.R
- man/ggsave.Rd
This PR aims to fix #5497.
Briefly, `dpi` is applied when units are specified in pixels, not *just* for raster output types.
This edits the description to clarify this.
> Clarify when `dpi` applies in `ggsave()`

- .github/workflows/R-CMD-check.yaml
It seems the latest version of quantreg requires very new Matrix package. We can ignore the error.
e.g. https://github.com/tidyverse/ggplot2/actions/runs/9044818946/job/24853881196#step:5:167
```
Error: 
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* deps::.: Can't install dependency quantreg
* quantreg: Can't install dependency MatrixModels
* MatrixModels: Can't install dependency Matrix (>= 1.6-0)
* Matrix: Needs R >= 4.5
* Matrix: Needs R >= 4.4.0
* any::sessioninfo: dependency conflict
* any::rcmdcheck: dependency conflict
```
> Fix CI failure by ignoring quantreg

- .github/workflows/R-CMD-check.yaml
Now that `oldrel-4` refers to R 4.0, I think this dedicated case for R 3.6 can be removed.
> Stop CI on R 3.6

- R/ggproto.R
This PR aims to fix #5722.
Briefly, it implements a wrapper for `debug()`, `debugonce()` and `undebug()` for ggproto methods.
These can't be debugged in a typical fashion as the relevant functions are wrapped in `<ggproto_method>` classes.
Therefore, we need to extract the relevant function to debug from the method's environment.
A few open ends:
* The debugger isn't exported, but should it?
* I have no idea how to write a test for this.
Not really a great reprex as this is mostly for interactive use, but just showing that the debugger can be activated:
``` r
geom_point()
ggproto_debug(GeomPoint$draw_panel)
p
```
```r
#> debugging in: draw_panel(..., self = self)
#> debug at …
```
> Debugger for ggproto methods

- R/aes-position.R
- man/aes_position.Rd
This PR aims to fix #5813.
Briefly, it does as the title indicates in the `?aes_position` documentation.
If there is a better wording for this, I'll be glad to adapt this PR.
> Add section about width/height

- R/theme.R
- man/theme.Rd
This PR aims to fix #4196.
It just lists `"centre"`/`"center"` as an option, which was already accepted, just not documented as such.
> List `"centre"` as option for `legend.box.just`

- NEWS.md
- R/geom-.R
- R/guide-legend.R
- R/layer.R
- tests/testthat/test-aes-calculated.R
This PR aims to fix #5901.
Briefly, when `after_stat()` or `after_scale()` produce aesthetics of the wrong length, a warning is thrown that the function could not be applied.
The reprex from the issue now renders with a warning:
``` r
ggplot(mpg[15:16, ], aes(displ, hwy)) +
geom_point(
aes(colour = after_scale(c("red", "green", "blue")))
)
#> Warning: Failed to apply `after_scale()` for the following aesthetic: colour.
```
<sup>Created on 2024-05-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
I have an alternate agenda with this PR.
Moving this check into `Geom$use_defaults()` frees us from having to do so in the legend code, allowing a simplification I ultimately need for #5833.
> `after_*()` length checks

- R/scale-gradient.R
- man/scale_gradient.Rd
This PR aims to fix #3738 and replaces #5824.
Briefly, an example is included to use the `rescaler` argument to center a custom divergent scale.
The example rendered:
``` r
set.seed(1)
x = runif(100),
y = runif(100),
z1 = rnorm(100),
z2 = abs(rnorm(100))
)
geom_point(aes(colour = z1)) +
scale_colour_gradientn(
colours = c("blue", "dodgerblue", "white", "orange", "red"),
rescaler = ~ scales::rescale_mid(.x, mid = 0)
)
```
<sup>Created on 2024-05-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
> Add gradient midpoint example

- R/geom-.R
- R/geom-sf.R
- R/guide-legend.R
- R/layer-sf.R
- R/layer.R
- tests/testthat/_snaps/geom-sf/geom-sf-line-legend.svg
- tests/testthat/_snaps/geom-sf/geom-sf-point-legend.svg
- tests/testthat/_snaps/geom-sf/geom-sf-polygon-legend.svg
- tests/testthat/test-geom-sf.R
- tests/testthat/test-guides.R
This PR is an amendment to #5834, as it didn't handle the non-standard defaults for `geom_sf()` legends.
Briefly, this PR let's `Layer$compute_geom_2()` instead of `Geom$use_defaults()` handle populating legend keys with defaults.
The legend code was mirroring `Layer$compute_geom_2()` in many ways anyway, so this shouldn't be much of a stretch.
This ensures that the layer could impose some of its non-aesthetic parameters on the legend keys.
That is needed to resolve the defaults for the correct legend type in `geom_sf()`, which we'd need for #5833.
In addition the following changes are made:
* `Layer$compute_geom_2()` now accepts a custom `params` object, as legends only pass static aesthetics when they are of length 1.
* The sf legend detection mechanism has moved from …
> Let `Layer$compute_geom_2()` handle legend defaults

- NEWS.md
- R/facet-wrap.R
- tests/testthat/test-facet-.R
This PR aims to fix #5898 and replaces #5900.
Briefly, it is not `as.table` that we need to preserve, but old-style `dir = 'h'/'v'` need to be translated.
This PR has a fallback for these old options and soft-deprecates their use.
Developers might see the following in their testthat runs:
``` r
library(deeptime)
options(lifecycle_verbosity = "warning")
df <- data.frame(x = 1:10, y = 1:10, period = c("Permian", "Triassic"))
ggplot(df) +
geom_point(aes(x, y)) +
facet_wrap_color(vars(period), colors = periods)
#> Warning: Internal use of `dir = "h"` and `dir = "v"` in `facet_wrap()` was deprecated in
#> ggplot2 3.5.2.
#> ℹ The `dir` argument should incorporate the `as.table` argument.
#> ℹ Falling back to `dir = "lt"`.
#> Call …
```
> Fallback for `dir = 'h'/'v'`

- NEWS.md
- R/position-jitterdodge.R
- tests/testthat/_snaps/position-jitterdodge.md
- tests/testthat/test-position-jitterdodge.R
This PR aims to fix #3656.
Briefly, instead of dodging by a set of aesthetics, it uses the innate `group` to dodge.
Also using `position = "jitterdodge"` no longer fails due to missing parameters.
Some examples:
If there is no `group` it just jitters:
``` r
p <- ggplot(mpg, aes("x", displ)) +
geom_point(position = "jitterdodge")
p
```
If there is an explicit group, that is used to dodge:
``` r
p + aes(group = drv)
```
If there is an implicit automatic group, it dodges by that:
``` r
p + aes(colour = drv)
```
Explicit groups can be used to override implicit ones:
``` r
p + aes(group = drv, colour = factor(cyl))
```
<sup>Created on 2024-05-31 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
> Use `group` to dodge in `position_jitterdodge()`

- NEWS.md
- R/position-dodge.R
This PR aims to fix #2801 and revives #2813.
Briefly, instead of counting the number of rows per `PANEL`/`xmin` interaction, we are counting the number of unique groups per `PANEL`/`xmin` interaction. Argueably, this is the metric that should be counted.
The reprex from the issue now shows violin plots of appropriate widths:
``` r
ggplot(mtcars, aes(factor(cyl), mpg, fill = factor(vs))) +
geom_violin(position = position_dodge(preserve = "single"))
#> Warning: Groups with fewer than two datapoints have been dropped.
#> ℹ Set `drop = FALSE` to consider such groups for position adjustment purposes.
```
<sup>Created on 2024-06-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
One concern raised in …
> Robust `position_dodge(preserve = "single")` 

- R/theme-elements.R
This PR is an amendement to  #5622.
Briefly, in #5622, we required that certain margin elements in the theme are of the class 'margin'.
However, reverse dependency checks shows that many people use e.g. `theme(plot.margin = unit(c(4, 4, 4, 4), "mm")`.
This isn't necessarily wrong, so this PR allows margin elements to accept units too.
> Margins can be units

- NEWS.md
- R/stat-bin.R
- man/geom_histogram.Rd
- tests/testthat/test-stat-bin.R
This PR is a recreation of #4560 (which can no longer be reopened) and addresses the initial issue discussed in #4561
(Not addressed: rlang lambda function notation for `breaks` and `binwidth`)
The changes allow the `breaks` argument of `stat_bin()` to take functions as input. Example:
``` r
x = c(rexp(1000), rexp(1000, 5)),
study = c(rep("A", 1000), rep("B", 1000))
)
ggplot(df, aes(x)) +
geom_histogram(
mapping = aes(y = after_stat(density)),
breaks = \(x) qexp(c(0, .25, .5, .75, .95, .99), 1/mean(x))
) +
facet_wrap(vars(study))
```
<sup>Created on 2024-06-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
> `stat_bin()` accepts functions for argument `breaks`

- R/fortify.R
This PR aims to fix #4786.
Briefly, it attempts to exploit that some `as.data.frame()` methods will implicitly use `collect()` to realise a local data.frame.
For example:
``` r
dbplyr:::as.data.frame.tbl_sql
#> function (x, row.names = NULL, optional = NULL, ..., n = Inf) 
#> {
#>     as.data.frame(collect(x, n = n))
#> }
#> <bytecode: 0x000001b7f118b958>
#> <environment: namespace:dbplyr>
```
This should ensure that you can still work with e.g. `<tbl_sql>` classes that will be `collect()`'ed while not requiring {dplyr} for the `fortify.tbl()` method. Example demonstrating we can still use lazy data.frames:
``` r
library(dbplyr)
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
dplyr::copy_to(con, mtcars)
df <- …
```
> Don't require dplyr for `fortify.tbl()`

- NEWS.md
- R/geom-hline.R
- R/geom-vline.R
- man/geom_abline.Rd
Reopen #4286, which aimed to fix #4285.
As suggested by @teunbrand, I confirmed now the code works without the `as.numeric()` tweak if I merge the changes of  #5640.
``` r
mydata <- data.frame(
x = factor(c("1", "2", "3")),
y = c(3, 4, 5)
)
mydata$splits <- factor(mydata$x, labels = c("baseline", "Cycle 1", "Cycle 1"))
devtools::load_all("~/GitHub/ggplot2/")
```
``` r
pos <- position_nudge(x = -0.1)
ggplot(mydata, aes(x, y)) +
geom_point(size = 3, position = pos) +
geom_vline(
aes(xintercept = as.numeric(x)),
alpha = 0.2, linewidth = 5,
colour = "red",
position = pos
)
```
``` r
ggplot(mydata, aes(x, y)) +
geom_point(size = 3, position = pos) +
geom_vline(
aes(xintercept = x),
alpha = 0.2, linewidth = 5,
colour = "red",
position = pos
)
```
<sup>Created on 2024-07-01 …
> Expose position arg on geom_hline() and geom_vline()

- R/scale-.R
- R/scale-discrete-.R
This PR is an amendement to #5770.
Briefly, we introduced the `palette` argument, but revdep check show that some people contstruct their discrete position scales using `discrete_scale(..., palette = identity)`. The identity palette is problematic as it doesn't return the expected values. This PR replaces identity palettes with `seq_len` to keep consistent behaviour with older scales.
> Guard against old discrete scales with identity palettes

- R/geom-rug.R
This PR aims to fix #5940.
Briefly, it uses the `setup_params` method to fill in a potentially missing `sides` argument.
> setup sides parameter in `geom_rug()`

- R/scale-gradient.R
- R/scale-grey.R
- R/scale-hue.R
- R/scale-linetype.R
- R/scale-shape.R
- man/scale_gradient.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_linetype.Rd
- man/scale_shape.Rd
This PR aims to fix #5991.
Briefly, some scales like `scale_linetype()` documented `palette` under the `...` parameter, whereas they don't accept user-defined `palette`s. This PR removes `palette` from the `...` documentation in cases it does not apply.
> Exclude `palette` as documented parameter

- R/labels.R
- tests/testthat/test-labels.R
This PR aims to fix #6003.
Briefly, any aesthetic in `layer$computed_mapping` that has an equivalent in `layer$aes_params` is excluded from contributing to the labels. Reprex from issue, please note the label at the colourbar is `G` and not `<<< G >>>` or `g` from the 1st layer.
``` r
d <- data.frame(x = 1, y = 2, g = 3)
d2 <- d
colnames(d2) <- c("X", "Y", "G")
attr(d[[1L]], "label") <- "<<< X >>>"
attr(d[[2L]], "label") <- "<<< Y >>>"
attr(d[[3L]], "label") <- "<<< G >>>"
ggplot() +
geom_point(data = d, aes(x, y, colour = g), colour = "grey") + 
geom_point(data = d2, aes(X, Y, colour = G))
```
<sup>Created on 2024-07-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Exclude labels from `aes_params` field

- DESCRIPTION
- R/position-jitter.R
- man/position_jitter.Rd
Fixes #5875
documentation update
> Adding the option `seed = 0` into the jitter argument

- DESCRIPTION
- R/stat-bin.R
- man/geom_histogram.Rd
- man/stat_summary.Rd
Fix #5960 Changed in documentation the text  - _here"unscaled x"_ - to - _takes x after scale transformation_ - because the function takes transformed values.
> Corrected documentation stat_bin(binwidth) Fixes # 5960

- R/stat-density.R
Fixes #5941 
Not sure if this is necessary because the error message is very descriptive already.
> Making bw argument in stat_density case insensitive

- R/geom-smooth.R
- R/stat-smooth.R
- man/geom_smooth.Rd
> `geom_smooth()`: Updated documentation, "confidence intervals" to "confidence bands"

- R/utilities-break.R
- tests/testthat/_snaps/utilities-break.md
- tests/testthat/test-utilities-break.R
> correct misleading error

- R/labeller.R
Very small change to fix a grammatical error in the `labeller` function documentation
> Fix tiny typo in `labeller` docs

- NEWS.md
- R/labels.R
> `labs()`: Added `gg` class

- NEWS.md
- R/geom-sf.R
> Add translate_string_shape to GeomSf

- NEWS.md
- R/stat-function.R
> `geom_function()`: x-axis title produced automatically where no data is added

- tests/testthat/test-aes-calculated.R
- tests/testthat/test-aes-grouping.R
- tests/testthat/test-coord-.R
- tests/testthat/test-coord-polar.R
- tests/testthat/test-coord-train.R
- tests/testthat/test-coord_sf.R
- tests/testthat/test-empty-data.R
- tests/testthat/test-facet-strips.R
- tests/testthat/test-fortify.R
- tests/testthat/test-geom-boxplot.R
- tests/testthat/test-geom-dotplot.R
- tests/testthat/test-geom-path.R
- tests/testthat/test-geom-rug.R
- tests/testthat/test-geom-sf.R
- tests/testthat/test-geom-violin.R
- tests/testthat/test-guides.R
- tests/testthat/test-layer.R
- tests/testthat/test-position-dodge2.R
- tests/testthat/test-scale-type.R
- tests/testthat/test-scales-breaks-labels.R
- tests/testthat/test-scales.R
- tests/testthat/test-sec-axis.R
- tests/testthat/test-stat-density.R
- tests/testthat/test-stat-function.R
- tests/testthat/test-stat-ydensity.R
- tests/testthat/test-stats.R
- tests/testthat/test-theme.R
- tests/testthat/test-utilities.R
Same as #6050 but used `flint::fix_dir("tests")` this time (to avoid having too many changed files in the same PR).
Changes include:
* `expect_equal(names(x), ...) -> expect_named(x, ...)`
* `expect_equal(x, NULL) -> expect_null(x)`
* `expect_equal(x, TRUE) -> expect_true(x)`
and more.
> Fix some lints in the `tests` folder

- R/geom-path.R
- R/geom-text.R
- man/geom_path.Rd
- man/geom_text.Rd
- man/labeller.Rd
closes #4875 
The changes in #4875 were good but too much has happened in the repo to fix up the PR (most notably renaming of all files from lower-case to upper-case .R file ending)
> legend key examples

- R/geom-text.R
- R/layer.R
- man/borders.Rd
- man/geom_blank.Rd
- man/geom_contour.Rd
- man/geom_errorbarh.Rd
- man/geom_function.Rd
- man/geom_jitter.Rd
- man/geom_linerange.Rd
- man/geom_map.Rd
- man/geom_path.Rd
- man/geom_point.Rd
- man/geom_polygon.Rd
- man/geom_ribbon.Rd
- man/geom_rug.Rd
- man/geom_segment.Rd
- man/geom_spoke.Rd
- man/geom_text.Rd
- man/geom_tile.Rd
- man/ggsf.Rd
- man/labeller.Rd
- man/layer.Rd
- man/layer_sf.Rd
I was reading the `geom_text()` docs and came across these minor typos. Feel free to reject or modify any change that goes against the original intent of what was originally written.
Thanks for maintaining this awesome package!
> Fix typos layer and geom_text docs

- R/plot-construction.R
- man/ggplot_add.Rd
This PR aims to fix #4984.
Briefly, it adds some details and an example to the documentation of `ggplot_add()`.
I'm not sure the example for `element_text()` is the most appropriate one, but I'd be happy to swap out that example for a better one.
> Extra documentation for `ggplot_add()`

- R/stat-contour.R
This PR doesn't address an issue, but I see it as a small chore.
Briefly, `iso_to_path()` and `iso_to_polygon()` were nearly identical functions. 
This PR merges these with a switch, which simplifies reasoning about the contours somewhat as you only have to understand 1 function instead of 2.
> chore: merge isoband/isolines functions

- R/geom-ribbon.R
This fixes an unintentional change in https://github.com/tidyverse/ggplot2/pull/5833.
---
**v3.5.1** (https://ggplot2.tidyverse.org/reference/geom_ribbon.html#ref-examples):
**dev** (https://ggplot2.tidyverse.org/dev/reference/geom_ribbon.html#ref-examples):
> Change `fill` of `GeomRibbon` to match with the previous default colour

- README.Rmd
- vignettes/articles/faq-annotation.Rmd
- vignettes/articles/faq-axes.Rmd
- vignettes/articles/faq-bars.Rmd
- vignettes/articles/faq-customising.Rmd
- vignettes/articles/faq-faceting.Rmd
- vignettes/articles/faq-reordering.Rmd
- vignettes/extending-ggplot2.Rmd
- vignettes/ggplot2-specs.Rmd
- vignettes/ggplot2.Rmd
Positron warns me a lot about the YAML syntax of `fig.alt`. Interestingly, if I re-render the README, there's no difference on `alt` of the corresponding `<img>` tag. So, it seems R Markdown is more permissive than Positron, and this is not a real problem. But, I think it's good to use valid YAML syntax anyway.
> Fix the YAML syntax of fig.alt chunk option

- vignettes/articles/faq-customising.Rmd
It seems this description needs updated.
https://ggplot2.tidyverse.org/dev/articles/faq-customising.html#fonts
> Update code of showing the default size of `geom_text()`

- NEWS.md
- R/summary.R
- tests/testthat/_snaps/utilities.md
- tests/testthat/test-utilities.R
This PR aims to fix #5989.
Briefly, `summary.ggplot()` no longer prints the whole facet ggproto object, but rather prints the variables used for facetting.
Some examples with various facets:
``` r
geom_point()
summary(p)
#> data: manufacturer, model, displ, year, cyl, trans, drv, cty, hwy, fl,
#>   class [234x11]
#> mapping:  x = ~displ, y = ~hwy
#> faceting:  <empty> 
#> -----------------------------------
#> geom_point: na.rm = FALSE
#> stat_identity: na.rm = FALSE
#> position_identity
summary(p + facet_wrap(~drv))
#> data: manufacturer, model, displ, year, cyl, trans, drv, cty, hwy, fl,
#>   class [234x11]
#> mapping:  x = ~displ, y = ~hwy
#> faceting:  ~drv 
#> …
```
> Make facet section of `summary()` more terse

- R/geom-text.R
- man/geom_text.Rd
This PR fixes #6033. The title pretty much covers the PR's content.
> Fix mistake in alignment docs for `geom_text()`

- R/position-dodge.R
- tests/testthat/test-position_dodge.R
This PR aims to fix #5995 and fix #3647.
Briefly, when `xmin` is absent from the data, `x` is used to count the number of groups per location.
In addition, some guardrails are in place to not use non-existing columns in the calculation.
``` r
palmerpenguins::penguins |>
dplyr::count(species, sex) |>
ggplot(
aes(x = sex,
y = n,
fill = species,
label = n),
) +
geom_col(
position = position_dodge(preserve = "single"),
width = 0.75,
alpha = 0.9,
) +
geom_text(
colour = "black",
position = position_dodge(width = 0.75, preserve = "single"),
vjust = 1.33,
)
```
<sup>Created on 2024-07-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Fix for `position_dodge(preserve = "single")` with location based data

- R/plot-construction.R
This PR fixes a regression from #5967 that is detectable as:
https://github.com/tidyverse/ggplot2/blob/d31c051bb87cd5d5f02e8d19b5c002ad2a129d6c/revdep/problems.md?plain=1#L155-L156
Briefly, this error occurs when the constructor call doesn't get captured cleanly, like in the following case:
``` r
rlang::call_name(do.call(geom_point, list())$constructor)
#> NULL
```
<sup>Created on 2024-09-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
In this PR, we construct a fallback name based on the geom's ggproto class.
> Fix regression from #5967

- R/scale-linetype.R
- R/scale-manual.R
- man/scale_linetype.Rd
- man/scale_manual.Rd
- tests/testthat/test-scale-manual.R
This PR aims to fix #6096.
Briefly, it replaces `na.value = "blank"`, which casts mapped value to characters, to `na.value = NA`, which will cast `NA` to whatever type mapped values have.
> Fix linetype regression

- R/plot.R
This PR aims to fix part of #6008.
Briefly, reverse dependencies sometimes make assumptions about `length(ggplot())` or `names(ggplot())`. In #5879 we removed the `labels` field, causing these assumptions to no longer hold. This PR brings back the `labels` field to make these assumptions valid again.
> Fix missing `labels` slot

- R/coord-.R
- tests/testthat/test-coord-.R
This PR fixes a regression introduced by #6027, that is detectable as:
https://github.com/tidyverse/ggplot2/blob/d31c051bb87cd5d5f02e8d19b5c002ad2a129d6c/revdep/problems.md?plain=1#L18570-L18572
The regression occurs when `expand = 0` or `expand = 1` is set in the coord, and this PR makes this valid input again.
> Fix regression from #6027

- R/facet-wrap.R
Currently `FacetWrap$draw_panels()` recalculates `layout$SCALE_X` and `layout$SCALE_Y` if used with `coord_flip()`. This PR changes the behaviour to instead restore the scales as calculated by `$compute_layout()`.
This is relevant when a subclass of `FacetWrap` has a customised layout, but could still otherwise call `FacetWrap$draw_panels()`, like in [ggragged](https://github.com/mikmart/ggragged/blob/513525d100ed636e29bebadd7f29391193246ceb/R/facet_ragged_cols.R#L38).
Fixes mikmart/ggragged#2.
> Restore rather than recalculate scales in `FacetWrap` with `CoordFlip`

- R/aes-evaluation.R
- man/aes_eval.Rd
- tests/testthat/test-aes-calculated.R
This PR adds tests to codify the behavior of `aes(stage(x))` and its variants working equivalently to `aes(x)`.
I had been under the impression that `stage(x)` will remain invalid since #4890 was closed without a follow-up (and with a general agreement that this is an odd thing to do), but that issue seems to have been resolved a while back as part of a larger PR in #5409. I assume that the currently working behavior of `stage(x)` is intended and desirable, and I would personally like for this to be guaranteed as a stable behavior (or at least, for there to be tests to detect its unintended regression).
Hence, the PR adds three tests of equivalence between `aes(x)` and:
1. `aes(stage(x))`
2. `aes(stage(start = x))`
3. `aes(stage(start = x, after_stat = NULL, after_scale = NULL))`
I saw …
> Add test for using `stage()` with a mapping specified for `start` only

- vignettes/articles/faq-annotation.Rmd
- vignettes/articles/faq-axes.Rmd
- vignettes/articles/faq-bars.Rmd
- vignettes/articles/faq-customising.Rmd
- vignettes/articles/faq-faceting.Rmd
- vignettes/articles/faq-reordering.Rmd
- vignettes/extending-ggplot2.Rmd
- vignettes/ggplot2-in-packages.Rmd
- vignettes/ggplot2-specs.Rmd
- vignettes/ggplot2.Rmd
- vignettes/profiling.Rmd
This PR follows #6083 and is in anticipation of spring cleaning 2024.
It applies YAML syntax of chunk options (quarto chunk style) everywhere.
> Use `knitr::convert_chunk_header(type = "yaml")`

- R/geom-histogram.R
- R/stat-bin.R
- man/geom_histogram.Rd
This PR addresses the points brought up in #5895: 
- The default behavior of `stat_bin()` of mapping counts to _height_ instead of _area_ is suitable for most common applications.
- This is because most common applications use equal-width bins.
- When non-equal-width bins are used, this behavior produces histograms that are hard to interpret and violate the [proportional ink](https://clauswilke.com/dataviz/proportional-ink.html) principle. 
- Therefore, I suggested adding to the docs/examples something that discusses this / shows how to do it properly.
Which is what I did 
Previously was:
> - `after_stat(width)`
widths of bins.
Now is:
> - `after_stat(width)`
widths of bins. Use with `after_stat(count / width)` to obtain bars with _areas_ representing counts (e.g., with non-equal-width …
> Expand on docs/example for cases with non-equal-width bins in `stat_bin()`

- R/geom-defaults.R
- man/update_defaults.Rd
This PR aims to fix #6085.
Briefly, it explains the 'all geoms versus single geom' axis versus 'update once versus update always' axis of using the update functions, suggested here: https://github.com/tidyverse/ggplot2/issues/6085#issuecomment-2333594467.
> Update `update_geom_defaults()` docs

- NEWS.md
- R/scale-.R
- tests/testthat/test-scale-binned.R
This PR aims to fix #6144.
It simply doesn't attempt to pre-transform the limits when the limits is a function.
``` r
df <- data.frame(x = seq(as.Date("2024-01-01"), as.Date("2024-06-30"), "day"))
ggplot(df) +
geom_bar(aes(x)) +
scale_x_binned(
breaks = scales::breaks_width("1 month"),
transform = scales::transform_date(),
limits = function(x) { x }
)
#> Warning in scale_x_binned(breaks = scales::breaks_width("1 month"), transform = scales::transform_date(), : Ignoring `n.breaks`. Use a breaks function that supports setting number of
#> breaks.
```
<sup>Created on 2024-10-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
The spurious warning the scale throws is commented upon …
> Fix binned scaled not accepting function-limits if there are transformations

- NEWS.md
- R/save.R
> Checks if svglite is installed when saving to svg.

- R/geom-sf.R
- tests/testthat/_snaps/geom-sf/north-carolina-county-boundaries.svg
- tests/testthat/test-geom-sf.R
This PR fixes https://github.com/tidyverse/ggplot2/pull/5904#issuecomment-2403851670.
Briefly, `linetype` never ended up in the grob's graphical parameters. This PR fixes that.
> Restore `geom_sf()`'s `linetype` aesthetic

- tests/testthat/test-patterns.R
- tests/testthat/test-utilities-checks.R
Should have been caught with #6175, sorry about that.
https://github.com/tidyverse/ggplot2/blob/cc329df041573c4ca0ce31b491de0144506c12f6/R/utilities-checks.R#L321-L324
> Adjust version for svglite skip

- NEWS.md
- R/annotation-custom.R
- R/annotation-raster.R
- tests/testthat/_snaps/annotate.md
- tests/testthat/test-annotate.R
This PR aims to fix #3120 and is incompatible with #3121.
Briefly, it uses the panel parameters to transform the corners of the rectangle used for annotation placement.
To recap some discussion in #3121. The scales should affect the annotation, but not vice versa (i.e., we don't want to train scales on annotations) https://github.com/tidyverse/ggplot2/pull/3121#issuecomment-465171258. The approach of encoding the corners coordinates as aesthetics did affect the scales, so that approach was unsuitable. Instead it was proposed to keep them as parameters and transform them in the drawing stage https://github.com/tidyverse/ggplot2/pull/3121#issuecomment-466220128. In addition, it was proposed to have data agnostic placement as well https://github.com/tidyverse/ggplot2/pull/3121#issuecomment-46 …
> `annotation_raster()/_custom()` respond to scale transformations

- tests/testthat/test-scale-binned.R
I see this warning.
```
> devtools::test(filter = "binned")
ℹ Testing ggplot2
✔ | F W  S  OK | Context
✔ |   1     15 | scale-binned                                                                                
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning (test-scale-binned.R:48:3): binned scales can use limits and transformations simultaneously (#6144)
The `trans` argument of `binned_scale()` is deprecated as of ggplot2 3.5.0.
i Please use the `transform` argument instead.
Backtrace:
▆
1. └─ggplot2::scale_x_binned(limits = function(x) x + 1, trans = transform_log10()) at test-scale-binned.R:48:3
2.   └─ggplot2::binned_scale(...) at ggplot2/R/scale-binned.R:34:3
3.     └─ggplot2:::deprecate_soft0("3.5.0", …
```
> Fix a minor deprecated warning about `trans` arg

- R/geom-sf.R
This PR aims to fix #6189.
Briefly, `ggraph::GeomEdgeSf` did not have a `stroke` aesthetic in `GeomEdgeSf$default_aes`.
That causes some calculations to go awry in `GeomSf$draw_panel()`.
This PR makes a fallback for when `stroke` is missing.
``` r
library(ggraph)
gr <- sfnetworks::as_sfnetwork(sfnetworks::roxel)
ggraph(gr, 'sf') + geom_edge_sf()
```
<sup>Created on 2024-11-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Fix regression in `geom_sf()`

- vignettes/ggplot2-in-packages.Rmd
This PR aims to fix #5927.
It does so by no longer advising to use a pointless theme wrapper.
> Replace confusing wording for themes in vignette

- R/coord-polar.R
- R/guide-axis-stack.R
- man/coord_polar.Rd
- man/guide_axis_stack.Rd
Fixes #6122
Two very small edits removing double comment tags in roxygen2 docs.
> 6122 fix exposed roxygen2

- R/fortify-map.R
- R/fortify-spatial.R
- man/fortify.map.Rd
- man/fortify.sp.Rd
- man/map_data.Rd
- tests/testthat/_snaps/geom-map.md
- tests/testthat/test-geom-map.R
This PR aims to fix #3816, close #5469 and fix #3717.
With regards to #3816, this PR checks off the last bullet that `fortify.map()` is deprecated.
WIth regards to #5469, this PR makes the issue obsolete, since we have deprecated all the functions we were considering putting up for adoption.
With regards to #3717 this PR fixes the mislinked `map_data(map)` argument.
> Tweaks to `map_data()`/fortify.map()`

- R/geom-point.R
- man/geom_point.Rd
- vignettes/ggplot2-specs.Rmd
Adds an example for `geom_point` and a small note to the relevant part of the specs vignette so there's a better chance of people finding out how to deal with guides for filled shapes. Closes #6177.
> Explain how to fix fill guide for points with filled shapes

- R/limits.R
- man/lims.Rd
This PR aims to fix #5148.
It more clearly points out out-of-bounds handling options.
> :memo: Tweak docs for `lims()`

- NEWS.md
- R/geom-ribbon.R
- tests/testthat/_snaps/geom-ribbon.md
- tests/testthat/test-geom-ribbon.R
This PR aims to fix #6243.
Briefly, missing values are thrown out and warn about when `na.rm = FALSE`.
The warning is skipped when `na.rm = TRUE` but missing values are thrown out.
When throwing out missing values, the `group` aesthetic is reformed so that groups with NA values break up into new uninterrupted groups.
Reprex from issue, note gradient is uniform now:
``` r
x = c(1:3, 1:3),
ymin = c(1, 1, 1, NA, 2, 2),
ymax = c(1.5, 2, 1.5, 2.5, 3, 2.5),
group = c(1,1,1,2,2,2)
)
ggplot(df, aes(x, ymin = ymin, ymax = ymax, group = group, fill = x)) +
geom_ribbon() +
scale_fill_viridis_c()
#> Warning: Removed 1 row containing missing values or values outside the scale range
#> (`geom_ribbon()`).
```
<sup>Created …
> Fix `geom_ribbon(na.rm)`

- R/coord-radial.R
- man/coord_polar.Rd
Fix minor typo in coord_radial documentation. Closes #6276.
> Fix typo in coord_radial documentation

- NEWS.md
- R/scale-discrete-.R
- R/scale-expansion.R
- man/scale_discrete.Rd
- tests/testthat/test-scale-expansion.R
This PR aims to fix #6259 and fix #4174.
Briefly, the discrete position scales get a new argument `continuous.limits` which controls what range is displayed.
It always acts as 'zoom limits', similar to limits set in the coord or continuous limits with `oob = scales::oob_keep()`.
Reprex from #4174:
``` r
stringsAsFactors = FALSE,
continent = c("europe","europe","europe",
"europe","asia","asia","asia","south america"),
country = c("AT", "DE", "DK", "ES", "PK", "IN", "TW", "BR"),
value = c(10L, 15L, 20L, 25L, 17L, 17L, 13L, 5L)
)
p <- df |>
ggplot() +
geom_col(
aes(y = country, x = value),
orientation = "y"
) +
facet_wrap(vars(continent), scales = "free_y")
p + scale_y_discrete(continuous.limits = c(1, 4))
``` …
> Continuous limits for discrete scales

- tests/testthat/_snaps/scales.md
- tests/testthat/test-scales.R
This PR fixes an issue discussed off-github.
Briefly, scales 1.4.0 was poised to break ggplot2 because `transform_exp()`'s breaks were improved and broke a test.
This PR makes all the transformation break tests snapshots, which means ggplot2 will not break on CRAN in the future if breaks are further improved.
> Use snapshot expectations for transformation breaks

- R/legend-draw.R
- tests/testthat/_snaps/legend-draw/all-legend-keys.svg
- tests/testthat/test-legend-draw.R
This PR aims to fix #6191.
Briefly, this PR adds a missing value for the `staplewidth` parameter in `draw_key_boxplot()`.
Also added test to prevent silent breakages of keys in the future.
> Ensure boxplot key can be drawn without `params`

- R/stat-density-2d.R
This PR aims to fix #5571.
It is a simple fix that just does what the title indicates.
Example from linked issue:
``` r
ggplot() +
layer(
geom = GeomDensity2d,
stat = StatDensity2d,
data = faithful,
mapping = aes(x = eruptions, y = waiting),
position = PositionIdentity,
)
```
<sup>Created on 2024-12-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Missing `contour` parameter defaults to `TRUE`

- README.Rmd
- README.md
Per discussion outside GitHub, it would be good to find the tidyverse blogs related to ggplot2 easily.
> :link: Link out to tidyverse blog

- R/scale-.R
- man/binned_scale.Rd
- man/continuous_scale.Rd
- man/datetime_scale.Rd
- man/discrete_scale.Rd
- man/scale_binned.Rd
- man/scale_continuous.Rd
- man/scale_date.Rd
- man/scale_discrete.Rd
- man/scale_gradient.Rd
- man/scale_grey.Rd
- man/scale_hue.Rd
- man/scale_linetype.Rd
- man/scale_linewidth.Rd
- man/scale_manual.Rd
- man/scale_shape.Rd
- man/scale_size.Rd
- man/scale_steps.Rd
This PR aims to fix #5208.
Briefly, it implements the advice in https://github.com/tidyverse/ggplot2/issues/5208#issuecomment-1446935976 in the documentation:
>  I have long operated under the rule of thumb that one should never specify labels without specifying breaks. We could just formalize that rule.
> Encourage specifying `breaks` when giving labels as a vector

- R/theme-elements.R
- man/element.Rd
> 📝 Mention (`fill_`)`alpha()` in theme element docs

- R/guides-.R
This PR aims to fix #6291.
Briefly it circumvents the `+` dispatch by using `add_theme()` directly.
In addition, contains a small failsafe for when `theme(legend.position)` is not recognised.
> 🚑 Fix for revdep problem with adding `NULL` to theme

- R/facet-grid-.R
This PR aims to fix #6292.
It replaces the vctrs subsetting by base subsetting.
> 🚑 Fix for using `vec_slice()` before naturalising data

- R/plot-construction.R
This PR aims to fix #6295.
It bequeaths the 'unknown' name upon layers that have lost their names.
``` r
geom_point()
p$layers <- list(geom_path(), geom_path())
p <- p + geom_point() + geom_point()
names(p$layers)
#> [1] "unknown...1"    "unknown...2"    "geom_point"     "geom_point...4"
```
<sup>Created on 2025-01-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> 🚑 Repair layer names that might have become lost

- R/geom-ribbon.R
This PR aims to fix an issue uncovered in #6287.
Briefly, in some extension packages an if-statement might have length other than 1. This PR asks for exactly length 1.
> 🚑 Amend clause in #6244

- R/guides-.R
This PR aims to fix an issue identified in #6287.
Briefly, some packages implement `ggplot_build()` methods. We added a `theme` argument to `Guides$build()`, which is now causing complaints about missing arguments in reverse dependencies. This PR provides a fallback for when the extension's `ggplot_build()` method does not support the new guide building yet.
> 🚑 Give default value to `Guides$build(theme)`

- R/position-nudge.R
- man/hmisc.Rd
- man/position_nudge.Rd
Recently, when creating plots with `ggstatsplot` (using the `ggbetweenstats` function), I wanted to move the centrality labels for each distribution individually. It took me quite some time to figure out that I can pass a vector to `nudge_y` (or `position_nudge` for that matter).
Therefore, I propose to document this functionality.
> Document vector passing to nudge_y/nudge_x/position_nudge

- R/geom-crossbar.R
- R/geom-pointrange.R
This PR amends #6238.
Briefly: it prevents a bunch of false positive warnings about the `fatten` parameters.
In some details; `lifecycle::is_present(params$fatten)` was evaluated as `TRUE` when fatten was absent and `params$fatten` returns `NULL`. This caused a bunch of false-positive deprecation warnings in stats that has `geom = "crossbar"` or `geom = "pointrange"`, like `stat_summary_bin()`.
> 🩹 Don't warn when fatten is absent

- NEWS.md
- R/theme-defaults.R
This PR aims to fix #6320.
Instead of setting `panel.grid.major` and `panel.grid.minor` to blank, we set the parent `panel.grid` to blank.
``` r
geom_point() +
theme_classic()
p + theme(panel.grid = element_line(colour = "limegreen"))
```
<sup>Created on 2025-02-05 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Bump level of panel grid blanknness in `theme_classic()`

- R/aes.R
- R/labels.R
- R/layer.R
- tests/testthat/test-labels.R
This PR aims to fix #6316.
Briefly, it skips label extraction when the mapping was constructed using the `aes_all()` function. This is communicated through a subclass. The layers from `annotation()` and `expand_limits()` functions are thereby not contributing to labels.
> Skip annotation labels

- R/stat-bin.R
- man/geom_histogram.Rd
- tests/testthat/test-stat-bin.R
This PR amends #6212 and also fixes #5118.
Briefly, #6212 repurposed the `keep.zeroes` argument to `drop`, but I forgot to invert the logic as well. This PR ensures that the interpretation is consistent and that `drop = TRUE` removes empty bins and `drop = FALSE` keeps them.
The fix for #5118 comes from being able to control the warning at the root of the issue.
> Align `stat_bin(drop)` with meaning

- NEWS.md
- R/position-jitter.R
- R/position-jitterdodge.R
- tests/testthat/test-position-jitter.R
This PR aims to fix #3722.
It ensures that the default, resolution-based jitter width is computed per panel instead of per layer.
Reprex from  the issue, notice that the jitter has about equal visual spread across panels:
``` r
set.seed(123)
y = rnorm(100, 50, 10),
x = c(rep(1:5, 10), rep(seq(0, 100, length.out = 5), 10)),
group = c(rep("a", times = 50), rep("b", times = 50))
)
ggplot(df, aes(x = x, y = y)) +
geom_point(color = "orange", alpha = 0.7) +
geom_point(position = "jitter", color = "blue", alpha = 0.7) +
facet_wrap( ~ group, scales = "free")
```
<sup>Created on 2025-02-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
An open question is whether we should do this for …
> Compute jitter width by panel

- R/scale-.R
- R/scale-continuous.R
This PR replaces #5032.
Briefly, it skips the NA replacment step if there are no NAs present.
Moreover `vec_assign()` is faster (and I presume more type stable) than `ifelse()`.
I think it is more of an 'empirical' determination than relying on some palette attribute as is proposed in the linked PR.
Benchmarking this PR, note 4 continuous scales (x, y, size, colour):
``` r
p <- ggplot(diamonds, aes(carat, price, colour = depth, size = table)) +
geom_point()
bench::mark(ggplot_build(p), min_iterations = 10)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 1 × 6
#>   expression           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>      <bch:tm> <bch:tm>     <dbl> …
```
> :zap: Skip replacing NAs during mapping when appropriate

- R/theme-defaults.R
- man/ggtheme.Rd
- tests/testthat/_snaps/geom-polygon/open-and-closed-munched-polygons.svg
- tests/testthat/_snaps/guides/guide-custom-with-void-theme.svg
- tests/testthat/_snaps/theme/theme-minimal-large.svg
- tests/testthat/_snaps/theme/theme-minimal.svg
- tests/testthat/_snaps/theme/theme-void-large.svg
- tests/testthat/_snaps/theme/theme-void.svg
This PR aims to fix #6251.
Briefly, some themes had `plot.background = element_blank()` (explicitly or implicitly), which led to counterintuitive colouring.
By providing this element we surprise less.
Examples:
``` r
geom_point()
p + theme_minimal(paper = "cornsilk")
```
``` r
p + theme_void(paper = "cornsilk")
```
<sup>Created on 2025-02-24 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Background for `theme_void()` and `theme_minimal()`

- R/coord-radial.R
- man/coord_polar.Rd
Partial of https://github.com/tidyverse/ggplot2/issues/6259 (The feature request has been changed from set limits for `coord_radial()`).
Since `coord_polar()` does not have an `expand` argument, I have not implemented this for `coord_polar()`.
```r
ggplot(mtcars, aes(disp, mpg)) +
geom_point() +
coord_radial(
start = -0.4 * pi,
end = 0.4 * pi, inner.radius = 0.3
)
```
```r
ggplot(mtcars, aes(disp, mpg)) +
geom_point() +
coord_radial(
start = -0.4 * pi,
end = 0.4 * pi, inner.radius = 0.3,
xlim = c(200, 300),
ylim = c(15, 30),
clip = "on"
)
```
> coord_radial: add xlim and ylim arguments

- NEWS.md
- R/facet-.R
- R/layout.R
- man/ggplot2-ggproto.Rd
fix https://github.com/tidyverse/ggplot2/issues/6380
This commit just add new method `setup_panel_params` in `Facet` object, and let `Facet` can act with the `panel_params` setted by `Coord` object before drawing.
> `Facet`: new method `setup_panel_params` to interact panel_params

- R/coord-radial.R
- man/coord_polar.Rd
- tests/testthat/_snaps/coord-polar.md
fix https://github.com/tidyverse/ggplot2/issues/6411
> make sure using the prepared `r_axis_inside` for all methods

- DESCRIPTION
- R/geom-sf.R
- R/theme-defaults.R
- R/utilities.R
- tests/testthat/_snaps/scale-date.md
- tests/testthat/_snaps/theme/theme-with-inverted-colours.svg
This PR aims to fix #6172.
It implements the two remaining items on the list in the issue.
Most of this PR are just tiny changes in colour mixing proportions to preserve the hex code.
One visual test changed, but that is fine as that theme option wasn't available in previous versions, so there isn't anything to preserve really.
> Adapt to scales 1.4.0

- NEWS.md
- R/facet-.R
- R/layout.R
- man/ggplot2-ggproto.Rd
fix https://github.com/tidyverse/ggplot2/issues/6406
Following the advice of @teunbrand
> Facet: gain draw_facet_panels method to draw grobs for each panel

- tests/testthat/test-coord-map.R
The dependency of the test on {maptools} is not very transparent; here's the failure if {maptools} is not installed:
```
<rlib_error_package_not_found/rlang_error/error/condition> ('test-coord-map.R:55:3')
--------------------------------------------------------------------------------
<rlib_error_package_not_found/rlang_error/error/condition>
Error in `mproject(self, grid$x, grid$y, orientation)`: The package "mapproj" is required for `coord_map()`.
Backtrace:
x
1. +-testthat::expect_snapshot_warning(...) at test-coord-map.R:55:3
2. | \-testthat:::expect_snapshot_condition(...)
3. |   +-testthat:::with_is_snapshotting(...)
4. |   \-testthat:::capture_matching_condition(x, cnd_matcher(class))
5. |     \-base::withCallingHandlers(...)
6. +-ggplot2::ggplot_build(ggplot() + coord_map() + …
```
> Optionally skip test requiring maptools

- R/geom-contour.R
- man/geom_contour.Rd
While switching to R 4.5.0, I hadn't installed {interp} and {akima} yet. I noticed roxygen complains when these aren't present due to some links in the doc pages. I don't think it is worth it to place them in suggested packages just for the purpose of linking docs. So instead I propose to remove the links.
> Don't link {interp} and {akima} packages

- R/scale-.R
- tests/testthat/_snaps/scales.md
This PR aims to fix #6184.
Briefly, the actual solution is already implemented in the scales package in https://github.com/r-lib/scales/pull/481. We just adapt ggplot2 to this solution by abdicating responsibility to scales.
> Simplify scale training

- R/theme.R
- man/theme.Rd
This PR aims to fix an issue discussed off github.
It just adds a few examples to illustrate the possibilities.
> Add examples for `theme(geom, palette.colour.continuous)`

- R/scale-.R
- tests/testthat/test-utilities.R
Thsi PR aims to fix #6384 and amends #6200.
Briefly, the reason `bquote()` input for scale names wasn't accepted is because it was interpreted as a two-sided formula.
This PR only attempts to cast a RHS-only formula as a function.
``` r
eff <- "Efficiency"
ggplot(mtcars, aes(factor(cyl), mpg)) + 
geom_boxplot() + 
scale_y_continuous(name = bquote(.(eff)~(mi~gl^{-1})))
```
<sup>Created on 2025-03-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Only RHS-formula accepted as lambda function

- R/scale-.R
This aims to fix a problem identified in #6469.
Briefly, using `vec_c()`  to concatenate the palette with `na.value` is  too strict in some cases. It was introduced in #6118.
Herein, we use regular `c()`, relying on `vctrs:::c.vctrs_vctr` to handle to vctrs case correctly.
> Fix reverse dependency issue with scale `na.value`

- R/scale-colour.R
This PR aims to fix a problem identified in #6469.
Briefly, the `scale_backward_compatibility()` fallback we used sometimes got handed `scale = NULL`, which I didn't anticipate. That change was introduced in #5946. Here, we inspect `type` to inform us what to do in that case.
> Fix reverse dependency issue with `scale_backward_compatibility()`

- R/layer.R
Fixes #6467 - layer expression shows up correctly on print
```r
p_expr <- parse(text = "
p <- ggplot() +
geom_point(size = 5)
")
eval(p_expr)
p$layers[[1]]$constructor
#> geom_point(size = 5)
```
I don't think I see existing tests for `$constructor` and this is only a minor display change, but if we were to add a test for the PR it'd be something like:
```r
expect_identical(
capture.output(p$layers[[1]]$constructor),
"geom_point(size = 5)"
)
```
> Strip `srcref` from the `$constructor` expression

- R/labels.R
- tests/testthat/_snaps/labels.md
- tests/testthat/test-labels.R
This PR aims to fix #6463.
Briefly, function-labels are formatted as `<function>` so they don't mess with text formatting.
Example from reprex, note the warning about unknown labels:
``` r
library(palmerpenguins)
penguins |> 
ggplot() +
geom_histogram(aes(x = flipper_length_mm)) +
labs(
x = snakecase::to_sentence_case,
y = snakecase::to_sentence_case,
fill = snakecase::to_sentence_case,
)
#> Warning: Ignoring unknown labels:
#> • fill : <function>
#> `stat_bin()` using `bins = 30`. Pick better value `binwidth`.
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_bin()`).
```
<sup>Created on 2025-05-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Fix label formatting bug in warning

- R/scale-.R
This PR aims to fix #6499.
The solution is the same as in #6474.
Reprex from the issue:
``` r
ggplot(mpg, aes(displ, hwy, colour = drv)) +
geom_point() +
scale_colour_manual(
values = structure(c(`4` = "blue", f = "red", r = "green"), class = "foobar"),
na.value = "gray"
)
```
<sup>Created on 2025-06-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> Tiptoe around `na.value`

- R/theme-elements.R
- man/element.Rd
The document of `element` says the return value is "S3", but `element` and `margin` are already S7. `rel` is still S3, so this pull request just removes `S3` for accuracy.
> A really minor document tweak

- R/plot.R
If/when S7 decides to fix the bug, `rm("non-existant")` will produce a warning message.
By using `local()`, it will work for the current version and if/when S7 fixes it.
> bug(S7): Use `local()` to avoid `rm()` call

- R/utilities-help.R
fix https://github.com/tidyverse/ggplot2/issues/6537
> fix: correct Rd link syntax for aesthetics roxygen2 tag

- R/theme-sub.R
- man/subtheme.Rd
- tests/testthat/_snaps/theme.md
- tests/testthat/test-theme.R
This PR aims to fix #6491.
It integrates the `panel.widths`, `panel.heights`, `axis.minor.ticks.length.{...}` and `axis.minor.ticks.{...}` settings in the `theme_sub_axis_*()` family and `theme_sub_panel()` function.
A demo:
``` r
minor <- guide_axis(minor.ticks = TRUE)
geom_point() +
theme_sub_panel(
widths = unit(5, "cm"),
heights = unit(5, "cm")
) +
guides(x = minor, y = minor, x.sec = minor, y.sec = minor) +
theme_sub_axis(minor.ticks.length = unit(5, "mm")) +
theme_sub_axis_bottom(minor.ticks = element_line(colour = "red")) +
theme_sub_axis_left(minor.ticks = element_line(colour = "limegreen")) +
theme_sub_axis_right(minor.ticks = element_blank()) +
theme_sub_axis_top(minor.ticks.length = …
```
> Add missing theme sub args

- vignettes/extending-ggplot2.Rmd
This PR aims to fix #6524.
It replaces some constructor code with the `make_constructor()` shortcut. This also leaves 1 instance of when not to use a constructor when you want to bake-in the 'stat' for example.
> Show `make_constructor()` a few times in extension vignette

- R/zzz.R
fix https://github.com/tidyverse/ggplot2/issues/6560
> fix: correct `+` method dispatch behavior for R >= 4.3.0

- .github/workflows/R-CMD-check.yaml
Close #6620 
As ragg 1.5.0 cannot be installed on Windows with R 4.1, use 1.4.0.
> ci: Add Tweak for Windows R 4.1

- R/backports.R
- R/geom-polygon.R
Deleted all code snippets that call `getRversion() <= "4.1"`. Fixes #6589
> Fixes Delete code for old versions of R

- R/theme-current.R
- man/get_theme.Rd
- tests/testthat/test-theme.R
`set_theme()` called without any arguments resets the theme to the default theme.
Fixes #6598.
> set_theme() resets theme if called with no arguments.

- NEWS.md
- R/utilities.R
- tests/testthat/test-scales-breaks-labels.R
Fix #6617 
This function `size0` was introduced in https://github.com/tidyverse/ggplot2/pull/6076 and I guess the expression labels don't work since then. Reading #6076, I found there's no intention to drop support for expression labels, so I think this fixes the problem. (As I don't actively follow the recent development of ggplot2, sorry if I'm missing some discussion)
``` r
library(tibble)
devtools::load_all("~/GitHub/ggplot2/")
#> Overwriting method +(<ggplot2::ggplot>, <ANY>)
#> 
#> Overwriting method +(<ggplot2::theme>, <ANY>)
#> 
#> Overwriting method convert(<ggplot2::ggplot>, <list>)
ggplot(tibble(x = -10:10, y = x^2)) +
geom_point(aes(x, y)) +
scale_x_continuous(
breaks = seq(-10, 10, 2),
labels = parse(text = paste0(seq(-10, 10, 2), "^degree"))
)
``` …
> Allow expression labels in `scale_{x,y}_*()`

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- R/zzz.R
- README.Rmd
- README.md
discussed in #6681
I've updated all mentions and urls of RStudio Community to posit Community, but added "(formerly RStudio community)" when relevant for context and disambiguation
> update mentions of RStudio Community
