tidyverse/ggplot2

.travis.yml
This will hopefully fix the travis error.
=> Remove rgeos from binary installation

NEWS, R/theme.r, inst/tests/test-theme.r, man/theme.Rd
This is a cleaner version of https://github.com/hadley/ggplot2/pull/953#issuecomment-111270357
=> theme(validate=FALSE) means do not validate_element (clean)

R/facet-grid-.r, R/theme-defaults.r
Fixes #1170.
I also adjusted the default padding. Before:
After:
=> Fix issues with switched facet strips

NEWS, R/scale-.r, tests/testthat/test-scales-breaks-labels.r
=> Fix automatically computed breaks for "probit" scale

R/facet-labels.r, tests/testthat/test-facet-labels.r
=> Fix label_value() to handle factors

R/plot-build.r
Clearer function and argument names in plot-build.r.
=> Rename dlapply() to by_layer()

R/facet-labels.r
=> Fix spurious warning in label_bquote()

R/position-collide.r
1. Copy
2. Paste
3. Modify*
\* Previously incomplete step, now complete.
=> Fix dulicate xmin, xmax calculation in collide()

inst/CITATION
To make it consistent with JSS style (and springer website)
=> update of CITATION

NEWS, R/stat-boxplot.r, tests/testthat/test-boxplot.r
- Only if there is more than one x value
- With tests
Fixes #992.
Closes #1213 (=includes it).
=> stat_boxplot warns if x is continuous and no group aesthetics is specified

R/guide-legend.r
=> No legend when aes parameters overide mappings

R/theme-defaults.r
Actually not due to your refactor but to this old regression in #1263
=> Strip text rotated opposite dir to axis text (derived themes)

R/margins.R
change 
@param t,b,r,l Dimensions of each margin. (To remember order, think trouble).
to
@param t,r,b,l Dimensions of each margin. (To remember order, think trouble).
=> Correct mistakes in the document

R/facet-wrap.r, tests/testthat/test-facet-strips.r
=> Fix labels-switching in facet_wrap()

R/geom-text.r
=> Removes incomplete sentence

vignettes/extending-ggplot2.Rmd
From: "you're best **of** transforming your data"
To: "you're best **off** transforming your data"
=> Fix typo in Extending ggplot2 vignette

NEWS.md, R/stat-.r, tests/testthat/test-stats.r
=> Fix required_aes error message of Stats

NEWS.md, R/geom-violin.r
=> Don't use alpha for violin quantiles

NEWS.md, R/theme-elements.r, man/element_line.Rd
=> Add arrow argument to element_line()

R/position-stack.r, tests/testthat/test-position-stack.R
=> Fix stacking negative text

NEWS.md, R/stat-binhex.r, tests/testthat/test-geom-hex.R
=> Rename value to count in stat_binhex

R/facet-.r, R/layout.R
This was a design omission in the Facet redesign
=> Pass theme into draw_back and draw_front in Facet

R/layout.R
=> Switch axis with coord_flip

R/facet-null.r
=> Fix axis names for FacetNull

R/facet-grid-.r, R/facet-wrap.r
=> fix stacking of panels

NEWS.md, R/ggproto.r
Fixes #1826 
@wch could you please review?
=> Dynamically access ggproto super class

R/plot.r
Change "an variable" to "a variable"
=> Correct grammar in plot.r

R/plot.r
=> Fix typo plot.r

NEWS.md
Sorry, saw "minor improvements" and thought "oh, this change is a minor improvement; I'll put it here." Didn't notice that it was listed under the wrong version 😶
Again, sorry for making extra work
=> Move NEWS item to the correct version (oops)

R/geom-bar.r, R/position-stack.r
=> typo fix in manuals of geom_bar and position_stack

NEWS.md, R/geom-smooth.r, tests/testthat/test-geom-smooth.R
Fixes https://github.com/tidyverse/ggplot2/issues/2028
=> Order path data in GeomSmooth

R/sf.R
=> geom_sf() now respects shape/pch for POINT/MULTIPOINT geometries

R/axis-secondary.R
Unless I'm missing something about boring graphs, that is.
Refer: https://math.stackexchange.com/a/365787/90266
> Q: Is “monotonous” ever used as a synonym for “monotonic” in math?
> A: It is always wrong.
I tripped this error and had a chuckle, nonetheless.
=> Minor typo: monotonous -> monotonic

R/scale-continuous.r, man/scale_continuous.Rd
=> Spelling fix in docs

R/sf.R
=> addresses https://github.com/tidyverse/ggplot2/issues/2119

NEWS.md, R/coord-polar.r, tests/figs/coord-polar/secondary-axis-ticks-and-labels.svg, tests/testthat/test-coord-polar.r
Fixes #2072
Labels and ticks are now drawn for secondary axis when using polar coordinates.
=> Fixes secondary axis support for polar coordinates

DESCRIPTION, R/scale-.r
=> Use minor breaks that are part of the transformation

R/geom-histogram.r, man/geom_histogram.Rd
s/across a the levels/across the levels/
=> Minor spelling fix in docs

NEWS.md, R/labeller.r, tests/testthat/test-facet-strips.r
As described here: https://stackoverflow.com/questions/46347656/ggplot2-error-when-setting-facet-strip-to-element-blank
=> Fix bug when setting strips to element_blank

R/geom-linerange.r, man/geom_linerange.Rd
=> Add example of geom_errorbar() with position_dodge2()

revdep/README.md, revdep/cran.md, revdep/problems.md
=> revdep results

ISSUE_TEMPLATE.md
=> Updates link to reprex how-to in issues template

NEWS.md, R/zzz.r
Update startup messages should include links to RStudio Community and R4DS, closes #2410.
=> Update startup messages

vignettes/extending-ggplot2.Rmd
=> fix typo for Extending ggplot2

R/geom-abline.r, R/geom-boxplot.r, R/geom-contour.r, R/geom-crossbar.r, R/geom-curve.r, R/geom-density.r, R/geom-density2d.r, R/geom-dotplot.r, R/geom-errorbar.r, R/geom-errorbarh.r, R/geom-hex.r, R/geom-hline.r, R/geom-label.R, R/geom-linerange.r, R/geom-path.r, R/geom-point.r, R/geom-pointrange.r, R/geom-polygon.r, R/geom-raster.r, R/geom-rect.r, R/geom-ribbon.r, R/geom-rug.r, R/geom-segment.r, R/geom-text.r, R/geom-tile.r, R/geom-violin.r, R/geom-vline.r, R/sf.R
#2559 breaks support for rgba colour values. This undos the changes reinstating support
=> Revert #2559

README.Rmd, README.md
=> Add cheatsheet thumbnail to README

NEWS.md
* sf section now has a bullet, so that it's inline with everything else
* minor typo fixes
* consistent period at the end of each item AFTER `(@author)`
=> Copy edit NEWS.md

R/layout.R
Fixes revdep failure in ggthemes
=> Stricter test for theme$panel.ontop

R/geom-curve.r
@hrbrmstr can you please double check? I think this is just a simple omission.
=> Arrow.fill

R/plot-build.r
=> Use 'topleft' if plot.tag.position is NULL

R/facet-.r, R/facet-grid-.r, R/facet-wrap.r, R/geom-point.r, R/guide-legend.r, R/labeller.r, man/facet_grid.Rd, man/facet_wrap.Rd, man/geom_point.Rd, man/guide_legend.Rd, man/labeller.Rd, man/labellers.Rd, man/vars.Rd
Since R CMD check requires <5s
=> Reduce run-time of long examples

R/geom-label.R
=> Better test for label.size

R/backports.R, R/zzz.r
=> Overwrite vars with dplyr::vars, if available

NEWS.md
=> Add more tidy eval stuff to breaking changes in NEWS.md

R/plot-construction.r, tests/testthat/test-aes.r
=> Handle null aesthetics when labelling

R/stat-boxplot.r, tests/testthat/test-stat-boxplot.R
=> Remove missing data in StatBoxplot

NEWS.md, R/stat-smooth.r, tests/testthat/test-geom-smooth.R
This closes #2621 and reopens #2535. I don't know how to close both.
=> fix geom_smooth() and add regression tests. Closes #2621.

revdep/README.md, revdep/cran.md, revdep/problems.md
We checked 2105 reverse dependencies (1715 from CRAN + 390 from BioConductor), comparing R CMD check results across CRAN and dev versions of this package.
* We saw 101 new problems
* We failed to check 63 packages
Issues with CRAN packages are summarised below.
(This reports the first line of each new failure)
* bayesAB
checking tests ...
* bayesplot
checking examples ... ERROR
checking tests ...
* benchmark
checking whether package ‘benchmark’ can be installed ... WARNING
* benchr
checking tests ...
* billboarder
checking examples ... ERROR
checking re-building of vignette outputs ... WARNING
* BioPET
checking examples ... ERROR
* cellWise
checking re-building of vignette outputs ... WARNING
* census
checking re-building of vignette outputs ... WARNING
* choroplethr
checking examples ... …
=> updated revdeps for 2.2.1 vs 2.2.1.9000

R/margins.R, tests/figs/themes/rotated-x-axis-tick-labels.svg, tests/testthat/test-theme.r
=> revert hjust/vjust rotation for cases with mixed justification models

NEWS.md, R/aes.r, man/aes.Rd
=> Improve aes() news and documentation

.Rbuildignore, .github/lock.yml
* Add lock bot <https://probot.github.io/apps/lock/>.
* Add \.github to .Rbuildignore.
=> Add lock bot 🔒🤖

vignettes/releases/ggplot2-2.2.0.Rmd
=> Fix typo in 2.2.0 release vignette

DESCRIPTION
=> bump rlang version

man/theme_get.Rd
=> Run roxygen after #2643

man/ggtheme.Rd, man/scale_brewer.Rd, man/scale_gradient.Rd
Building theme docs after #2721. A couple link fixes to scales documentation came along for the ride.
=> Docs update after 2721

R/theme.r, man/theme.Rd
This is a PR to update the `theme()` documentation with feedback from #2727 and as a part of #2553 
includes:
- linking `element_*()` throughout doc
- documenting parameters together according to inheritance to reduce cognitive load
- updating the intro paragraph 
- linking to aesthetics vignette.
=> Update theme documentation

NEWS.md, R/fortify.r
=> Improve error from fortify.grouped_df when dplyr is not installed

R/labeller.r, man/label_bquote.Rd
The `default` argument appears to be unused, this PR updates the documentation.
=> Document now unused argument

NEWS.md, R/geom-boxplot.r
=> Define "width" parameter for geom_boxplot.

revdep/email.yml
I decided I should send out anyway, since that's policy.
=> Update email.yml for 3.1.0 release

.Rbuildignore
=> Add GOVERNANCE.md to Rbuildignore

.github/move.yml
* Add movebot config file
Since an issue was filed in reprex that belonged in ggplot2, it seems to me it's worth adding movebot to the repos for easier management.
=> Add movebot 🤖

NEWS.md
Remove useless word: "if you your plot" -> "if your plot".
=> remove typo

DESCRIPTION, GOVERNANCE.md
Again, thanks for inviting me to the core team. I'll do my best to contribute to the development of ggplot2!
=> Add Hiroaki Yutani to authors

R/performance.R, tests/testthat/test-stat-ellipsis.R
force col_names to make sure it is calculated before x is converted to a list
=> Fix #3014 force col_names

NEWS.md, R/labeller.r, tests/figs/facet-strips/switched-facet-strips.svg
=> Turn on clipping for facet strips on the left

R/labeller.r, man/labeller.Rd
Changed the use of revalue (from the plyr package) to base in the don't test example of labeller. 
-fixes #3083
=> fixes the dependency of labeller example on plyr in issue #3083

README.md
=> Reflect the typo fix of #3108 to README.md

R/geom-abline.r, man/geom_abline.Rd
=> Document mapping arg to geom_abline() without mentioning inherit.aes

CONTRIBUTING.md
There was an unnecessary apostrophe in the text, I removed it
=> Fixed typo by removing apostrophe

R/layer.r, man/layer.Rd
Suggested by @clauswilke here: https://github.com/tidyverse/ggplot2/issues/3207#issuecomment-477293511
=> Clarify layer_class is for internal use only

DESCRIPTION, NEWS.md
This puts devel ahead of CRAN again
=> bump devel version

DESCRIPTION, R/backports.R, R/coord-.r, R/facet-.r, R/facet-wrap.r, R/grob-dotstack.r, R/guide-colorbar.r, R/guide-legend.r, R/guides-.r, R/guides-grid.r, R/margins.R, R/position-stack.r, R/scale-.r, R/theme.r, cran-comments.md, inst/CITATION, man/max_height.Rd
**THIS IS NOT TO BE MERGED**
This PR represents a hot fix on top of v3.1.0 that applies the commits related to supporting the new unit spec in grid
=> Unit hotfix

_pkgdown.yml
Fix #3189
This PR add a menu item that links to the extension site... @Hadley is this what you had in mind?
=> Add menu-bar link to the extension site

man/ggplot2-ggproto.Rd
to reflect the change of #3223.
=> Regenerate docs for #3223

vignettes/ggplot2-specs.Rmd
A few small improvements to the aesthetic specifications vignette
=> Aesthetic spec tweaks

man/theme.Rd, tests/figs/themes/ticks-length.svg
(This is a follow up of #2934)
* Reflect the changes to `man/theme.Rd`.
* Generate a new visual case
=> Regenerate docs for #2934

R/position-dodge.r, man/position_dodge.Rd
The default behavior was changed in #2386 but the example wasn't updated.
I've opened this against master, but maybe it could go in the 3.2.0 release? @thomasp85 let me know if you want this PR against the release candidate branch instead.
=> Fix position_dodge2() example

revdep/README.md, revdep/failures.md, revdep/problems.md
DB at https://www.dropbox.com/s/llilyu97detb5xv/data.sqlite?dl=0
=> reverse dependencies

_pkgdown.yml
=> Add docsearch.

tests/testthat/test-scale_date.R, tests/testthat/test-sec-axis.R
(Since this PR is just about testing, I think it's safe to merge. But, I'll wait for the release of v3.2.0)
Fix #3284
=> Set locale explicitly before testing visual cases

_pkgdown.yml
Per @hadley 1-on-1…
* Wasn't actually searching the right site.
* Was harshing our vibe in the navbar.
=> Kill site search

NEWS.md, R/scale-discrete-.r, man/scale_discrete.Rd
=> add link to labs() and lims() in scale_(x|y)_discrete documentation TDD

R/stat-ellipse.R, man/stat_ellipse.Rd
fixes #2776 : data ellipse instead of confidence ellipse
=> fixes stat_ellipse misleading documentation

NEWS, NEWS.md, R/stat-density-2d.r, man/geom_density_2d.Rd
=> Add `adjust` param to `stat_density2d()` (fix #2860)

R/limits.r, man/lims.Rd
=> Improved lims() documentation

NEWS.md, R/utilities.r, man/gg_dep.Rd
=> Deprecate ggdep

R/scale-colour.r, R/scale-manual.r, man/scale_colour_continuous.Rd, man/scale_manual.Rd
closes https://github.com/tidyverse/ggplot2/issues/2863
=> advice users regarding colourblindness

tests/testthat/test-coord_sf.R
This is a cherry-pick of the #3378 commit intended for the 3.2.1 hotfix release
=> update sf label tests

NEWS.md
=> Fix a typo in NEWS

tests/testthat/test-facet-.r, tests/testthat/test-stat-sum.R
=> Use new function argument names for stat_summary in tests

vignettes/ggplot2-specs.Rmd
"makes it easy to specific colours" = "makes it easy to **choose** specific colours"
=> Add missing verb

DESCRIPTION, GOVERNANCE.md, man/ggplot2-package.Rd
As discussed in #3588, this is a PR adding myself as a core developer. Thanks @yutannihilation for the nomination! Thanks to @hadley for giving me the opportunity to contribute to ggplot2 as an intern, and thanks to everyone for taking the time to review my PRs over the last year. I look forward to contributing more in the future!
=> add Dewey Dunnington to package authors

DESCRIPTION, R/scale-viridis.r
=> Eliminate viridisLite dependency

R/geom-dotplot.r, man/geom_dotplot.Rd
=> Typo fix: Remove double "just" in documentation

R/aes.r, man/aes.Rd
Hello :-) Is it intended that this link directs to the package-level docu, instead of the relevant function?
=> Update link in docu

R/geom-sf.R, man/ggsf.Rd, tests/testthat/test-geom-sf.R
=> Use EPSG code instead of proj4string "+init=epsg:XXXX" in test and example

R/annotation-map.r, man/annotation_map.Rd
=> Fix typos in examples of annotation_map() (for master)

R/scale-manual.r
=> Allow more values than breaks in manual scale

R/limits.r, man/lims.Rd
=> improve documentation for xlim and ylim in limits.r

R/geom-histogram.r, man/geom_histogram.Rd
=> Added description of scale_x_binned to geom_histogram

R/theme-elements.r
=> Change structure of error message to correct grammar

R/labeller.r
This PR fixes the failing examples from `facet_grid()` in the current master. The fix was only applied to the release branch and has been copied over
=> Fix strips from interactions

R/geom-bar.r, man/geom_bar.Rd
=> Improve geom_bar documentation (#3751)

tests/testthat/test-theme.r
=> fix unit test. 

revdep/README.md, revdep/failures.md, revdep/problems.md
@thomasp85 
[SQL file](https://www.dropbox.com/sh/y00i50n0hlm7qnm/AABU7WoD-hjfVmsVIb6Jprnza?dl=0)
We checked 3157 reverse dependencies (2685 from CRAN + 472 from BioConductor), comparing R CMD check results across CRAN and dev versions of this package.
* We saw 30 new problems
* We failed to check 79 packages
Issues with CRAN packages are summarised below.
(This reports the first line of each new failure)
* apyramid
checking tests ...
* autocogs
checking examples ... ERROR
checking tests ...
* bayesdfa
checking installed package size ... NOTE
checking for GNU extensions in Makefiles ... NOTE
* benchr
checking tests ...
* biclustermd
checking tests ...
* dabestr
checking examples ... ERROR
checking tests ...
* DeLorean
checking installed package size ... NOTE
checking dependencies in R …
=> revdep update

man/annotation_logticks.Rd
The last PR I merged didn't have all the docs updated to the latest build. This fixes that.
=> rerun docs

R/stat-summary.r, man/hmisc.Rd
=> Check for availability of Hmisc in examples

NEWS, NEWS.md
#3783 inadvertently deleted the entire NEWS.md file, along with adding entries to the old NEWS file. This PR hopefully reverses that
=> Recreate NEWS.md and move new entry froms NEWS to NEWS.md

R/geom-histogram.r, man/geom_density.Rd, man/geom_histogram.Rd, man/geom_ribbon.Rd
Remove a dot and regenerate docs (It seems some document changes are not reflected to the actual docs yet)
=> Remove a mysterious dot and regenerate docs

DESCRIPTION, R/zzz.r
Reverts tidyverse/ggplot2#3902
=> Revert "Import lifecycle"

vignettes/ggplot2-specs.Rmd
=> Fix the name of Albert H. Munsell

R/scale-.r, man/discrete_scale.Rd
Resolved the conflict in #3969 by starting over.
=> Fixed typo in discrete_scales doc 

NEWS.md, R/geom-function.R, R/stat-function.r, man/geom_function.Rd, tests/testthat/test-stat-function.R
=> Make stat_function() work with empty input data.

R/scale-discrete-.r
=> allow NULL to be passed through new_mapped_discrete()

tests/testthat/test-stat-function.R
Add a few unit tests that should have been there all along.
=> missing stat_function() unit tests

R/position-dodge.r, man/position_dodge.Rd, tests/testthat/test-geom-boxplot.R, tests/testthat/test-position-dodge2.R
=> Remove iris

tests/testthat/test-build.r, tests/testthat/test-data.r, tests/testthat/test-position-dodge2.R
Just happened to find these misuses.
=> Do not pass stringsAsFactors to data_frame()

R/grouping.r, tests/testthat/test-aes-grouping.r
hi this is my proposed fix for #4072, along with a test that fails using current master.
=> Fix aes(groupS)

NEWS.md, R/stat-bin.r, man/geom_histogram.Rd, tests/testthat/test-stat-bin.R
Fix #3522 
Though this pull request introduces no code change (except for a test), I think this is worth adding a NEWS so that the users might notice this hidden feature (but, as I did nothing, I didn't add my name on the NEWS item).
=>  Document computed variable `width` and add a test 

.github/workflows/pr-commands.yaml
=> Fix a typo in pr-command.yaml

R/geom-text.r, man/geom_text.Rd
Noticed a small typo - thought I'd submit the correction as my first contribution!
=> Corrected type: cobination -> combination

R/fortify-map.r, man/map_data.Rd
=> Fixed typo in map_data() documentation

R/position-jitterdodge.R, man/position_jitterdodge.Rd
Remove leading space in the  document of position_jitterdodge()
=> Remove leading space in document

_pkgdown.yml
I will also make sure pkgdown doesn't let one have duplicate elements. (or maybe pkgdown will throw an error?)
=> temporary pkgdown fix

README.Rmd, README.md
The ggplot2 cheat sheet file name changed so I updated the link here.
=> update cheat sheet link

NEWS.md, R/position-stack.r
Fix #4367 make sure that position_stack doesn't convert numeric NA to to logical NA
=> Ensure output is numeric even if ifelse clause is NA

DESCRIPTION, NEWS.md
=> Upgrade rlang dependency to >= 1.0.0

CONTRIBUTING.md, GOVERNANCE.md
=> Update COC links

NEWS.md, R/geom-linerange.r
=> Pass na.rm from geom_linerange to GeomSegment

R/position-dodge2.r, tests/testthat/test-position-dodge2.R
Reverted PR #4936 for #4327 
Added test for the bug with the previous solution
=> revert pr for position_dodge2

R/fortify.r, tests/testthat/_snaps/fortify.md
=> Improve the error message of fortify.default()

NEWS.md, R/stat-smooth.r
This PR attempts to fix #5053 based on @clauswilke's suggestion.
=> Drop `weight` aesthetic quietly in `stat_smooth()`

R/geom-text.r, man/geom_text.Rd, man/ggplot2-package.Rd
=> Fix typos in geom_text dcumentation

NEWS.md, R/facet-grid-.R, R/quick-plot.R, R/stat-smooth.R
This PR aims to contribute to #5233.
Briefly, I thought it safer to put in a PR to edit the RC than to edit directly. 
Note that the PR is for merging into the RC branch instead of the main branch.
This way, it is easier to track what I'm proposing to change.
=> Release candidate changes

NEWS.md
https://github.com/tidyverse/ggplot2/issues/5307
=> markdown typos

NEWS.md, man/facet_grid.Rd, man/facet_wrap.Rd, vignettes/articles/faq-customising.Rmd, vignettes/ggplot2.Rmd
This PR adds the url check / news polish items from #5588 to the new RC branch. Also missed regenerating some documentation which is also added.
=> Initial release tasks 3.5.0

tests/testthat/test-coord_sf.R
This PR aims to fix #5742.
It appears I had missed the skipping when writing these tests.
=> Skip sf tests if not installed

R/facet-.R
See #6082
PR suggested by @teunbrand
=> Fixing misnamed panels for facet_wrap (#6082)

R/geom-map.R, man/geom_map.Rd
=> Typo in geom-map.R

tests/testthat/test-utilities-checks.R
https://github.com/tidyverse/ggplot2/blob/b29b83151a8415093cadc8aead5024452ed7eae6/R/utilities-checks.R#L315-L318
=> Fix ragg version check in test skip

vignettes/articles/faq-annotation.Rmd, vignettes/articles/faq-axes.Rmd, vignettes/articles/faq-reordering.Rmd
=> Fix typos in the vignette

R/plot-build.R
fix https://github.com/tidyverse/ggplot2/issues/6234
=> add padding cell in final gtable for NULL `plot.margin`

R/scale-linewidth.R, man/scale_linewidth.Rd
=> Fixes a small typo in docstring for scale_linewidth

R/coord-.R, R/geom-defaults.R, R/labels.R, man/get_geom_defaults.Rd, man/labs.Rd
This PR aims to fix a few mistakes that came from grafting newer function upon an older base.
=> Forward compatibility: fix mistakes

R/guide-legend.R, man/guide_legend.Rd
Edits to documentation for 'position' in guide_legend.R.
Edits from feedback in #6451 (closed)
=> position param updated with extra notes
